### PR TITLE
Fix enum reflection test for jdk15+

### LINKED ISSUE #9216: jdk15 test_getParameters Number of methods should be 2 for enum class MOOD
https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/d6f6d9c...8d72cb3
seems related to `8241798: Allow enums to have more constants`

https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/171
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_mac_OpenJDK/165
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_ppc64_aix_OpenJDK/96
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_ppc64le_linux_OpenJDK/174
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_windows_OpenJDK/160
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK/163
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_xl_OpenJDK/163
JCL_Test_0
JCL_Test_1
JCL_Test_2
JCL_Test_openj9_none_SCC_0
JCL_Test_openj9_none_SCC_1
```
FAILED: test_getParameters
java.lang.AssertionError: Number of methods should be 2 for enum class MOOD
	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.reflect.Test_Executable.checkExecutableCount(Test_Executable.java:367) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at org.openj9.test.java.lang.reflect.Test_Executable.test_getParameters(Test_Executable.java:156) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) from jrt:/java.base
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) from jrt:/java.base
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) from jrt:/java.base
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) from jrt:/java.base
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestRunner.privateRun(TestRunner.java:648) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestRunner.run(TestRunner.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.runSuites(TestNG.java:1049) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.run(TestNG.java:1017) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.privateMain(TestNG.java:1354) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.main(TestNG.java:1323) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5845349(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/lib/testng.jar)
```

### PR DESCRIPTION
**Pull request by pshipton**
Enum classes have a third synthetic method in jdk15+, `$values()`.
Also fixed some mistakes in the enum test.

Fixes #9216

[ci skip]

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Note PR testing for jdk15 will fail until the latest jdk15 JCL material is promoted. I'll start a new promotion build when this is reviewed and merged.
Tested a previously failing jdk15 build via grinder here https://ci.eclipse.org/openj9/view/Test/job/Grinder/779

Also tested jdk8 to ensure this doesn't break testing for older versions
via grinder https://ci.eclipse.org/openj9/view/Test/job/Grinder/781

File: test/functional/Java8andUp/src/org/openj9/test/java/lang/reflect/Test_Executable.java [hunk 1]
```diff
@@ -351,10 +359,21 @@ public void test_getParameters() {
 			}
 
 			checkDeclaringExecutable(parameters[0], methods[1]);
-			checkParameterName(methods[1], parameters[0], "name");
-			checkParameterModifiers(methods[1], parameters[0], ACC_MANDATED);
+			checkParameterName(methods[1], parameters[0], "arg0");
+			checkParameterModifiers(methods[1], parameters[0], ACC_DEFAULT);
```
Comment (DanHeidinga) [inline test/functional/Java8andUp/src/org/openj9/test/java/lang/reflect/Test_Executable.java:363]: why ACC_DEFAULT instead of ACC_MANDATED?

Comment (pshipton) [reply test/functional/Java8andUp/src/org/openj9/test/java/lang/reflect/Test_Executable.java:363]: @DanHeidinga When the code is compiled without `-parameters`, getModifiers() on the parameters returns 0. See the other tests without `-parameters`. The only reason it worked with ACC_MANDATED before is because the "without parameters" test was using the wrong "with parameters" class.

**Comment by DanHeidinga** [comment]
Given the testing @pshipton did in Grinders, will merge as is without additional builds
