### PR TITLE
Handle mismatched env setup between server and client

### LINKED ISSUE #5163: JITaas server in non-remote AOT mode crashes while it's connected by -Xnojit JITaas client
Run `_cmdLineTest_J9test_SE80_0` on the client side and the JITaas server in non-remote AOT mode crashes while testing `Testing: Xnojit`.

Server setup: 
- Non-remote AOT mode (TR_EnableJITaaSRemoteAOT is not set) 
- DisableDelayRelocationForAOTCompilations

Client setup: 
- TEST_FLAGS=AOT 
- EXTRA_OPTIONS=" -XX:JITaaSClient "
- export TR_EnableJITaaSRemoteAOT=1
- DisableDelayRelocationForAOTCompilations

```
Running command: "/root/home/ahuo/sdk/jvmxa6480/jre/bin/java" -Xshareclasses:name=cmdLineTest_J9test_SE80_0 -Xscmx400M -Xscmaxaot256m -Xcompressedrefs  -Xdump -Xnojit -cp "/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/utils/utils.jar" VMBench.FibBench
```

```
#12 <signal handler called>
#13 0x00007fb8131134cd in J9::X86::AheadOfTimeCompile::initializeAOTRelocationHeader (this=0x7fb70100abe0, 
    relocation=0x7fb70113f070)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp:1159
#14 0x00007fb813332e33 in TR::IteratedExternalRelocation::initializeRelocation (this=0x7fb70113f070, codeGen=0x7fb701006310)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/codegen/Relocation.cpp:514
#15 0x00007fb81311071a in J9::X86::AheadOfTimeCompile::processRelocations (this=0x7fb70100abe0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp:114
#16 0x00007fb812dc7dbe in J9::CodeGenerator::processRelocations (this=0x7fb701006310)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/codegen/J9CodeGenerator.cpp:2878
#17 0x00007fb813321bd1 in OMR::CodeGenPhase::performProcessRelocationsPhase (cg=0x7fb701006310, phase=0x7fb701006880)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/codegen/OMRCodeGenPhase.cpp:166
#18 0x00007fb813321a80 in OMR::CodeGenPhase::performAll (this=0x7fb701006880)
--Type <RET> for more, q to quit, c to continue without paging--
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/codegen/OMRCodeGenPhase.cpp:133
#19 0x00007fb81331690f in OMR::CodeGenerator::generateCode (this=0x7fb701006310)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/codegen/OMRCodeGenerator.cpp:1312
#20 0x00007fb813340249 in OMR::Compilation::compile (this=0x7fb701000000)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/compile/OMRCompilation.cpp:1120
#21 0x00007fb812e27394 in TR::CompilationInfoPerThreadBase::compile (this=0x7fb80fb84a50, vmThread=0x25f4600, 
    compiler=0x7fb701000000, compilee=0x7fb80f769588, vm=..., optimizationPlan=0x7fb7545fa400, scratchSegmentProvider=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:8709
#22 0x00007fb812e25734 in TR::CompilationInfoPerThreadBase::wrappedCompile (portLib=0x7fb81a995380 <j9portLibrary>, 
    opaqueParameters=0x7fb80f769300)
```

### PR DESCRIPTION
**Pull request by a7ehuo**
[skip ci]

The client will not request a remote compilation
when `canDoRelocatableCompile` is false and `-Xnojit` is set.
If it was allowed, the server would do a JIT compilation
which contradicts `-Xnojit` set on the client side.
Meanwhile, when the server receives a compilation request
from the client with `_useAotCompilation` set but
the remote AOT is disabled on the server,
the server will discard the compilation request.

Fixes #5163

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

File: runtime/compiler/control/CompilationThread.cpp [hunk 1]
```diff
@@ -6960,6 +6960,13 @@ TR::CompilationInfoPerThreadBase::preCompilationTasks(J9VMThread * vmThread,
                   }
                }
             }
+         else
+            {
+            // When both canDoRelocatableCompile and TR::Options::canJITCompile() are false,
+            // remote compilation request should not be used.
+            doLocalCompilation = true;
+            }
+
```
Comment (mpirvu) [inline runtime/compiler/control/CompilationThread.cpp]: My suggestion would be to move the code below under `if (TR::Options::canJITCompile())`. Then you don't have to add this new code.

File: runtime/compiler/control/JITaaSCompilationThread.cpp [hunk 2]
```diff
@@ -3623,7 +3624,7 @@ TR::CompilationInfoPerThreadRemote::processEntry(TR_MethodToBeCompiled &entry, J
          // This behaviour is consistent with non-JITaaS
          ((TR_J9JITaaSServerSharedCache *) _vm->sharedCache())->setStream(stream);
 
-      if (!ramMethod)
+      if ((!ramMethod) || (entry._useAotCompilation && !enableJITaaSRemoteAOT))
```
Comment (mpirvu) [inline runtime/compiler/control/JITaaSCompilationThread.cpp]: I do not understand the need for this code. The case with ramMethod==0 happens when the client terminates and wants to inform the server that it can delete all cached data related to this client.

Comment (a7ehuo) [reply runtime/compiler/control/JITaaSCompilationThread.cpp]: The server shouldn't process the AOT compilation request when enableJITaaSRemoteAOT is false on the server side. In this case, we need to abort the compilation request received from the client side. I thought we could piggyback on this `ramMethod==0` case to quit the compilation on the server side. Maybe not? What would be a better way to quit/ignore the compilation request in this stage on the server side?

Comment (mpirvu) [reply runtime/compiler/control/JITaaSCompilationThread.cpp]: I would like to understand why `enableJITaaSRemoteAOT` is needed at the server side. As long as the capability exists (and currently we have this capability) the server should do whatever the client tells it to do. If the server is not supposed to perform an AOT compilation the client should not have sent the request in the first place.

Comment (a7ehuo) [reply runtime/compiler/control/JITaaSCompilationThread.cpp]: Good point. `enableJITaaSRemoteAOT` doesn't  apply to the server anymore. The following code should to be changed: 
```
eligibleForRelocatableCompile =
            (enableJITaaSRemoteAOT || !entry->isOutOfProcessCompReq()) && // disable remote JITaaS AOT until it's working
````
to 
```
eligibleForRelocatableCompile =
            (enableJITaaSRemoteAOT || entry->isOutOfProcessCompReq()) &&
````

Comment (mpirvu) [reply runtime/compiler/control/JITaaSCompilationThread.cpp]: I would say that if we are at the server `eligibleForRelocatableCompile` should always be true because all of the preliminary checks have already been done at the client. We just need some information from the client to the server that it wants an AOT compilation.

Comment (mpirvu) [reply runtime/compiler/control/JITaaSCompilationThread.cpp]: I see this being passed in `entry._useAotCompilation  = std::get<12>(req);` so we have the info that the client wants an AOT compilation

Comment (mpirvu) [reply runtime/compiler/control/JITaaSCompilationThread.cpp]:
```
  // If we are allowed to do relocatable compilations, just do it
   // Note that currently we don't support out-of-process relocatable compilations
   if (canDoRelocatableCompile)
      {
      _vm = TR_J9VMBase::get(_jitConfig, vmThread, TR_J9VMBase::AOT_VM);
      entry->_useAotCompilation = true;

      if (_compInfo.getPersistentInfo()->getJITaaSMode() == CLIENT_MODE && enableJITaaSRemoteAOT)
         {
         entry->setRemoteCompReq();
         }
      }
```
The comment needs some adjustment.
The test of `enableJITaaSRemoteAOT` could disappear and maybe in another PR replaced with a test on how expensive the compilation is expected to be. Cheap ones could be done locally while expensive ones could be done remotely.

Comment (a7ehuo) [reply runtime/compiler/control/JITaaSCompilationThread.cpp]: @dmitry-ten and I are working together to remove `TR_EnableJITaaSRemoteAOT` on both the client and the server side.

**Comment by a7ehuo** [comment]
@mpirvu Updated the client side change. The removal of the env flag will be in a separate PR.

File: runtime/compiler/control/CompilationThread.cpp [hunk 3]
```diff
@@ -2008,7 +2008,7 @@ bool TR::CompilationInfo::shouldRetryCompilation(TR_MethodToBeCompiled *entry, T
    if (entry->_compErrCode != compilationOK &&
       useSeparateCompilationThread()) // Retrials for compilation on application thread are not implemented
       {
-      if (entry->_compilationAttemptsLeft > 0)
+      if ((entry->_compilationAttemptsLeft > 0) && TR::Options::canJITCompile())
```
Comment (mpirvu) [inline runtime/compiler/control/CompilationThread.cpp]: Suggestion: I see this pattern repeating a few times `(entry->_compilationAttemptsLeft > 0) && TR::Options::canJITCompile()`. This can be simplified if we always set entry->_compilationAttemptsLeft to 1 if TR::Options::canJITCompile() is false.
