### PR TITLE
Correct format of errno2 output in create Thread exceptions

### LINKED ISSUE #5048: Format z/OS errno2 values for OOME at j.l.Thread.start()
The exception detail message for OutOfMemoryError at `java.lang.Thread.start()` on z/OS reports the errno2 value as a 64-bit hex value. For example:
```
Exception in thread "main" java.lang.OutOfMemoryError: Failed to create a thread: retVal -1073741830, errno 132 (0x84), errno2 -1055784930 (0xffffffffc112001e) at java.lang.Thread.start(Thread.java:982) at HelloWorld3.main(HelloWorld3.java:51)
```
It would be more user-friendly to report the errno2 as the lower 8 hex digits only, 0xc112001e in the example above. The decimal value is not used on z/OS for any of the errno2 documentation nor for the error code diagnostic tools such as `edcmtext` or `bpxmtext`. The high 8 hex digits are not used and because the are all 0xf they make the errno2 value look like a negative number, which is confusing.

The z/OS documentation confirms that only the lower 8 hex digits are signficant for errno2 values. For example:

https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3.ceea100/edcun.htm

> The range of values for the XL C/C++ runtime library is 0X'C0000000' through 0X'CFFFFFFF'.

### PR DESCRIPTION
**Pull request by pshipton**
Only 32-bits of errno2 are used, and only the hex output is required.

Fixes #5048

### CODE REVIEW

**Comment by pshipton** [comment]
Testing z/OS sanity in internal build 413017

**Comment by pshipton** [comment]
^ Just a rebase

**Comment by pshipton** [comment]
New output
`Exception in thread "main" java.lang.OutOfMemoryError: Failed to create a thread: retVal -1073741830, errno 112 (0x70), errno2 0xb51025d`

File: runtime/vm/vmthread.c [hunk 1]
```diff
@@ -1973,10 +1973,10 @@ setFailedToForkThreadException(J9VMThread *currentThread, IDATA retVal, omrthrea
 	PORT_ACCESS_FROM_VMC(currentThread);
 
 	errorMessage = j9nls_lookup_message(J9NLS_DO_NOT_PRINT_MESSAGE_TAG | J9NLS_DO_NOT_APPEND_NEWLINE,
-			J9NLS_VM_THREAD_CREATE_FAILED_WITH_ERRNO2, NULL);
+			J9NLS_VM_THREAD_CREATE_FAILED_WITH_32BIT_ERRNO2, NULL);
 
 	if (errorMessage) {
-		bufLen = j9str_printf(PORTLIB, NULL, 0, errorMessage, retVal, os_errno, os_errno, os_errno2, os_errno2);
+		bufLen = j9str_printf(PORTLIB, NULL, 0, errorMessage, retVal, os_errno, os_errno, (U_32)os_errno2);
```
Comment (keithc-ca) [inline runtime/vm/vmthread.c]: This may trigger a compiler warning (changing from signed to unsigned together with a size change).
The warning can be avoided by casting `(U_32)(UDATA)os_errno2`.

File: runtime/nls/j9vm/j9vm.nls [hunk 2]
```diff
@@ -1311,14 +1311,8 @@ J9NLS_VM_DIAGNOSTIC_COLLECTOR_NOT_SUPPORTED.system_action=The JVM continues to r
 J9NLS_VM_DIAGNOSTIC_COLLECTOR_NOT_SUPPORTED.user_response=Refer to the IBM SDK documentation
 # END NON-TRANSLATABLE
 
-# retVal, errno and errno2 should not be translated. They refer to internal variables.
-J9NLS_VM_THREAD_CREATE_FAILED_WITH_ERRNO2=Failed to create a thread: retVal %1$zd, errno %2$zd (0x%3$zx), errno2 %4$zd (0x%5$zx)
+J9NLS_VM_THREAD_CREATE_FAILED_WITH_ERRNO2=
```
Comment (keithc-ca) [inline runtime/nls/j9vm/j9vm.nls]: Perhaps it would help to have a comment indicating this key is now unused?

**Comment by pshipton** [comment]
Suggestions added.

File: runtime/vm/vmthread.c (hunk 1 above)
Comment (pshipton) [reply runtime/vm/vmthread.c]: I could just cast to I_32, but I already added the UDATA cast.

Comment (keithc-ca) [reply runtime/vm/vmthread.c]: FYI, casting to `I_32` wouldn't match the format for that parameter.

**Comment by keithc-ca** [comment]
Jenkins compile zlinux jdk11
