### PR TITLE
Check the free disk space size when setting default cache size

### LINKED ISSUE #2174: We should use a smaller shared cache size when there is not enough disk space
We are seeing test failures like the following due to limited disk space 

> Running command: "/home/jenkins/workspace/PullRequest-Sanity-JDK10-linux_x86-64_cmprssptrs-OpenJ9/build/linux-x86_64-normal-server-release/images/jdk/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xshareclasses:name=bcienabled,enableBCI  -Xdump    -agentlib:jvmtitest=test:aln001 -cp "/home/jenkins/workspace/PullRequest-Sanity-JDK10-linux_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
> 19:05:48 Time spent starting: 38 milliseconds
> 19:05:48 Time spent executing: 98 milliseconds
> 19:05:48 Test result: FAILED
> 19:05:48 Output from test:
> 19:05:48  [ERR] JVMSHRC561E Failed to initialize the shared classes cache, there is not enough space in the file system. Available free disk space bytes = 196653056, requested bytes = 314572800.
> 19:05:48  [ERR] JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
> 19:05:48  [ERR] Error: Could not create the Java Virtual Machine.
> 19:05:48  [ERR] Error: A fatal exception has occurred. Program will exit.
> 19:05:48 >> Success condition was not found: [Return code: 0]

### PR DESCRIPTION
**Pull request by hangshao0**
Set default shared cache size to 64MB if the free disk space is less
than 6GB.

Fixes #2174

Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

File: runtime/shared_common/shrinit.cpp [hunk 1]
```diff
@@ -80,6 +80,7 @@ extern "C" {
 
 
 #define SHRINIT_NAMEBUF_SIZE 256
+#define SHRINIT_LOW_FREE_DISK_SIZE (1024 * 1024 * 1024)
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: Lets pick something bigger, say 3GB - 6GB, so the shared cache is only taking 10% - 5% of the available space.

File: runtime/shared_common/shrinit.cpp [hunk 2]
```diff
@@ -2720,14 +2722,20 @@ ensureCorrectCacheSizes(J9JavaVM *vm, J9PortLibrary* portlib, U_64 runtimeFlags,
...
 			&& (*cacheSize > maxSize)
 		) {
 			adjustCacheSizes(portlib, verboseFlags, piconfig, maxSize);
 		}
+	} else {
+		if (is64BitPlatDefaultSize) {
+			if (isFreeDiskSpaceLow(vm, &maxSize)) {
+				Trc_SHR_Assert_True(*cacheSize > maxSize);
+				adjustCacheSizes(portlib, verboseFlags, piconfig, maxSize);
+			}
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: There should be tracepoints if isFreeDiskSpaceLow fails. Should we fallback to 64M if we can't check the free space?

Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: I will add the tracepoints inside isFreeDiskSpaceLow(). It is safer to use 64MB if we cannot check the free space.

**Comment by hangshao0** [comment]
Updates:
1. New trace points added into isFreeDiskSpaceLow(). Use 64MB if an error occurs inside isFreeDiskSpaceLow().
2. Change SHRINIT_LOW_FREE_DISK_SIZE  to 6GB
3. Test 43: LIR 1445.1 checks if the debug area is 3m, which might fail if we fallback to 64m, as the debug area size will be adjust proportionally to the shared cache size. So add "-Xscmx64m" to  Test 42: LIR 1445.1 when creating the test cache.

File: runtime/shared_common/shrinit.cpp [hunk 3]
```diff
@@ -4849,4 +4857,42 @@ getModule(J9VMThread* vmThread, U_8* className, UDATA classNameLength, J9ClassLo
...
+	/* check for free disk space */
+	J9FileStatFilesystem fileStatFilesystem;
+	if (0 == j9file_stat_filesystem(cacheDirName, 0, &fileStatFilesystem)) {
+		if (fileStatFilesystem.freeSizeBytes >= SHRINIT_LOW_FREE_DISK_SIZE) {
+			ret = false;
+		} else {
+			Trc_SHR_INIT_isFreeDiskSpaceLow_DiskSpaceLow(fileStatFilesystem.freeSizeBytes);
+		}
+	} else {
+		Trc_SHR_INIT_isFreeDiskSpaceLow_StatFileSystemFailed(cacheDirName);
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: the tracepoint should include error information, i.e. get_last_error, from j9file_stat_filesystem

File: runtime/shared_common/shrinit.cpp [hunk 4]
```diff
@@ -4849,4 +4857,42 @@ getModule(J9VMThread* vmThread, U_8* className, UDATA classNameLength, J9ClassLo
...
+	}
+done:
+	if (ret) {
+		*maxsize = J9_SHARED_CLASS_CACHE_DEFAULT_SOFTMAX_SIZE_64BIT_PLATFORM;
+		Trc_SHR_INIT_isFreeDiskSpaceLow_SetMaxSize(J9_SHARED_CLASS_CACHE_DEFAULT_SOFTMAX_SIZE_64BIT_PLATFORM);
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: To avoid future problems, better to use *maxsize in the tracepoint.

File: runtime/shared_common/shrinit.cpp (hunk 3 above)
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

File: runtime/shared_common/shrinit.cpp (hunk 4 above)
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

File: runtime/shared_common/shrinit.cpp [hunk 5]
```diff
@@ -4849,4 +4857,42 @@ getModule(J9VMThread* vmThread, U_8* className, UDATA classNameLength, J9ClassLo
...
+static bool
+isFreeDiskSpaceLow(J9JavaVM *vm, U_64* maxsize)
+{
+	char cacheDirName[J9SH_MAXPATH];
+	memset(cacheDirName, 0, J9SH_MAXPATH);
+	bool ret = true;
+	PORT_ACCESS_FROM_JAVAVM(vm);
+
+	if (-1 == SH_OSCache::getCacheDir(PORTLIB, vm->sharedCacheAPI->ctrlDirName, cacheDirName, J9SH_MAXPATH, J9PORT_SHR_CACHE_TYPE_PERSISTENT)) {
+		goto done;
```
[the remark this answers is not in the document]
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: There is already a tracepoint inside SH_OSCache::getCacheDir() if it returns -1.

[the remark this answers is not in the document]
Comment (pshipton) [reply runtime/shared_common/shrinit.cpp]: A couple of problems with that. 
- Trc_SHR_OSC_getCacheDir_j9shmem_getDir_failed is not an exception tracepoint but should be. There is a TraceExit-Exception keyword.
- there is no context, it won't be possible to tell the problem occurred from isFreeDiskSpaceLow()

[the remark this answers is not in the document]
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed.

**Comment by pshipton** [comment]
jenkins test all jdk10

**Comment by pshipton** [comment]
jenkins test all all jdk10

**Comment by SueChaplain** [comment]
@hangshao0 Please open an issue for the doc change: https://github.com/eclipse/openj9-docs/issues/new?template=new-documentation-change.md

As this is the first time the template will be used, please feed back any suggestions for changes.

**Comment by hangshao0** [comment]
@SueChaplain, issue created. I find the template is quite easy to follow.
