### PR TITLE
JDK15 enable NPE extended message by default

### LINKED ISSUE #10296: JEP 358 NullPointerException messages enabled by default for jdk 15
From OpenJDK 15 release notes.
"
Enable ShowCodeDetailsInExceptionMessages by default (JDK-8233014)
hotspot/runtime
The default of the flag ShowCodeDetailsInExceptionMessages was changed to 'true'. The helpful NullPointerException messages of JEP 358 are now printed by default. The messages contain snippets of the code where the NullPointerException was raised.

App deployers should double check the output of their web applications and similar usage scenarios. The NullPointerException message could be included in application error messages or be displayed by other means in the app. This could give remote attackers valuable hints about a potential vulnerable state of the software components being used.

An example message is 'Cannot read field "c" because "a.b" is null'. The attacker knows that field b of a contains null which might be unintended and offer an opportunity for an attack. For more details of what the message can contain see above mentioned JEP 358.
"

### PR DESCRIPTION
**Pull request by JasonFengJ9**
As per earlier discussion https://github.com/eclipse/openj9/issues/10296#issuecomment-668189594
_The cost of retrieving the extended NPE message applies when NullPointerException.getMessage() is invoked, otherwise it is same as previous Java version.
If the exception is caught with no logging, there won't be any penalty._

There is no references to `NullPointerException.getMessage()` within `OpenJ9 JCL` code, there are a few `Throwable.getMessage()` which might invoke `NPE` message if the `Throwable` in question is a `NullPointerException`. 
```
MethodHandles.java
729: e.getCause().getMessage()); 
https://github.com/eclipse/openj9/blob/0aec295571c6c25927af41a629bc915c2129642e/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L726-L729
MethodType.java
404: NoClassDefFoundError noClassDefFoundError = new NoClassDefFoundError(cause.getMessage()); 
https://github.com/eclipse/openj9/blob/0aec295571c6c25927af41a629bc915c2129642e/jcl/src/java.base/share/classes/java/lang/invoke/MethodType.java#L403-L404
MethodTypeHelper.java
274: NoClassDefFoundError noClassDefFoundError = new NoClassDefFoundError(cause.getMessage()); 
https://github.com/eclipse/openj9/blob/0aec295571c6c25927af41a629bc915c2129642e/jcl/src/java.base/share/classes/java/lang/invoke/MethodTypeHelper.java#L273-L274
``` 
Also searched `OpenJDK` `java.base` code, there is no reference to `NullPointerException.getMessage()` either. Similarly there are references to `Throwable.getMessage()` , `Exception.getMessage()`.

Tested in person builds with this PR and no issue found.

closes #10296 

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
@gacholio could you please review?

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins test sanity,extended zlinux jdk15

File: runtime/vm/jvminit.c [hunk 1]
```diff
@@ -2150,13 +2150,14 @@ IDATA VMInitStages(J9JavaVM *vm, IDATA stage, void* reserved) {
 				j9port_control(OMRPORT_CTLDATA_VMEM_PERFORM_FULL_MEMORY_SEARCH, 0);
 			}
 
+#if JAVA_SPEC_VERSION >= 15
```
Comment (pshipton) [inline runtime/vm/jvminit.c:2153]: Does this feature need to be restricted to jdk15? If not, turning it on via the option should be allowed for all versions.

Comment (gacholio) [reply runtime/vm/jvminit.c:2153]: I was under the impression the feature was new for JDK15 of the RI. Having said that, it should work fine with older JCLs.

Comment (gacholio) [reply runtime/vm/jvminit.c:2153]: Does the Throwable method which retrieves the extended message exist pre-JDK15?

Comment (JasonFengJ9) [reply runtime/vm/jvminit.c:2153]: Only JDK15+ has the support of NPE helpful message via https://github.com/ibmruntimes/openj9-openjdk-jdk15/blob/425fa83a6d01232c99cb7eaa3f5ff9f724c7b27c/src/java.base/share/classes/java/lang/NullPointerException.java#L131

So it won't work for pre-JDK15 versions even it is on by default.

https://github.com/eclipse/openj9/issues/9844 requires JCL patch.

Comment (JasonFengJ9) [reply runtime/vm/jvminit.c:2153]: > Does the Throwable method which retrieves the extended message exist pre-JDK15?

No, only JDK15+ `NullPointerException` has the method to retrieve the extended messages.

Comment (pshipton) [reply runtime/vm/jvminit.c:2153]: Ok, it can be dealt with via https://github.com/eclipse/openj9/issues/9844 then.
