### PR TITLE
Skip package access check for classes within same module

### LINKED ISSUE #859: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.cs.ext")
@aguibert mentioned a problem running Liberty on OpenJ9 Java 9

```
>Stack Dump = java.lang.ExceptionInInitializerError
>    at java.lang.J9VMInternals.ensureError(java.base@9-internal/J9VMInternals.java:191)
>    at java.lang.J9VMInternals.recordInitializationFailure(java.base@9-internal/J9VMInternals.java:180)
>    at java.nio.charset.Charset.lookupExtendedCharset(java.base@9-internal/Charset.java:456)
>    at java.nio.charset.Charset.lookup2(java.base@9-internal/Charset.java:486)
>    at java.nio.charset.Charset.lookup(java.base@9-internal/Charset.java:474)
>    at java.nio.charset.Charset.forName(java.base@9-internal/Charset.java:538)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.findCharsetNameFor(java.xml@9-internal/Encodings.java:402)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.findCharsetNameFor(java.xml@9-internal/Encodings.java:438)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.loadEncodingInfo(java.xml@9-internal/Encodings.java:466)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.<init>(java.xml@9-internal/Encodings.java:324)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.<init>(java.xml@9-internal/Encodings.java:312)
>    at com.sun.org.apache.xml.internal.serializer.Encodings.<clinit>(java.xml@9-internal/Encodings.java:580)
>    at com.sun.org.apache.xml.internal.serializer.ToStream.<init>(java.xml@9-internal/ToStream.java:135)
>    at com.sun.org.apache.xml.internal.serializer.ToXMLStream.<init>(java.xml@9-internal/ToXMLStream.java:65)
>    at com.sun.org.apache.xalan.internal.xsltc.runtime.output.TransletOutputHandlerFactory.getSerializationHandler(java.xml@9-internal/TransletOutputHandlerFactory.java:163)
>    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutputHandler(java.xml@9-internal/TransformerImpl.java:472)
>    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(java.xml@9-internal/TransformerImpl.java:361)
>    at com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator.generateXML(PluginGenerator.java:756)
>    at com.ibm.ws.webcontainer.osgi.mbeans.GeneratePluginConfigMBean.generatePluginConfig(GeneratePluginConfigMBean.java:159)
>    at com.ibm.ws.webcontainer.osgi.mbeans.GeneratePluginConfigMBean.generatePluginConfig(GeneratePluginConfigMBean.java:261)
>    at com.ibm.ws.webserver.plugin.runtime.listeners.GeneratePluginConfigListener$1.run(GeneratePluginConfigListener.java:285)
>    at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9-internal/Executors.java:514)
>    at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:264)
>    at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1167)
>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:641)
>    at java.lang.Thread.run(java.base@9-internal/Thread.java:835)
>Caused by: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.cs.ext")
>    at java.security.AccessController.throwACE(java.base@9-internal/AccessController.java:176)
>    at java.security.AccessController.checkPermissionHelper(java.base@9-internal/AccessController.java:236)
>    at java.security.AccessController.checkPermission(java.base@9-internal/AccessController.java:371)
>    at java.lang.SecurityManager.checkPermission(java.base@9-internal/SecurityManager.java:558)
>    at java.lang.SecurityManager.checkPackageAccess(java.base@9-internal/SecurityManager.java:1534)
>    at java.lang.J9VMInternals$2.run(java.base@9-internal/J9VMInternals.java:311)
>    at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:664)
>    at java.lang.J9VMInternals.checkPackageAccess(java.base@9-internal/J9VMInternals.java:307)
>    at java.lang.ClassLoader.defineClassImpl(java.base@9-internal/Native Method)
>    at java.lang.ClassLoader.defineClass(java.base@9-internal/ClassLoader.java:445)
>    at java.lang.ClassLoader.defineClass(java.base@9-internal/ClassLoader.java:1985)
>    at java.security.SecureClassLoader.defineClass(java.base@9-internal/SecureClassLoader.java:206)
>    at jdk.internal.loader.BuiltinClassLoader.defineClass(java.base@9-internal/BuiltinClassLoader.java:1021)
>    at jdk.internal.loader.BuiltinClassLoader.lambda$findClassInModuleOrNull$4(java.base@9-internal/BuiltinClassLoader.java:865)
>    at jdk.internal.loader.BuiltinClassLoader$$Lambda$155.00000000B0AFBFA0.run(Unknown Source)
>    at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:638)
>    at jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(java.base@9-internal/BuiltinClassLoader.java:866)
>    at jdk.internal.loader.BuiltinClassLoader.findClass(java.base@9-internal/BuiltinClassLoader.java:733)
>    at java.lang.ClassLoader.loadClassHelper(java.base@9-internal/ClassLoader.java:1131)
>    at java.lang.Class.forName(java.base@9-internal/Class.java:442)
>    at java.util.ServiceLoader.lambda$loadProvider$1(java.base@9-internal/ServiceLoader.java:852)
>    at java.util.ServiceLoader$$Lambda$154.00000000B0AF9BC0.run(Unknown Source)
>    at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:694)
>    at java.util.ServiceLoader.loadProvider(java.base@9-internal/ServiceLoader.java:854)
>    at java.util.ServiceLoader.access$600(java.base@9-internal/ServiceLoader.java:390)
>    at java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(java.base@9-internal/ServiceLoader.java:1071)
>    at java.util.ServiceLoader$2.hasNext(java.base@9-internal/ServiceLoader.java:1294)
>    at java.util.ServiceLoader$3.hasNext(java.base@9-internal/ServiceLoader.java:1379)
>    at java.nio.charset.Charset$ExtendedProviderHolder$1.run(java.base@9-internal/Charset.java:442)
>    at java.nio.charset.Charset$ExtendedProviderHolder$1.run(java.base@9-internal/Charset.java:436)
>    at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:638)
>    at java.nio.charset.Charset$ExtendedProviderHolder.extendedProviders(java.base@9-internal/Charset.java:436)
>    at java.nio.charset.Charset$ExtendedProviderHolder.<clinit>(java.base@9-internal/Charset.java:433)
```

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Skip package access check for classes within same module

Not perform package access check when resolving classes, loading super/interface classes if current class is in same module as target classes.

closes #859 

Reviewers @pshipton @tajila 
FYI: @DanHeidinga 

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

File: runtime/vm/resolvesupport.cpp [hunk 1]
```diff
@@ -122,6 +123,27 @@ packageAccessIsLegal(J9VMThread *currentThread, J9Class *targetClass, j9object_t
...
+BOOLEAN
+requirePackageAccessCheck(J9VMThread *vmThread, J9ClassLoader *srcClassLoader, J9Module *srcModule, J9Class *targetClass)
+{
+	BOOLEAN checkFlag = TRUE;
+	if (J2SE_VERSION(vmThread->javaVM) >= J2SE_19) {
+		if (srcModule == targetClass->module) {
+			if (NULL != srcModule) {
+				/* same named module */
+				checkFlag = FALSE;
+			} else if (J9VMJAVALANGCLASSLOADER_UNNAMEDMODULE(vmThread, srcClassLoader->classLoaderObject)
```
Comment (tajila) [inline runtime/vm/resolvesupport.cpp]: doing `srcClassLoader == targetClass->classLoader` might be cheaper. If the classloaders are the same, they will have the same unnamedModule

Comment (JasonFengJ9) [reply runtime/vm/resolvesupport.cpp]: Agree and fixed.

File: runtime/vm/resolvesupport.cpp [hunk 2]
```diff
@@ -360,7 +380,10 @@ resolveClassRef(J9VMThread *vmStruct, J9ConstantPool *ramCP, UDATA cpIndex, UDAT
 	 * 		- the current class and resolved class are identical
 	 * 		- the current class was loaded by the bootstrap class loader
```
Comment (pshipton) [inline runtime/vm/resolvesupport.cpp]: The comment needs an update for the new condition

Comment (JasonFengJ9) [reply runtime/vm/resolvesupport.cpp]: The comment updated.
