### PR TITLE
Grow StringBuffer and StringBuilder aggressively from 1G to 2G

### LINKED ISSUE #7671: Integer overflow when increasing the capacity of very large StringBuffers
The OpenJ9 StringBuffer class behaves very differently to the OpenJDK StringBuffer class when appending small numbers of characters to very large StringBuffers (half of the maximum capacity of `Integer.MAX_VALUE`).

Consider this testcase, which appends characters to a StringBuffer one at a time, and prints out the capacity of the StringBuffer whenever it increases:

```
public class StringBufferTest {
	public static void main(String[] args) {
		StringBuffer b = new StringBuffer();
		int cap = b.capacity();
		while(true) {
			b.append("a");
			if (b.capacity() > cap) {
				cap = b.capacity();
				System.out.println("Capacity increased to " + cap);
			}
		}
	}
}
```

With OpenJDK's StringBuffer implementation the output goes like this:

```
C:\>java -Xmx8g StringBufferTest
Capacity increased to 34
Capacity increased to 70
Capacity increased to 142
Capacity increased to 286
Capacity increased to 574
Capacity increased to 1150
Capacity increased to 2302
Capacity increased to 4606
Capacity increased to 9214
Capacity increased to 18430
Capacity increased to 36862
Capacity increased to 73726
Capacity increased to 147454
Capacity increased to 294910
Capacity increased to 589822
Capacity increased to 1179646
Capacity increased to 2359294
Capacity increased to 4718590
Capacity increased to 9437182
Capacity increased to 18874366
Capacity increased to 37748734
Capacity increased to 75497470
Capacity increased to 150994942
Capacity increased to 301989886
Capacity increased to 603979774
Capacity increased to 1207959550
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuffer.append(StringBuffer.java:270)
        at StringBufferTest.main(StringBufferTest.java:8)
```

While OpenJ9 behaves like this:

```
C:\>java -Xmx8g StringBufferTest
Capacity increased to 34
Capacity increased to 70
Capacity increased to 142
Capacity increased to 286
Capacity increased to 574
Capacity increased to 1150
Capacity increased to 2302
Capacity increased to 4606
Capacity increased to 9214
Capacity increased to 18430
Capacity increased to 36862
Capacity increased to 73726
Capacity increased to 147454
Capacity increased to 294910
Capacity increased to 589822
Capacity increased to 1179646
Capacity increased to 2359294
Capacity increased to 4718590
Capacity increased to 9437182
Capacity increased to 18874366
Capacity increased to 37748734
Capacity increased to 75497470
Capacity increased to 150994942
Capacity increased to 301989886
Capacity increased to 603979774
Capacity increased to 1207959550
Capacity increased to 1207959551
Capacity increased to 1207959552
Capacity increased to 1207959553
Capacity increased to 1207959554
Capacity increased to 1207959555
Capacity increased to 1207959556
Capacity increased to 1207959557
Capacity increased to 1207959558
Capacity increased to 1207959559
Capacity increased to 1207959560
Capacity increased to 1207959561
Capacity increased to 1207959562
Capacity increased to 1207959563
Capacity increased to 1207959564
Capacity increased to 1207959565
Capacity increased to 1207959566
Capacity increased to 1207959567
Capacity increased to 1207959568
< and so on, and so on... >
```

On the plus side, this means that more characters can be appended to the StringBuffer on OpenJ9 before it throws an OOM. However, we have recently seen a situation where this behaviour prolonged the suffering of an application which was malfunctioning and appending too many characters to a StringBuffer - the repeated copying of the backing array to a slightly larger backing array can be extremely expensive in a large multi-threaded application.

Regardless of the pros and cons, it looks like the OpenJ9 behaviour is not intentional. It happens when `newcapacity` overflows on line 762:

```
758	 private void ensureCapacityImpl(int min) {
759		int currentLength = lengthInternalUnsynchronized();
760		int currentCapacity = capacityInternal();
761	
762		int newCapacity = (currentCapacity << 1) + 2;
763
764		int newLength = min > newCapacity ? min : newCapacity;
```
Which causes `newLength` to always be set to `min` on line 764. This means the backing array will grow only just enough to accommodate the character(s) being appended this time round, as seen in the testcase.

The OpenJDK code considers the potential overflow more carefully and prevents it, with the consequence that an OutOfMemoryError is thrown much earlier.

It may be that the OpenJ9 behaviour is preferable under some circumstances (maybe a command line flag is needed?). But in any case the behaviour should be intentional, not a consequence of a defect.

### PR DESCRIPTION
**Pull request by pshipton**
Affects jdk8 only. jdk11 and later already grow aggressively.
When `-Djava.lang.stringBufferAndBuilder.growAggressively` or
`-Djava.lang.stringBufferAndBuilder.growAggressively=true` is set on
the command line, and doubling the capacity overflows Integer.MAX_VALUE, 
grow StringBuffer and StringBuilder to Integer.MAX_VALUE instead of
only increasing the capacity by the size of the String being appended.
Compatible with Hotspot behavior.

Add testing for the same.

Fixes #7671

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

File: test/functional/cmdLineTests/cmdLineTest_J9tests/src/TestStringBufferAndBuilderGrowth.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+ *******************************************************************************/
+
+/**
+ * @file TestStringBufferAndBuilderGrowth.java
+ * @brief Grows a StringBuffer and StringBuilder to Integer.MAX_VALUE
+ */
+
+public class TestStringBufferAndBuilderGrowth {
+
+public static void main(String[] args) {
```
Comment (keithc-ca) [inline test/functional/cmdLineTests/cmdLineTest_J9tests/src/TestStringBufferAndBuilderGrowth.java]: nits: Inconsistent indenting (here and the closing `}`); missing space around `=` in `for` loops.

Comment (pshipton) [reply test/functional/cmdLineTests/cmdLineTest_J9tests/src/TestStringBufferAndBuilderGrowth.java]: Fixed

**Comment by pshipton** [comment]
> The test seems rather sensitive to implementation details.

Yes it is. I've added comments to the test for clarity.

**Comment by keithc-ca** [comment]
Previous PR testing passed; only changes since were formatting and comments: no addition PR testing required.

**Comment by gita-omr** [comment]
Seemsto be causing failure here: https://github.com/eclipse/openj9/pull/7622#issuecomment-580865585

**Comment by pshipton** [comment]
That PR test is failing because the associated code change isn't included, i.e. new test, old code.
