### PR TITLE
There in no need to call notifyClasspathChange3() when urlCount is 0

### LINKED ISSUE #6549: Memory corruption detected when loading a class in groovy and Xshareclasses is enabled.
Java -version output
--------------------

```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux amd64-64-Bit Compressed References 20190717_286 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

Summary of problem
------------------

Memory corruption when loading a class in groovy.

I am receiving this error:
```
04:55:50.700 0x22a3a00 omrport.359    *   ** ASSERTION FAILED ** at ../../omr/port/common/omrmemtag.c:145: ((memoryCorruptionDetected))
```

The error seems to be triggered when `loadClass` is called on the groovy class loader when running: (as root if that matters)
```
/usr/lib/jvm/default-java/bin/java -classpath path-to-shadded-jar.jar -Xshareclasses:name=jetty -Xshareclasses:cacheDir=/tmp/jvmcaches/ com.funnelback.jetty.launch.Launch
```
The code run is:
```
    public static void main(String[] args) throws Exception {
        
        System.out.println("Do with groovy");
        try (GroovyClassLoader groovyClassLoader = new GroovyClassLoader(Launch.class.getClassLoader())) {
            System.out.println("Doing with groovy");
            // a jar file containing a single hello world printing main.
            groovyClassLoader.addClasspath("/tmp/hello/Hello.jar");
            
            System.out.println("g4");
            Class<?> clazz = groovyClassLoader.loadClass("foo.Hello", false, true);
            System.out.println("g5");
        } catch (Exception e) {
            System.out.println("g8");
            throw new RuntimeException(e);
        }
        System.out.println("g9 end");
    }
```

The dependencies from maven are:
```
    <dependencies>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.5.6</version>
            <type>pom</type>
        </dependency>
    </dependencies>
```
Output is:
```
/usr/lib/jvm/default-java/bin/java -classpath /home/luke/code/trunk/funnelback/web/server/funnelback-jetty-launcher.jar -Xshareclasses:name=jetty -Xshareclasses:cacheDir=/tmp/jvmcaches/ com.funnelback.jetty.launch.Launch
Do with groovy
Doing with groovy
g4
05:18:58.617 0x1aaca00 omrport.359    *   ** ASSERTION FAILED ** at ../../omr/port/common/omrmemtag.c:145: ((memoryCorruptionDetected))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2019/07/23 15:18:58 - please wait.
JVMDUMP032I JVM requested System dump using '/usr/lib/jvm/core.20190723.151858.14762.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.14788.

JVMDUMP010I System dump written to /usr/lib/jvm/core.20190723.151858.14762.0001.dmp
JVMDUMP032I JVM requested Java dump using '/usr/lib/jvm/javacore.20190723.151858.14762.0002.txt' in response to an event
JVMDUMP010I Java dump written to /usr/lib/jvm/javacore.20190723.151858.14762.0002.txt
JVMDUMP032I JVM requested Snap dump using '/usr/lib/jvm/Snap.20190723.151858.14762.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /usr/lib/jvm/Snap.20190723.151858.14762.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".
```
Diagnostic files
----------------
[javacore.20190723.151858.14762.0002.txt](https://github.com/eclipse/openj9/files/3420335/javacore.20190723.151858.14762.0002.txt)

[Snap.20190723.151858.14762.0003.trc.zip](https://github.com/eclipse/openj9/files/3420336/Snap.20190723.151858.14762.0003.trc.zip)

core dump:
https://drive.google.com/file/d/138FKS_NNKBQjALJtnu97MRXIgAzut3OV/view?usp=sharing

### PR DESCRIPTION
**Pull request by hangshao0**
When a URLClassLoader is initialized with an empty url array, it calls
into notifyClasspathChange3() through
SharedClassURLClasspathHelperImpl(). There is no need to allocate memory
and create class path entries for the empty array. Return directly in
this case.

Fixes #6549

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
Manually tested on Groovy, the memory corruption goes away.

File: runtime/jcl/common/shared.c [hunk 1]
```diff
@@ -239,7 +239,8 @@ createCPEntries(JNIEnv* env, jint helperID, jint urlCount, J9ClassPathEntry** cp
 	PORT_ACCESS_FROM_VMC((J9VMThread*)env);
 
 	Trc_JCL_com_ibm_oti_shared_createCPEntries_Entry(env, helperID, urlCount);
-	
+	Assert_JCL_true(urlCount > 0);
```
Comment (DanHeidinga) [inline runtime/jcl/common/shared.c]: What about other callers of this method like https://github.com/eclipse/openj9/blob/2601bd3308305958029c9678bf6493e307163563/runtime/jcl/common/shared.c#L1527-L1530 ?

Should they be updated to prevent passing 0 through as well?

Comment (hangshao0) [reply runtime/jcl/common/shared.c]: We should not reach here when urlCount is 0. The other 2 callers are guarded by these two checks on the JCL side:

https://github.com/eclipse/openj9/blob/master/jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassURLClasspathHelperImpl.java#L167

https://github.com/eclipse/openj9/blob/master/jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassURLClasspathHelperImpl.java#L121
(confirmedCount is the number of confirmed URL entries in the URL classpath, so confirmedCount should always be <=urlCount)

**Comment by DanHeidinga** [comment]
I'll launch builds on this when we get the all clear on jenkins being back

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8

**Comment by pshipton** [comment]
jenkins compile win jdk8

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/905/ - https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_ppc64le_linux/616/
https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/906/ - https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_x86-64_windows/585/
