### PR TITLE
Fix searching with a method signature

### LINKED ISSUE #10080: methodforname in jdmpview doesn't find methods
Working on https://github.com/eclipse/openj9/issues/9710 I know a method exists:
```
> !j9method 0x0000000000E259F0
J9Method at 0xe259f0 {
  Fields for J9Method:
        0x0: U8* bytecodes = !j9x 0x00007F525948B16C
        0x8: struct J9ConstantPool* constantPool = !j9constantpool 0x0000000000E24AA0 (flags = 0x0)
        0x10: void* methodRunAddress = !j9x 0x0000000000000006
        0x18: void* extra = !j9x 0x0000000000001753
}
Signature: scala/collection/immutable/Queue.enqueue(Ljava/lang/Object;)Lscala/collection/immutable/Queue; !bytecodes 0x0000000000E259F0
ROM Method: !j9rommethod 0x00007F525948B158
Next Method: !j9method 0x0000000000E25A10
```
However, searching for it with certain wildcards doesn't work:
```
> !methodforname *.enqueue(Ljava/lang/Object;)*
Searching for methods named '*.enqueue(Ljava/lang/Object;)*' in VM=0x00007F52B4016A50...
Found 0 method(s) named *.enqueue(Ljava/lang/Object;)*
```
I can find methods if I do this search:
```
> !methodforname scala/collection/immutable/Queue.enqueue*
Searching for methods named 'scala/collection/immutable/Queue.enqueue*' in VM=0x00007F52B4016A50...
!j9method 0x0000000000E259F0 --> scala/collection/immutable/Queue.enqueue(Ljava/lang/Object;)Lscala/collection/immutable/Queue;
!j9method 0x0000000000E25A10 --> scala/collection/immutable/Queue.enqueue(Lscala/collection/immutable/Iterable;)Lscala/collection/immutable/Queue;
Found 2 method(s) named scala/collection/immutable/Queue.enqueue*
```
However, this doesn't help if I want to know if there are other overrides of this method.

### PR DESCRIPTION
**Pull request by keithc-ca**
When decomposing a method search pattern, the 'name' portion should not include the 'signature' portion, if any.

Fixes #10080.

### CODE REVIEW

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/MethodForNameCommand.java [hunk 1]
```diff
@@ -68,85 +68,74 @@ public void run(String command, String[] args, Context context, PrintStream out)
...
-		if (pattern.indexOf('(') != -1) {
-			sigStart = pattern.substring(pattern.indexOf('('));
-		} else {
-			sigStart = "*";
-		}
-
-		StringBuffer needleBuffer = new StringBuffer();
-		classMatchFlags = WildCard.parseWildcard(classStart, needleBuffer);
-		classNeedle = needleBuffer.toString();
+		needleBuffer = new StringBuffer();
```
Comment (pshipton) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/MethodForNameCommand.java:78]: Just curious why you split the declaration and the initialization.

**Comment by pshipton** [comment]
jenkins test sanity,extended zlinux jdk8

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/MethodForNameCommand.java (hunk 1 above)
Comment (keithc-ca) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/MethodForNameCommand.java:78]: `needleBuffer` is reused several times: in my opinion, it's misleading to put the first assignment into the declaration.
