### PR TITLE
AArch64: Return 64 as L1 data cache line size when info unavailable

### LINKED ISSUE #8969: AArch64: Failure in ContendedFieldsTests_90_1
Failure link
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_aarch64_linux_Personal/7/

Some tests in ContendedFieldsTests_90_1 fail as shown below.
```
[2020-03-23T02:16:31.422Z] FAILED: testContentionGroupsAndClass
[2020-03-23T02:16:31.422Z] java.lang.AssertionError: org.openj9.test.contendedfields.TestClasses$ContGroupContClass calculated size 64 actual size 24 difference -40
[2020-03-23T02:16:31.422Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2020-03-23T02:16:31.422Z] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
[2020-03-23T02:16:31.422Z] 	at org.openj9.test.contendedfields.FieldUtilities.checkObjectSize(FieldUtilities.java:67)
```

### PR DESCRIPTION
**Pull request by knn-k**
sysconf(_SC_LEVEL1_DCACHE_LINESIZE) returns 0 on some systems.
This commit changes j9sysinfo_get_cache_info() to return 64 as the
L1 data cache line size for AArch64 on such systems.

Fixes #8969

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
jenkins test extended.functional alinux64 jdk11

File: runtime/port/unix/j9sysinfo.c [hunk 1]
```diff
@@ -1675,8 +1675,11 @@ j9sysinfo_get_cache_info(struct J9PortLibrary *portLibrary, const J9CacheInfoQue
 	) {
 		/* L1 data cache line size */
 		int32_t rc = (int32_t)sysconf(_SC_LEVEL1_DCACHE_LINESIZE);
-		if (rc >= 0) {
+		if (rc > 0) {
 			result = rc;
+		} else if (rc == 0) {
+			// Cache line size in unavailable on some systems
```
Comment (DanHeidinga) [inline runtime/port/unix/j9sysinfo.c:1681]: Nitpick - we typically avoid `//` comments in VM code as not all supported compilers accept them and its easier to blanket ban them then ensure they are only present where in platform-specific code

```suggestion
			/* Cache line size in unavailable on some systems */
```

File: runtime/port/unix/j9sysinfo.c [hunk 2]
```diff
@@ -1675,8 +1675,11 @@ j9sysinfo_get_cache_info(struct J9PortLibrary *portLibrary, const J9CacheInfoQue
...
+			result = 64;
```
Comment (DanHeidinga) [inline runtime/port/unix/j9sysinfo.c:1682]: I had suggested 64 in the issue where this was discussed but have no experience on aarch64 to tell if that's actually reasonable.  Does 64 make sense given the chips that are available?  Would another value be a safer default?

Comment (pshipton) [reply runtime/port/unix/j9sysinfo.c:1682]: As I understand it, it's better if the number is too big than too small. If it's too big then a little memory will be wasted, but if it's too small then it will defeat the purpose of the optimization and affect performance.

Comment (knn-k) [reply runtime/port/unix/j9sysinfo.c:1682]: The line size of L1 data cache of Cortex-A53 (low-end AArch64 core) is 64 bytes, as stated in http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0500j/BABCFDAH.html.
Other Cortex-A3x, A5x and A7x chips also seem to have 64 byte cache line in L1 data cache.

File: runtime/port/unix/j9sysinfo.c (hunk 1 above)
Comment (knn-k) [reply runtime/port/unix/j9sysinfo.c]: Updated the code as suggested.

File: runtime/port/unix/j9sysinfo.c (hunk 2 above)
Comment (knn-k) [reply runtime/port/unix/j9sysinfo.c:1682]: I don't think there is a good reason to choose other line size.  Cortex AArch64 cores seem to have the 64 byte cache lins.

File: runtime/port/unix/j9sysinfo.c [hunk 3]
```diff
@@ -1675,8 +1675,11 @@ j9sysinfo_get_cache_info(struct J9PortLibrary *portLibrary, const J9CacheInfoQue
 	) {
 		/* L1 data cache line size */
 		int32_t rc = (int32_t)sysconf(_SC_LEVEL1_DCACHE_LINESIZE);
-		if (rc >= 0) {
+		if (rc > 0) {
 			result = rc;
+		} else if (rc == 0) {
+			/* Cache line size in unavailable on some systems */
```
Comment (pshipton) [inline runtime/port/unix/j9sysinfo.c:1681]: Typo `in` should be `is`

File: runtime/port/unix/j9sysinfo.c (hunk 2 above)
Comment (pshipton) [reply runtime/port/unix/j9sysinfo.c:1682]: Pls add the information https://github.com/eclipse/openj9/pull/9155/files#r404837464 as a comment in the code for future reference.

Comment (knn-k) [reply runtime/port/unix/j9sysinfo.c:1686]: Updated the comment.

**Comment by DanHeidinga** [comment]
jenkins test extended.functional alinux64 jdk11

**Comment by knn-k** [comment]
The jenkins build above is taking so long.

**Comment by knn-k** [comment]
The test machine was rebooted.  Running the jenkins job again.

**Comment by knn-k** [comment]
jenkins test extended.functional alinux64 jdk11

**Comment by pshipton** [comment]
The existing PR build https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK11_aarch64_linux/72/ ran the extended tests, with the only failure being testSoftMxUserScenario_2. I don't think we need any more testing here.
