### PR TITLE
Uncommon autosimd piv loop stride increment node

### LINKED ISSUE #10656: JDK15 s390x autoSIMD : PIV commoning with address calculation can generate wrong IL
While performing autoSIMD to loops, the commoning of PIV with the address calculation of the array can cause the address calculation to be wrong. Thus yielding wrong IL.

See:  https://github.com/eclipse/openj9/issues/9331#issuecomment-682105215 for more details

### PR DESCRIPTION
**Pull request by mnalam-p**
If the loop increment node is commoned, then reducing the loop by
changing the value of loop stride can cause unwanted bug. This is
potentially true if the node is commoned for address calculation.
This commit uncommon the PIV increment node so that changing the
stride does not introduce side-effects on commoned nodes.

Fixes #10656

Signed-off-by: Mohammad Nazmul Alam <mohammad.nazmul.alam@ibm.com>

### CODE REVIEW

File: runtime/compiler/optimizer/SPMDParallelizer.cpp [hunk 1]
```diff
@@ -1441,6 +1441,30 @@ bool TR_SPMDKernelParallelizer::processSPMDKernelLoopForSIMDize(TR::Compilation
             {
             // increment of PIV
             traceMsg(comp, "Reducing the number of iterations of the loop %d at storeNode [%p] by vector length %d \n",loop->getNumber(), storeNode, unrollCount);
+	    TR_ASSERT_FATAL(storeNode->getFirstChild()->getOpCode().isAdd() || storeNode->getFirstChild()->getOpCode().isSub(), "PIV increment should be simple (either by add or by sub");
+	    TR_ASSERT_FATAL(storeNode->getFirstChild()->getFirstChild()->getOpCode().isLoad(), "PIV increment should have load");
+	    TR_ASSERT_FATAL(!storeNode->getFirstChild()->getSecondChild()->getSymbolReference(), "PIV increment should have const increment value");
```
Comment (IBMJimmyk) [inline runtime/compiler/optimizer/SPMDParallelizer.cpp:1446]: I think this assert was supposed to check if the child is a const.

File: runtime/compiler/optimizer/SPMDParallelizer.cpp [hunk 2]
```diff
@@ -1441,6 +1441,30 @@ bool TR_SPMDKernelParallelizer::processSPMDKernelLoopForSIMDize(TR::Compilation
             {
             // increment of PIV
             traceMsg(comp, "Reducing the number of iterations of the loop %d at storeNode [%p] by vector length %d \n",loop->getNumber(), storeNode, unrollCount);
+	    TR_ASSERT_FATAL(storeNode->getFirstChild()->getOpCode().isAdd() || storeNode->getFirstChild()->getOpCode().isSub(), "PIV increment should be simple (either by add or by sub");
+	    TR_ASSERT_FATAL(storeNode->getFirstChild()->getFirstChild()->getOpCode().isLoad(), "PIV increment should have load");
+	    TR_ASSERT_FATAL(storeNode->getFirstChild()->getSecondChild()->getOpCode().isLoadConst(), "PIV increment should have const increment value");
+            if (storeNode->getFirstChild()->getReferenceCount() > 1)
```
Comment (andrewcraik) [inline runtime/compiler/optimizer/SPMDParallelizer.cpp:1447]: Maybe I'm missing something, but if the increment is commoned with other uses why does uncommoning just the definition let the vectorization do the right thing but the commoned version does not?

File: runtime/compiler/optimizer/SPMDParallelizer.cpp (hunk 1 above)
Comment (mnalam-p) [reply runtime/compiler/optimizer/SPMDParallelizer.cpp]: Code Updated

File: runtime/compiler/optimizer/SPMDParallelizer.cpp (hunk 2 above)
Comment (mnalam-p) [reply runtime/compiler/optimizer/SPMDParallelizer.cpp:1447]: Lets says we want to vectorize the following
`A[i] = B[i+1] * 2`
Now when we do that, the i + 1 calculation in the address is used for incrementing i. Hence, they become common. Now, if we don't uncommon the i+1 node, then later on loop reduction will change the 1 to 4 (for example). Hence making i = i + 4. Now, as i + 1 was previously commoned, this change will make the code like below -
`A[i] = B[i+4] * 2`

Comment (mnalam-p) [reply runtime/compiler/optimizer/SPMDParallelizer.cpp:1447]: Also, I believe this fix should be able to fix a previous bug #9446

Comment (fjeremic) [reply runtime/compiler/optimizer/SPMDParallelizer.cpp:1508]: Also mixed tabs/spaces in this commit should be fixed up.

**Review by fjeremic — CHANGES_REQUESTED** [review]
We should try to keep the commit titles consistent with the rest of the contributions.

> The first line should be less than 70 characters, where reasonable, and should be written in sentence case **preferably not ending in a period.**

[1] https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md#commit-guidelines

File: runtime/compiler/optimizer/SPMDParallelizer.cpp [hunk 3]
```diff
@@ -1369,6 +1369,30 @@ bool TR_SPMDKernelParallelizer::reductionLoopExitProcessing(TR::Compilation *com
    return true;
    }
 
+TR::Node * replaceAndAnchorOldNode(TR::Compilation *comp, TR::TreeTop *treeTop, TR::Node *parent, TR::Node *oldNode, TR::Node *newNode, int index)
+   {
+	   treeTop->insertBefore(TR::TreeTop::create(comp, TR::Node::create(TR::treetop, 1, oldNode)));
+	   oldNode->recursivelyDecReferenceCount();
+	   parent->setAndIncChild(index, newNode);
+	   return newNode;
```
Comment (gita-omr) [inline runtime/compiler/optimizer/SPMDParallelizer.cpp:1377]: Let's not return the value passed as a parameter. Better to make that function void.

File: runtime/compiler/optimizer/SPMDParallelizer.cpp [hunk 4]
```diff
@@ -1369,6 +1369,30 @@ bool TR_SPMDKernelParallelizer::reductionLoopExitProcessing(TR::Compilation *com
...
+   }
+
+bool matchIVIncrementPattern(TR::Node *node, TR::SymbolReference *pivSymRef)
+   {
+   return (node->getOpCode().isAdd() || node->getOpCode().isSub()) && node->getFirstChild()->getOpCode().isLoad()
+    && node->getFirstChild()->getSymbolReference() == pivSymRef && node->getSecondChild()->getOpCode().isLoadConst();
+   }
+
+TR::Node * changeIAddISubConstNodeMultiplyBy(TR::Node * parent, int32_t multiple)
```
Comment (gita-omr) [inline runtime/compiler/optimizer/SPMDParallelizer.cpp:1386]: I would rather call it: changeLoopStride.

File: runtime/compiler/optimizer/SPMDParallelizer.cpp [hunk 5]
```diff
@@ -1427,26 +1451,110 @@ bool TR_SPMDKernelParallelizer::processSPMDKernelLoopForSIMDize(TR::Compilation
    loop->getBlocks(&blocksInLoop);
    ListIterator<TR::Block> blocksIt1(&blocksInLoop);
 
-
    // SIMD_TODO: improve this code
 
    for (TR::Block *nextBlock = blocksIt1.getCurrent(); nextBlock; nextBlock=blocksIt1.getNext())
       {
+      TR_HashTab* entries = new (comp->trStackMemory()) TR_HashTab(comp->trMemory(), stackAlloc);
```
Comment (gita-omr) [inline runtime/compiler/optimizer/SPMDParallelizer.cpp:1458]: Please fix all the formatting.

**Review by gita-omr — COMMENTED** [review]
I think the algorithm is correct. But I would like to review once more after cosmetic changes are done.

File: runtime/compiler/optimizer/SPMDParallelizer.cpp (hunk 5 above)
Comment (gita-omr) [inline runtime/compiler/optimizer/SPMDParallelizer.cpp:1458]: I don't think we should create a hash table for each block. I think we need only one that is cleared on every block.

File: runtime/compiler/optimizer/SPMDParallelizer.cpp [hunk 6]
```diff
@@ -1427,26 +1451,110 @@ bool TR_SPMDKernelParallelizer::processSPMDKernelLoopForSIMDize(TR::Compilation
...
       for (TR::TreeTop *tt = nextBlock->getEntry() ; tt != nextBlock->getExit() ; tt = tt->getNextTreeTop())
          {
          // identify operation for primary induction variable
          TR::Node *storeNode = tt->getNode();
```
Comment (gita-omr) [inline runtime/compiler/optimizer/SPMDParallelizer.cpp:1462]: Since the node is not necessary a store maybe should be named something else.

File: runtime/compiler/optimizer/SPMDParallelizer.cpp (hunk 5 above)
Comment (gita-omr) [reply runtime/compiler/optimizer/SPMDParallelizer.cpp:1458]: Looks like the code assumes there are no extended blocks at this point. So perhaps having a hash table is not really necessary since there will be only one compare and branch and it will always follow an inductions variable increment.  But let's keep the hash table in case we want to handle more general case in the future.

File: runtime/compiler/optimizer/SPMDParallelizer.cpp (hunk 4 above)
Comment (gita-omr) [reply runtime/compiler/optimizer/SPMDParallelizer.cpp:1386]: or even better: multiplyLoopStride

File: runtime/compiler/optimizer/SPMDParallelizer.cpp (hunk 2 above)
Comment (mnalam-p) [reply runtime/compiler/optimizer/SPMDParallelizer.cpp:1508]: The tabs/spaces are fixed, it was introduced due to vim not having proper tab extend setup

**Comment by gita-omr** [comment]
Looks very good to me, but @IBMJimmyk please take another look when you have a chance.

**Review by fjeremic — APPROVED** [review]

File: runtime/compiler/optimizer/SPMDParallelizer.cpp [hunk 7]
```diff
@@ -1369,6 +1369,29 @@ bool TR_SPMDKernelParallelizer::reductionLoopExitProcessing(TR::Compilation *com
    return true;
    }
 
+void TR_SPMDKernelParallelizer::replaceAndAnchorOldNode(TR::Compilation *comp, TR::TreeTop *treeTop, TR::Node *parent, TR::Node *oldNode, TR::Node *newNode, int index)
+   {
+	   treeTop->insertBefore(TR::TreeTop::create(comp, TR::Node::create(TR::treetop, 1, oldNode)));
+	   oldNode->recursivelyDecReferenceCount();
+	   parent->setAndIncChild(index, newNode);
```
Comment (IBMJimmyk) [inline runtime/compiler/optimizer/SPMDParallelizer.cpp:1376]: There are still some tabs here that should be replaced with spaces.

**Comment by IBMJimmyk** [comment]
Other than minor whitespace issues, everything looks good to me.

File: runtime/compiler/optimizer/SPMDParallelizer.cpp (hunk 7 above)
Comment (mnalam-p) [reply runtime/compiler/optimizer/SPMDParallelizer.cpp]: Fixed

**Comment by gita-omr** [comment]
@mnalam-p please remove the "// SIMD_TODO: improve this code" code since it's unclear what needs to be improved. Then we can merge.

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by gita-omr** [comment]
Investigating why Travis CI build is stuck...

**Comment by gita-omr** [comment]
@pshipton we would like this fix to be in 0.24.

**Comment by pshipton** [comment]
If it's merged today or tomorrow then it will be in 0.24. Next week it will have to be double delivered.

You can ignore the travis build, it compiles xlinux jdk11 using cmake, which you have already done in PR testing.
