### PR TITLE
Fix javacore native mem info output

### LINKED ISSUE #8984: jdk11+ Modules native memory accounting incorrect on AIX
Looking at native memory info for a jdk11 AIX run (`java -Xdump:java`), there are some problems with the Modules data. The problems don't occur on xlinux.
1) The amount is 2,472,459,672 bytes which doesn't make sense, considering there is a 2G heap and the VM parent only totals 2,478,799,464 bytes.
2) Modules shouldn't have any children, but it's got an "Other" child. I suspect the Other value is the actual Modules data, it matches what xlinux shows.

```
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
0MEMUSER
1MEMUSER       JRE: 2,787,696,240 bytes / 5451 allocations
1MEMUSER       |
2MEMUSER       +--VM: 2,478,799,464 bytes / 4970 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 5,094,272 bytes / 159 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Modules: 2,472,459,672 bytes / 3401 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 511,120 bytes / 2053 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 2,190,767,184 bytes / 726 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 2,147,483,648 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 43,283,536 bytes / 725 allocations
2MEMUSER       |  |
```

### PR DESCRIPTION
**Pull request by pshipton**
Compute the bit mask indexes properly, which are used to track memory
category ancestors. Memory category codes don't need to be consecutive.

Fixes #8984

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile zlinux,win jdk8

**Comment by pshipton** [comment]
jenkins compile zlinux,win jdk8

**Comment by pshipton** [comment]
My changes seem to have made it worse, need to figure out what went wrong.

**Comment by pshipton** [comment]
jenkins compile zlinux jdk8,jdk11

**Comment by pshipton** [comment]
Seems to be working now.

**Comment by pshipton** [comment]
jdk8
```
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
0MEMUSER
1MEMUSER       JRE: 1,542,653,544 bytes / 1866 allocations
1MEMUSER       |
2MEMUSER       +--VM: 1,253,118,880 bytes / 1476 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 4,291,664 bytes / 136 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 1,029,203,448 bytes / 373 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 1,008,791,552 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 20,411,896 bytes / 372 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Threads: 10,046,904 bytes / 131 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Stack: 80,808 bytes / 13 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Native Stack: 9,830,400 bytes / 14 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 135,696 bytes / 104 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Trace: 153,208 bytes / 254 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JVMTI: 17,776 bytes / 13 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JNI: 33,360 bytes / 51 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Port Library: 208,373,520 bytes / 69 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Unused <32bit allocation regions: 208,363,360 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 10,160 bytes / 68 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 999,000 bytes / 449 allocations
1MEMUSER       |
2MEMUSER       +--JIT: 288,507,168 bytes / 134 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 268,435,456 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 2,097,216 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--Other: 17,974,496 bytes / 132 allocations
1MEMUSER       |
2MEMUSER       +--Class Libraries: 1,027,496 bytes / 256 allocations
2MEMUSER       |  |
3MEMUSER       |  +--VM Class Libraries: 1,027,496 bytes / 256 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--sun.misc.Unsafe: 2,656 bytes / 7 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Direct Byte Buffers: 528 bytes / 6 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Other: 2,128 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 1,024,840 bytes / 249 allocations
```

jdk11
```
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
0MEMUSER
1MEMUSER       JRE: 1,544,192,648 bytes / 4604 allocations
1MEMUSER       |
2MEMUSER       +--VM: 1,254,617,448 bytes / 4407 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 5,096,952 bytes / 160 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Modules: 511,528 bytes / 2055 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 1,029,261,304 bytes / 391 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 1,008,791,552 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 20,469,752 bytes / 390 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Threads: 10,326,080 bytes / 139 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Stack: 87,024 bytes / 14 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Native Stack: 10,092,544 bytes / 15 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 146,512 bytes / 110 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Trace: 161,560 bytes / 257 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JVMTI: 17,776 bytes / 13 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JNI: 37,432 bytes / 52 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Port Library: 208,124,736 bytes / 69 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Unused <32bit allocation regions: 208,114,664 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 10,072 bytes / 68 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 1,080,080 bytes / 1271 allocations
1MEMUSER       |
2MEMUSER       +--JIT: 289,564,912 bytes / 185 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 268,435,456 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 2,097,216 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--Other: 19,032,240 bytes / 183 allocations
1MEMUSER       |
2MEMUSER       +--Class Libraries: 10,288 bytes / 12 allocations
2MEMUSER       |  |
3MEMUSER       |  +--VM Class Libraries: 10,288 bytes / 12 allocations
```

File: runtime/rasdump/javadump.cpp [hunk 1]
```diff
@@ -1587,8 +1606,9 @@ outerMemCategoryCallBack (U_32 categoryCode, const char * categoryName, UDATA li
 	 * for all children of this node.
 	 */
 	memset(&total, 0, sizeof(memcategory_total));
-	total.category_bitmask = (U_32*)alloca(writer->_TotalCategories * sizeof(U_32));
-	memset(total.category_bitmask, 0, writer->_TotalCategories * sizeof(U_32));
+	U_32 bitmask_size = (((writer->_MaxCategoryBits - 1) / 32) + 1) * sizeof(U_32);
```
Comment (keithc-ca) [inline runtime/rasdump/javadump.cpp]: This would be safer written like this (so no one has to wonder whether `_MaxCategoryBits` can be zero):
```
U_32 bitmask_size = ((writer->_MaxCategoryBits + 31) / 32) * sizeof(U_32);
```

File: runtime/rasdump/javadump.cpp [hunk 2]
```diff
@@ -1498,7 +1505,19 @@ JavaCoreDumpWriter::writeMemorySection(void)
...
 countMemoryCategoriesCallback (U_32 categoryCode, const char * categoryName, UDATA liveBytes, UDATA liveAllocations, BOOLEAN isRoot, U_32 parentCategoryCode, OMRMemCategoryWalkState * state)
 {
-	(*(I_32 *)state->userData1)++;
+	(*(U_32 *)state->userData1)++;
+	
+	memcategory_max_indexes *max_indexes = (memcategory_max_indexes *)state->userData2;
+	if (categoryCode > OMRMEM_LANGUAGE_CATEGORY_LIMIT) {
+		U_32 omrCode = OMRMEM_OMR_CATEGORY_INDEX_FROM_CODE(categoryCode);
+		if (omrCode > max_indexes->omrMaxIndex) {
+			max_indexes->omrMaxIndex = omrCode;
```
Comment (keithc-ca) [inline runtime/rasdump/javadump.cpp]: I this this is easier to read if the comparison is reversed (same for `languageMaxIndex` below):
```
    if (max_indexes->omrMaxIndex < omrCode) {
        max_indexes->omrMaxIndex = omrCode;
    }
```

File: runtime/rasdump/javadump.cpp (hunk 1 above)
Comment (pshipton) [reply runtime/rasdump/javadump.cpp]: updated

File: runtime/rasdump/javadump.cpp (hunk 2 above)
Comment (pshipton) [reply runtime/rasdump/javadump.cpp]: updated
