### PR TITLE
Exempt com/sun/proxy classes from validation

### LINKED ISSUE #5950: java_lang_invoke_MethodHandlesProxiesTest failure on jdk8u
Failure link

https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-64_linux/547/testReport/

    test category: openjdk
    test suite name: jdk_lang
    OS/architecture: fails on all platforms

java -version
05:42:04  openjdk version "1.8.0_222"
05:42:04  OpenJDK Runtime Environment (build 1.8.0_222-201905290400-b04)
05:42:04  Eclipse OpenJ9 VM (build master-501661ce5, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190529_322 (JIT enabled, AOT enabled)
05:42:04  OpenJ9   - 501661ce5
05:42:04  OMR      - b2ffe8a9
05:42:04  JCL      - fc2cdb9145 based on jdk8u222-b04)
11:23:42 JCL - bb38f8aaac based on jdk-12+32)

Optional info

    intermittent failure: no
    regression: yes, started failing around May 22nd, according to test results 'Age'

Failure output

05:49:52  [TestNG] Running:
05:49:52    java/lang/invoke/MethodHandlesProxiesTest.java
05:49:52  
05:49:52  test test.java.lang.invoke.MethodHandlesProxiesTest.testDefaultMethods(): failure
05:49:52  java.lang.InternalError: java.lang.IllegalAccessException: test/java/lang/invoke/MethodHandlesProxiesTest$A is not a direct superinterface of com/sun/proxy/$Proxy2.
05:49:52  	at java.lang.invoke.MethodHandleProxies.lambda$callDefaultMethod$0(MethodHandleProxies.java:367)
05:49:52  	at java.lang.invoke.MethodHandleProxies$$Lambda$2.000000001C17D990.apply(Unknown Source)
05:49:52  	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
05:49:52  	at java.lang.invoke.MethodHandleProxies.callDefaultMethod(MethodHandleProxies.java:354)
05:49:52  	at java.lang.invoke.MethodHandleProxies.access$300(MethodHandleProxies.java:44)
05:49:52  	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:200)
05:49:52  	at com.sun.proxy.$Proxy2.a(Unknown Source)
05:49:52  	at test.java.lang.invoke.MethodHandlesProxiesTest.testDefaultMethods(MethodHandlesProxiesTest.java:87)
05:49:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:49:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:49:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:49:52  	at java.lang.reflect.Method.invoke(Method.java:498)
05:49:52  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
05:49:52  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
05:49:52  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
05:49:52  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
05:49:52  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
05:49:52  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
05:49:52  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
05:49:52  	at org.testng.TestRunner.run(TestRunner.java:623)
05:49:52  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
05:49:52  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
05:49:52  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
05:49:52  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
05:49:52  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
05:49:52  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
05:49:52  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
05:49:52  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
05:49:52  	at org.testng.TestNG.run(TestNG.java:1018)
05:49:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
05:49:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
05:49:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:49:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:49:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:49:52  	at java.lang.reflect.Method.invoke(Method.java:498)
05:49:52  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
05:49:52  	at java.lang.Thread.run(Thread.java:819)
05:49:52  Caused by: java.lang.IllegalAccessException: test/java/lang/invoke/MethodHandlesProxiesTest$A is not a direct superinterface of com/sun/proxy/$Proxy2.
05:49:52  	at java.lang.invoke.PrimitiveHandle.finishMethodInitialization(PrimitiveHandle.java:196)
05:49:52  	at java.lang.invoke.DirectHandle.<init>(DirectHandle.java:51)
05:49:52  	at java.lang.invoke.DirectHandle.<init>(DirectHandle.java:43)
05:49:52  	at java.lang.invoke.MethodHandles$Lookup.findSpecialImpl(MethodHandles.java:512)
05:49:52  	at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:480)
05:49:52  	at java.lang.invoke.MethodHandleProxies.lambda$callDefaultMethod$0(MethodHandleProxies.java:358)
05:49:52  	... 36 more
05:49:52  test test.java.lang.invoke.MethodHandlesProxiesTest.testOverriddenDefaultMethods(): success
05:49:52  
05:49:52  ===============================================
05:49:52  java/lang/invoke/MethodHandlesProxiesTest.java
05:49:52  Total tests run: 2, Failures: 1, Skips: 0
05:49:52  ===============================================
05:49:52  
05:49:52  STDERR:
05:49:52  java.lang.Exception: failures: 1
05:49:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
05:49:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
05:49:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:49:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:49:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:49:52  	at java.lang.reflect.Method.invoke(Method.java:498)
05:49:52  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
05:49:52  	at java.lang.Thread.run(Thread.java:819)
05:49:52  
05:49:52  JavaTest Message: Test threw exception: java.lang.Exception: failures: 1
05:49:52  JavaTest Message: shutting down test

### PR DESCRIPTION
**Pull request by mikezhang1234567890**
When we create a proxy of an interface with MethodHandleProxies and invoke a default method from the proxied interface's superinterfaces, an access check in the VM fails in JDK8 because the proxy itself does not have the superinterface listed as one of its own direct superinterfaces. In JDK11 and later, the generated proxy classes have a flag set that exempts them from validation. This PR does the same to the proxy classes generated in JDK8.

Signed-off-by: Mike Zhang <mike.h.zhang@ibm.com>

Fixes #5950

### CODE REVIEW

File: runtime/vm/createramclass.cpp [hunk 1]
```diff
@@ -3108,6 +3108,13 @@ internalCreateRAMClassFromROMClass(J9VMThread *vmThread, J9ClassLoader *classLoa
 			if (J9UTF8_LITERAL_EQUALS(J9UTF8_DATA(className), J9UTF8_LENGTH(className), MAGIC_ACCESSOR_IMPL)) {
 				classFlags |= J9ClassIsExemptFromValidation;
 			}
+
+#if JAVA_SPEC_VERSION == 8
+			if (J9UTF8_LITERAL_EQUALS(J9UTF8_DATA(className), 20, "com/sun/proxy/$Proxy")) {
```
Comment (DanHeidinga) [inline runtime/vm/createramclass.cpp]: The hardcoded `20` doesn't seem right.  Looking at the definition of the macro it should be the `J9UTF8_LENGTH(className)`:

https://github.com/eclipse/openj9/blob/097492a09bfc0767aeea69141794c39063e080db/runtime/oti/j9.h#L174

If the intention is to check a substring, it would be clearer to use `strncmp` after validating the length and adding a comment to indicate why strncmp is correct

**Comment by mikezhang1234567890** [comment]
> How are these proxy classes loaded? sun.misc.Unsafe.defineClass should already exempt them from the access check...

The proxy class in JDK 8 is generated by `java/lang/reflect/Proxy.defineClass0` rather than `Unsafe.defineClass`. Main difference seems to be the fact that in the `Proxy.defineClass0` native, https://github.com/eclipse/openj9/blob/9b2299f2be56526a89c7e96ed3d7ae435936b783/runtime/jcl/common/proxy.c#L68
0 is passed as option flag whereas in `Unsafe.defineClass`, the `J9_FINDCLASS_FLAG_UNSAFE` flag is passed. https://github.com/eclipse/openj9/blob/9b2299f2be56526a89c7e96ed3d7ae435936b783/runtime/jcl/common/sun_misc_Unsafe.cpp#L62

**Comment by DanHeidinga** [comment]
There also seems to be a path that goes through defineClassCommon instead of Proxy.defineClass:
https://github.com/eclipse/openj9/blob/9b2299f2be56526a89c7e96ed3d7ae435936b783/runtime/jcl/common/proxy.c#L88-L94

**Comment by pshipton** [comment]
@mikezhang1234567890 is this ready for re-review? If you push new changes and don't make any new comments, there isn't any notification to the reviewer.

**Comment by mikezhang1234567890** [comment]
Yes, sorry. I was looking into Dan's last comment, but those 2 paths both end up calling `defineClassCommon` anyways.

This change is ready for re-review.

File: runtime/vm/createramclass.cpp [hunk 2]
```diff
@@ -3108,6 +3108,15 @@ internalCreateRAMClassFromROMClass(J9VMThread *vmThread, J9ClassLoader *classLoa
 			if (J9UTF8_LITERAL_EQUALS(J9UTF8_DATA(className), J9UTF8_LENGTH(className), MAGIC_ACCESSOR_IMPL)) {
 				classFlags |= J9ClassIsExemptFromValidation;
 			}
+
+#if JAVA_SPEC_VERSION == 8
+			/* check if a proxy class is being created by checking if the name matches the generated implementation class
+			   name excluding the generated characters */
+			if (0 == strncmp( (char*)J9UTF8_DATA(className), "com/sun/proxy/$Proxy", 20)) {
```
Comment (keithc-ca) [inline runtime/vm/createramclass.cpp]: nits: no space after the opening parenthesis; the cast should be `(const char *)`.

What prevents a hostile class from defining classes with this name prefix and bypassing validation?

**Comment by DanHeidinga** [comment]
Similar to @keithc-ca's concerns, can we move the fix for this into `openj9/runtime/jcl/common/proxy.c`?  It ensures the logic is only applicable to proxy classes and provides more of a limited surface to the change.

Is it possible to do the name lookup in the proxy.c code and pass a flag through to the defineClass call?

**Comment by mikezhang1234567890** [comment]
Should be. I'll see if there's an appropriate flag to use.

**Comment by DanHeidinga** [comment]
@mikezhang1234567890 Does passing `J9_FINDCLASS_FLAG_UNSAFE` work?  Or does it imply more than the `J9ClassIsExemptFromValidation` this patch sets?

**Comment by mikezhang1234567890** [comment]
@DanHeidinga updated the PR to do the name check from `proxy.c` and pass in the `J9_FINDCLASS_FLAG_UNSAFE` flag to `defineClassCommon`.

File: runtime/jcl/common/proxy.c [hunk 3]
```diff
@@ -23,6 +23,19 @@
 #include "jclglob.h"
 #include "jclprots.h"
 
+#if JAVA_SPEC_VERSION == 8
+static BOOLEAN isProxyExemptFromVerification(JNIEnv * env, jstring className) {
+	if (NULL != className) {
+		const char * utf8Name = (const char *) (*env)->GetStringUTFChars(env, className, NULL);
```
Comment (DanHeidinga) [inline runtime/jcl/common/proxy.c]: Every `GetStringUTFChars` needs a matching `ReleaseStringUTF8Chars` call.

File: runtime/jcl/common/proxy.c [hunk 4]
```diff
@@ -65,6 +78,11 @@ static jclass proxyDefineClass(
 
 	vmFuncs->internalExitVMToJNI(currentThread);
 
+#if JAVA_SPEC_VERSION == 8
+	if (isProxyExemptFromVerification(env, className)) {
+		return defineClassCommon(env, classLoader, className, classBytes, offset, length, pd, J9_FINDCLASS_FLAG_UNSAFE, NULL);
+	}
+#endif /* JAVA_SPEC_VERSION == 8 */
 	return defineClassCommon(env, classLoader, className, classBytes, offset, length, pd, 0, NULL);
```
Comment (DanHeidinga) [inline runtime/jcl/common/proxy.c]: These two calls only differ in one parameter.  To make that clearer, can you refactor the code like:
```
UDATA defineClassOptions = 0;
....
if (isProxyExemptFromVerification(env, className)) {
    defineClassOptions |= J9_FINDCLASS_FLAG_UNSAFE;
}
return defineClassCommon(env, classLoader, className, classBytes, offset, length, pd, defineClassOptions, NULL);
```

File: runtime/jcl/common/proxy.c [hunk 5]
```diff
@@ -90,6 +108,11 @@ Java_java_lang_reflect_Proxy_defineClass0__Ljava_lang_ClassLoader_2Ljava_lang_St
 	if (classLoader == NULL || pd == NULL) {
 		return proxyDefineClass(env, classLoader, className, classBytes, offset, length, pd);
 	} else {
+#if JAVA_SPEC_VERSION == 8
+		if (isProxyExemptFromVerification(env, className)) {
+			return defineClassCommon(env, classLoader, className, classBytes, offset, length, pd, J9_FINDCLASS_FLAG_UNSAFE, NULL);
+		}
+#endif /* JAVA_SPEC_VERSION == 8 */
```
Comment (DanHeidinga) [inline runtime/jcl/common/proxy.c]: please use the same kind of pattern here as well

**Comment by mikezhang1234567890** [comment]
@DanHeidinga can you review again please?

File: runtime/jcl/common/proxy.c [hunk 6]
```diff
@@ -23,6 +23,23 @@
 #include "jclglob.h"
 #include "jclprots.h"
 
+#if JAVA_SPEC_VERSION == 8
```
Comment (DanHeidinga) [inline runtime/jcl/common/proxy.c]: Are these ifdefs needed?  Is this file used in later JDK releases or do they use Unsafe.defineClass instead? 

I guess my question is should this whole file only be included in JDK8?

Comment (mikezhang1234567890) [reply runtime/jcl/common/proxy.c]: Looking into it, the later JDK releases don't use this file at all. JDK 11 seems to use `Unsafe.defineClass` to create the proxies, and JDK 12 goes through `ClassLoader.defineClassImpl`.

Should I remove those ifdefs then?

**Comment by DanHeidinga** [comment]
@mikezhang1234567890 Let's leave the ifdefs for this PR as this is a fairly constrained change.  Can you open a second PR that stops compiling this file for JDK11+?

**Comment by DanHeidinga** [comment]
Jenkins test sanity,extended zlinux jdk8

**Comment by DanHeidinga** [comment]
Jenkins test sanity osx jdk11

**Comment by DanHeidinga** [comment]
@mikezhang1234567890 Can you create a PR with the same commits against the `v0.15.0-release` branch?

File: runtime/jcl/common/proxy.c [hunk 7]
```diff
@@ -23,6 +23,23 @@
...
+static BOOLEAN isProxyExemptFromVerification(JNIEnv * env, jstring className) {
```
Comment (keithc-ca) [inline runtime/jcl/common/proxy.c]: formatting: this function should begin with
```
static BOOLEAN
isProxyExemptFromVerification(JNIEnv * env, jstring className)
{
```

**Comment by DanHeidinga** [comment]
Removed the backport:candidate label as this has been merged into 0.15
