### PR TITLE
Check if SCC is valid at startup

### LINKED ISSUE #7890: JDK8 Win64 java -version crash VMState: 0x000503ff Shared cache offset out of bounds
Happens only on JDK8 64bit (internal nightly build). Seems to be 100% reproducible. I have a set of diagnostic files saved. Last passed build was Nov 10 58d490796d0276f5c3f3b45a6cf21513ecf7bde1 
```
00:01:43.811  unzip file: OpenJ9-JDK8-x86-64_windows-20191121-211505.tar.gz ...
00:01:58.863  unzip file: test-images.tar.gz ...
00:02:01.630  Run C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly/openjdkbinary/j2sdk-image/bin/java -version
00:02:01.630  Assertion failed at C:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\build\windows-x86_64-normal-server-release\vm\compiler\env\J9SharedCache.cpp:457: false
00:02:01.630  VMState: 0x000503ff
00:02:01.630  	Shared cache offset out of bounds
00:02:01.630  compiling java/util/Hashtable.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; at level: cold
00:02:01.630  
00:02:01.630  Unhandled exception
00:02:01.630  Type=Segmentation error vmState=0x000503ff
00:02:01.630  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=0000000057F18A46 ContextFlags=0010001f
00:02:01.630  Handler1=0000000057C1B470 Handler2=00007FF87553CC70 InaccessibleWriteAddress=0000000000000000
00:02:01.630  RDI=000000000E868788 RSI=000000000E868780 RAX=0000000000000000 RBX=000A42E7ED469368
00:02:01.630  RCX=A1AEBD1D8CAD0000 RDX=0000000000000000 R8=0000000000000069 R9=00000000000000CB
00:02:01.630  R10=00000000000002C0 R11=0000000000000059 R12=0000000000000003 R13=FFFFFFFFF1797878
00:02:01.630  R14=000000000E6E7DB0 R15=0000000001824300
00:02:01.630  RIP=0000000057F18A46 RSP=000000000E8685E0 RBP=000000000E8687C8 GS=002B
00:02:01.630  FS=0053 ES=002B DS=002B
00:02:01.630  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
00:02:01.631  Module=C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\jre\bin\compressedrefs\j9jit29.dll
00:02:01.631  Module_base_address=0000000057BD0000 Offset_in_DLL=0000000000348a46
00:02:01.631  
00:02:01.631  Method_being_compiled=java/util/Hashtable.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
00:02:01.631  Target=2_90_20191121_232 (Windows Server 2016 10.0 build 14393)
00:02:01.631  CPU=amd64 (4 logical CPUs) (0x1fff8d000 RAM)
00:02:01.631  ----------- Stack Backtrace -----------
00:02:01.631  openjdk version "1.8.0_232-internal"
00:02:01.631  OpenJDK Runtime Environment (build 1.8.0_232-internal-jenkins_2019_11_21_18_40-b00)
00:02:01.631  Eclipse OpenJ9 VM (build ibm_sdk-b2a72599ec, JRE 1.8.0 Windows Server 2016 amd64-64-Bit Compressed References 20191121_232 (JIT enabled, AOT enabled)
00:02:01.631  OpenJ9   - b2a72599ec
00:02:01.631  OMR      - 8eb476a6e
00:02:01.631  JCL      - f6352f08a86 based on jdk8u232-b09)
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x2b65f6 (0x0000000057F18A46 [j9jit29+0x348a46])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x2b686d (0x0000000057F18CBD [j9jit29+0x348cbd])
00:02:02.506  j9jit_testarossa+0x7e84 (0x0000000057C47C94 [j9jit29+0x77c94])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x9a698 (0x0000000057CFCAE8 [j9jit29+0x12cae8])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x9e338 (0x0000000057D00788 [j9jit29+0x130788])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x9834d (0x0000000057CFA79D [j9jit29+0x12a79d])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x9caa2 (0x0000000057CFEEF2 [j9jit29+0x12eef2])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x9b4b3 (0x0000000057CFD903 [j9jit29+0x12d903])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0xa3ff2 (0x0000000057D06442 [j9jit29+0x136442])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x804c6 (0x0000000057CE2916 [j9jit29+0x112916])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x35cd6e (0x0000000057FBF1BE [j9jit29+0x3ef1be])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x35f0aa (0x0000000057FC14FA [j9jit29+0x3f14fa])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x3559d9 (0x0000000057FB7E29 [j9jit29+0x3e7e29])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x352cb1 (0x0000000057FB5101 [j9jit29+0x3e5101])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x3553a2 (0x0000000057FB77F2 [j9jit29+0x3e77f2])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x3f9c39 (0x000000005805C089 [j9jit29+0x48c089])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x3fa766 (0x000000005805CBB6 [j9jit29+0x48cbb6])
00:02:02.506  Java_java_lang_invoke_MutableCallSite_invalidate+0x259dff (0x0000000057EBC24F [j9jit29+0x2ec24f])
00:02:02.506  (0x0000000057C26786 [j9jit29+0x56786])
00:02:02.506  (0x0000000057C2828E [j9jit29+0x5828e])
00:02:02.506  j9port_init_library+0x1b476 (0x00007FF87553DE46 [j9prt29+0x1de46])
00:02:02.506  j9port_init_library+0x1b674 (0x00007FF87553E044 [j9prt29+0x1e044])
00:02:02.506  (0x0000000057C28B2C [j9jit29+0x58b2c])
00:02:02.506  (0x0000000057C290F2 [j9jit29+0x590f2])
00:02:02.506  (0x0000000057C23EDA [j9jit29+0x53eda])
00:02:02.506  (0x0000000057C26E8E [j9jit29+0x56e8e])
00:02:02.506  j9port_init_library+0x1b6af (0x00007FF87553E07F [j9prt29+0x1e07f])
00:02:02.506  (0x0000000057C286DD [j9jit29+0x586dd])
00:02:02.506  omrthread_detach+0x1fd (0x00007FF878E85D6D [J9THR29+0x5d6d])
00:02:02.506  _endthreadex+0x43 (0x00000000599E1D9F [msvcr100+0x21d9f])
00:02:02.506  _endthreadex+0xdf (0x00000000599E1E3B [msvcr100+0x21e3b])
00:02:02.506  BaseThreadInitThunk+0x14 (0x00007FF87FB184D4 [KERNEL32+0x84d4])
00:02:02.506  RtlUserThreadStart+0x21 (0x00007FF88023E851 [ntdll+0x6e851])
00:02:02.506  ---------------------------------------
00:02:02.506  JVMDUMP039I Processing dump event "gpf", detail "" at 2019/11/22 01:34:14 - please wait.
00:02:02.506  JVMDUMP032I JVM requested System dump using 'C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly\openjdkbinary\core.20191122.013414.15288.0001.dmp' in response to an event
00:02:10.626  JVMDUMP010I System dump written to C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly\openjdkbinary\core.20191122.013414.15288.0001.dmp
00:02:10.626  JVMDUMP032I JVM requested Java dump using 'C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly\openjdkbinary\javacore.20191122.013414.15288.0002.txt' in response to an event
00:02:10.626  JVMDUMP010I Java dump written to C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly\openjdkbinary\javacore.20191122.013414.15288.0002.txt
00:02:10.626  JVMDUMP032I JVM requested Snap dump using 'C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly\openjdkbinary\Snap.20191122.013414.15288.0003.trc' in response to an event
00:02:10.626  JVMDUMP010I Snap dump written to C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly\openjdkbinary\Snap.20191122.013414.15288.0003.trc
00:02:10.626  JVMDUMP007I JVM Requesting JIT dump using 'C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly\openjdkbinary\jitdump.20191122.013414.15288.0004.dmp'
```

### LINKED ISSUE #8404: Java 8 x64: Running application causes a segmentation error vmState=0x000503ff
Java -version output
--------------------
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200122_564 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)

Summary of problem
------------------
My Java application crashes with Java 8 Update 242 b08 with J9 VM 0.18.1 on Windows.
The previous Java version 8 Update 232 b09 with J9 VM 0.17.0 has no problem to run it.

Unhandled exception
Type=Segmentation error vmState=0x000503ff
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFD0AFF0113 ContextFlags=0010005f
Handler1=0000000051EFBC30 Handler2=00007FFD15D5C910 InaccessibleReadAddress=00000000242E0000
RDI=0000000000CB3ED0 RSI=00000000ADD66466 RAX=000000000000536D RBX=0000000003157700
RCX=000000000000536D RDX=00000000242E0000 R8=FFFFFFFFED4602A4 R9=000000000000002F
R10=00007FFD17F68AB0 R11=0000000000000000 R12=000000000FB0CE68 R13=0000000000C92130
R14=0000000000000000 R15=000000000000FFFC
RIP=00007FFD0AFF0113 RSP=00000000110D8730 RBP=00000000110D8760 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000041a00000 (f: 1101004800.000000, d: 5.439686e-315)
XMM1 000000003dcccccd (f: 1036831936.000000, d: 5.122630e-315)
XMM2 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
XMM3 412e848000000000 (f: 0.000000, d: 1.000000e+006)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\ProgramData\DAKOSY\AppStart\java\j9\x64\1.8.242-b08\jdk8u242-b08-jre\bin\compressedrefs\j9vm29.dll
Module_base_address=00007FFD0AFA0000 Offset_in_DLL=0000000000050113

Method_being_compiled=com/sun/proxy/$Proxy1.hashCode()I
Target=2_90_20200122_564 (Windows 10 10.0 build 18363)
CPU=amd64 (16 logical CPUs) (0x7ea446000 RAM)
----------- Stack Backtrace -----------
(0x00007FFD0AFF0113 [j9vm29+0x50113])
J9_CreateJavaVM+0x90742 (0x00007FFD0B0B8602 [j9vm29+0x118602])
(0x00007FFD0AFF0265 [j9vm29+0x50265])
(0x00007FFD0B00ECF7 [j9vm29+0x6ecf7])
(0x00007FFD0B011390 [j9vm29+0x71390])
Java_java_lang_invoke_MutableCallSite_invalidate+0x5bfc84 (0x00000000525034D4 [j9jit29+0x6534d4])
Java_java_lang_invoke_InterfaceHandle_convertITableIndexToVTableIndex+0x45c (0x0000000051F3A9AC [j9jit29+0x8a9ac])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa2f02 (0x0000000051FE6752 [j9jit29+0x136752])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa6b78 (0x0000000051FEA3C8 [j9jit29+0x13a3c8])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa0b8d (0x0000000051FE43DD [j9jit29+0x1343dd])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa52e2 (0x0000000051FE8B32 [j9jit29+0x138b32])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa3cf3 (0x0000000051FE7543 [j9jit29+0x137543])
Java_java_lang_invoke_MutableCallSite_invalidate+0xac822 (0x0000000051FF0072 [j9jit29+0x140072])
Java_java_lang_invoke_MutableCallSite_invalidate+0x7f426 (0x0000000051FC2C76 [j9jit29+0x112c76])
Java_java_lang_invoke_MutableCallSite_invalidate+0x7d826 (0x0000000051FC1076 [j9jit29+0x111076])
Java_java_lang_invoke_MutableCallSite_invalidate+0x367e9e (0x00000000522AB6EE [j9jit29+0x3fb6ee])
Java_java_lang_invoke_MutableCallSite_invalidate+0x36a1ea (0x00000000522ADA3A [j9jit29+0x3fda3a])
Java_java_lang_invoke_MutableCallSite_invalidate+0x360a09 (0x00000000522A4259 [j9jit29+0x3f4259])
Java_java_lang_invoke_MutableCallSite_invalidate+0x35dce1 (0x00000000522A1531 [j9jit29+0x3f1531])
Java_java_lang_invoke_MutableCallSite_invalidate+0x3603d2 (0x00000000522A3C22 [j9jit29+0x3f3c22])
Java_java_lang_invoke_MutableCallSite_invalidate+0x404d49 (0x0000000052348599 [j9jit29+0x498599])
Java_java_lang_invoke_MutableCallSite_invalidate+0x405876 (0x00000000523490C6 [j9jit29+0x4990c6])
Java_java_lang_invoke_MutableCallSite_invalidate+0x262b8b (0x00000000521A63DB [j9jit29+0x2f63db])
(0x0000000051F06F26 [j9jit29+0x56f26])
(0x0000000051F08AAB [j9jit29+0x58aab])
j9port_init_library+0x2b116 (0x00007FFD15D5DAE6 [j9prt29+0x2dae6])
j9port_init_library+0x2b314 (0x00007FFD15D5DCE4 [j9prt29+0x2dce4])
(0x0000000051F0934C [j9jit29+0x5934c])
(0x0000000051F09912 [j9jit29+0x59912])
(0x0000000051F0467A [j9jit29+0x5467a])
(0x0000000051F0762E [j9jit29+0x5762e])
j9port_init_library+0x2b34f (0x00007FFD15D5DD1F [j9prt29+0x2dd1f])
(0x0000000051F08EFD [j9jit29+0x58efd])
omrthread_detach+0x1fd (0x00007FFD23DD5D6D [J9THR29+0x5d6d])
_endthreadex+0x43 (0x0000000053A81D9F [msvcr100+0x21d9f])
_endthreadex+0xdf (0x0000000053A81E3B [msvcr100+0x21e3b])
BaseThreadInitThunk+0x14 (0x00007FFD52397BD4 [KERNEL32+0x17bd4])
RtlUserThreadStart+0x21 (0x00007FFD5268CED1 [ntdll+0x6ced1])
---------------------------------------
JVMDUMP039I Speicherauszugsereignis "gpf", Detail "" um 2020/01/24 17:31:54 - bitte warten.
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von System mit "C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\core.20200124.173154.9988.0001.dmp" an
JVMDUMP010I Speicherauszug von System in C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\core.20200124.173154.9988.0001.dmp geschrieben
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von Java mit "C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\javacore.20200124.173154.9988.0002.txt" an
JVMDUMP010I Speicherauszug von Java in C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065

c353d431777e0618146de7fde51dca9c0dbd77be056\content\javacore.20200124.173154.9988.0002.txt geschrieben
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von Snap mit "C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\Snap.20200124.173154.9988.0003.trc" an
JVMDUMP010I Speicherauszug von Snap in C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\Snap.20200124.173154.9988.0003.trc geschrieben
JVMDUMP007I JVM fordert JIT-Speicherauszug mit "C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\jitdump.20200124.173154.9988.0004.dmp" an.
JVMDUMP010I Speicherauszug von JIT in C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\jitdump.20200124.173154.9988.0004.dmp geschrieben
JVMDUMP013I Speicherauszugsereignis "gpf", Detail "" wurde verarbeitet.

Diagnostic files
----------------
[dumps-without-core-20200124.173154.zip](https://github.com/eclipse/openj9/files/4109744/dumps-without-core-20200124.173154.zip)

The compressed core dump ist too big (about 116 MB). Please write if you need it.

### LINKED ISSUE #8517: product crashes at startup when upgrading from 13.0.1-openj9-0.17 to 13.0.2-openj9-0.18
4 files are generated i 7zipped them here: http://download.servoy.com/openj9-0.18.7z

This is an eclipse based product where in the eclipse.ini file i just switch the vm
And if i run it with OpenJDK 13.0.1 it works fine, just switching the vm:

-vm
D:\servoy_inst\201912_rc2\developer\jdk-13.0.2+8-jre/bin/j9vm/jvm.dll
-vmargs
-Xshareclasses:nonfatal
-Xms40m
-Xmx1G
--add-modules=ALL-SYSTEM

will always crash it right away at startup generating always 4 files.

### PR DESCRIPTION
**Pull request by dsouzai**
Currently the check to see if the SCC is valid is done at the first
compilation. This is done on the load run to see if it is ok to load a
method that was stored to the SCC. However, other parts of the compiler,
such as the IProfiler, don't use this check.

This PR checks the validity of the SCC at startup and updates the
global flag that all parts of the compiler check.

Fixes #7890
Fixes #8404
Fixes #8517

### CODE REVIEW

**Comment by dsouzai** [comment]
@mpirvu is there anything extra I have to do for JITServer?

**Comment by mpirvu** [comment]
> @mpirvu is there anything extra I have to do for JITServer?

JITServer generates AOT bodies at the request of the client which is responsible for validating the header and storing/loading the AOT body.

File: runtime/compiler/control/rossa.cpp [hunk 1]
```diff
@@ -1868,13 +1868,24 @@ aboutToBootstrap(J9JavaVM * javaVM, J9JITConfig * jitConfig)
...
    if (isSharedAOT)
       {
-      /* If AOT Shared Classes is turned ON, perform compatibility checks for AOT Shared Classes */
-      if (0) //!validateSharedClassAOTHeader(javaVM, curThread, compInfo))
+      /* If AOT Shared Classes is turned ON, perform compatibility checks for AOT Shared Classes
+       *
+       * This check has to be done after latePostProcessJIT so that all the necessary JIT options
+       * can be set
+       */
+      TR_J9SharedCacheVM *fe = (TR_J9SharedCacheVM *) TR_J9VMBase::get(jitConfig, curThread, TR_J9VMBase::AOT_VM);
```
Comment (mpirvu) [inline runtime/compiler/control/rossa.cpp]: Do we actually need a TR_J9SharedCacheVM frontend? As far as I can tell we only need the frontend to ask if it asynchronous compilation is disabled.

File: runtime/compiler/control/rossa.cpp [hunk 2]
```diff
@@ -1868,13 +1868,24 @@ aboutToBootstrap(J9JavaVM * javaVM, J9JITConfig * jitConfig)
...
+      if (!compInfo->reloRuntime()->validateAOTHeader(fe, curThread))
          {
-         TR::Options::getAOTCmdLineOptions()->setOption(TR_NoLoadAOT);
-         TR::Options::getAOTCmdLineOptions()->setOption(TR_NoStoreAOT);
-         TR::Options::setSharedClassCache(false);
-         TR_J9SharedCache::setSharedCacheDisabledReason(TR_J9SharedCache::AOT_DISABLED);
+         /* This could be the first run, in which case validateAOTHeader might return false because
```
Comment (mpirvu) [inline runtime/compiler/control/rossa.cpp]: I wonder is there is any problem when there is no header, but the SCC has been created by another JVM, maybe because that JVM didn't have the time to generate any AOT compilations. Could IProfiler be present in such an SCC and therefore defeat the check here?

Comment (dsouzai) [reply runtime/compiler/control/rossa.cpp]: Hm, that is definitely a possible scenario. Maybe I'd have to add code in the IProfiler to generate the header if it doesn't already exist in that case.

File: runtime/compiler/control/rossa.cpp (hunk 1 above)
Comment (dsouzai) [reply runtime/compiler/control/rossa.cpp]: Probably not, I mean given that we're calling code to validate the AOT Header, the SCC must be enabled.

File: runtime/compiler/control/rossa.cpp (hunk 2 above)
Comment (dsouzai) [reply runtime/compiler/control/rossa.cpp]: At the moment, we only ever persist the IProfiler data either in `genIL` (if we haven't delayed AOT loads) or when we do an AOT load (if we have delayed AOT loads).

Do you think we should still have code to create a header in the IProfiler just in case?

Comment (dsouzai) [reply runtime/compiler/control/rossa.cpp]: @mpirvu ^

**Comment by pshipton** [comment]
@dsouzai I've updated the description to use auto-close keywords.
https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

File: runtime/compiler/control/rossa.cpp (hunk 2 above)
Comment (mpirvu) [reply runtime/compiler/control/rossa.cpp]: @dsouzai Yes, we still have a problem, because an AOT compilation starts, `genIL()` is performed and some IP data is stored in SCC, then, while the JIT compiler is in optimizer or codegen, the JVM enters the shutdown stage, the compilation is aborted and we don't reach the point where the header is written.

I do not see a problem if delayed AOT load feature is in place though (we must have compiled and stored an AOT body in order to reach the point where IP data is stored).

File: runtime/compiler/control/rossa.cpp (hunk 1 above)
Comment (dsouzai) [reply runtime/compiler/control/rossa.cpp]: Addressed in 0233e1d2ebdd5ba3beae46cb7d6b7f0a1c2f8b06

File: runtime/compiler/control/rossa.cpp (hunk 2 above)
Comment (dsouzai) [reply runtime/compiler/control/rossa.cpp]: Addressed in 0233e1d2ebdd5ba3beae46cb7d6b7f0a1c2f8b06

**Comment by dsouzai** [comment]
@mpirvu I updated the code so that at startup we validate the header or create it if it doesn't exist. This will guarantee that all existing (and future) parts of the compiler that use the SCC will do so only when it is valid.

**Comment by mpirvu** [comment]
jenkins test all jdk11

**Comment by dsouzai** [comment]
```
12:16:27  Command "git read-tree -mu HEAD" returned status code 128:
12:16:27  stdout: 
12:16:27  stderr: fatal: Not a valid object name HEAD
```

**Comment by dsouzai** [comment]
jenkins test sanity all jdk11

**Comment by dsouzai** [comment]
s390x build failure is likely because of https://github.com/eclipse/openj9/issues/8738

**Comment by pshipton** [comment]
Not that once these changes are final we'll need to deliver them to the v0.19.0-release branch as well.

**Comment by dsouzai** [comment]
Ah, good to know, thanks.

**Comment by dsouzai** [comment]
x86_64 build failed because of 
```
[2020-03-03T21:39:06.533Z] JITServer is currently a technology preview. Its use is not yet supported
[2020-03-03T21:39:06.533Z] JIT: env var TR_Options is set to verbose={compileEnd|JITServer|heartbeat},vlog=testServerUnreachableForAWhile.server.jitverboselog.out
[2020-03-03T21:39:06.533Z] Error: -Xaot:nostore option is not compatible with JITServer mode.JVMJ9VM015W Initialization error for library j9jit29(13): cannot initialize JIT
[2020-03-03T21:39:06.533Z] JITServer_CreateServer failed, error code=-2
```

**Comment by mpirvu** [comment]
@dsouzai  If you are at the server (`compInfo->getPersistentInfo()->getRemoteCompilationMode() == JITServer::SERVER`) just don't set any global options, not even TR::Options::setSharedClassCache(false).
The server is supposed to receive options from the client and obey those.

**Comment by dsouzai** [comment]
@mpirvu ready for review again.

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Comment by dsouzai** [comment]
Don't really know why the test is still failing. I'm going to have to build locally and see what the problem is.

**Comment by dsouzai** [comment]
I think it's because of https://github.com/eclipse/openj9/issues/8229 . The `#ifdef` changed to be consistent with the VM, and I'm guarding the code with the old `#ifdef` because I didn't rebase. _Sigh.._

**Comment by dsouzai** [comment]
jenkins test sanity all jdk11

**Comment by dsouzai** [comment]
And of course in the 0.19 branch the code uses the old `#ifdef` [1]. I'll have to make sure that in the 0.19 version, I use the old one.

[1] https://github.com/eclipse/openj9/blob/67a91ae5544e5cb7c6d0a61ad66241e4f89209aa/runtime/compiler/control/rossa.cpp#L1884

**Comment by dsouzai** [comment]
@mpirvu all tests passed finally; could you do one more review and merge please.
