### PR TITLE
load java.instrument module when loading agent

### LINKED ISSUE #2030: Cannot load agent jar in Java 10 modular app
Trying to load an agent jar into OpenJ9 Java 10 using the attach API, where Java 10 is running a module, results in a AgentLoadException error 102. It works with OpenJDK.
```
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message find class on InstrumentationImpl failed at JPLISAgent.c line: 493
*** java.lang.instrument ASSERTION FAILED ***: "success" at InvocationAdapter.c line: 395
Agent failed to start!
JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
```

openjdk version "10.0.1-adoptopenjdk" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1-adoptopenjdk+0-adhoc..openjdk)
Eclipse OpenJ9 VM (build master-6f5a858a, JRE 10 Windows 8.1 amd64-64-Bit Compressed References 20180523_54 (JIT enabled, AOT enabled)
OpenJ9   - 6f5a858a
OMR      - 15290506
JCL      - 228f0625d8 based on jdk-10.0.1+10)

You need to start a Java 10 modular app to connect to, such as jconsole. While running jconsole exhibits the problem you don't get a console. To get a console run "java -m jdk.jconsole/sun.tools.jconsole.JConsole" instead.

Sample loader code.
```
		String vmid = com.ibm.tools.attach.target.AttachHandler.getVmId();
		VirtualMachineDescriptor target = null;
		List<VirtualMachineDescriptor> machines = VirtualMachine.list();
		for (VirtualMachineDescriptor vmd : machines) {
			if (vmd.id().equals(vmid)) continue;
			System.out.println(vmd);
			if (vmd.displayName().contains(args[0])) {
				if (target != null) {
					System.out.println("Duplicates!");
					System.exit(1);
				}
				target = vmd;
			}
		}
		if (target == null) {
			System.out.println("No target found");
			System.exit(1);
		}
		VirtualMachine vm = VirtualMachine.attach(target);
		vm.loadAgent("t:\\peter\\premain.jar");
```

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Java 9 and above need the java.instrument module loaded when
using -javaagent or loading an instrumentation agent via late attach.
Avoid this on legacy versions of Java 9.

Fixes #2030 

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
Jenkins test sanity all

File: runtime/vm/classloadersearch.c [hunk 1]
```diff
@@ -34,6 +34,8 @@
 
 static UDATA addToSystemProperty(J9JavaVM * vm, const char * propertyName, const char * segment);
 static UDATA addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader, BOOLEAN enforceJarRestriction);
+#define INSTRUMENT_MODULE "java.instrument"
+UDATA JNICALL loadModule(J9JavaVM *vm, const char *moduleName, jobject *modulePtr);
```
Comment (keithc-ca) [inline runtime/vm/classloadersearch.c]: This method should be static in which case JNICALL should be omitted.

File: runtime/vm/classloadersearch.c [hunk 2]
```diff
@@ -237,3 +242,52 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
...
+	 * vm->jimModules may have been set already by JVMTI.
+	 * If not, grab a private copy of the class.
+	 */
+	if (NULL == jimModules) {
+		jimModules = (*env)->FindClass(env, "jdk/internal/module/Modules");
+	}
+	if (NULL == jimModules) {
+		rc = CLS_ERROR_NOT_FOUND;
+	} else {
+		jmethodID loadModule =
```
Comment (keithc-ca) [inline runtime/vm/classloadersearch.c]: Shouldn't this save `jimModules` in `vm->jimModules`?

File: runtime/vm/classloadersearch.c [hunk 3]
```diff
@@ -237,3 +242,52 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
...
+				(*env)->GetStaticMethodID(env, jimModules, "loadModule", "(Ljava/lang/String;)Ljava/lang/Module;");
+		if (NULL == loadModule) {
+			rc = CLS_ERROR_NOT_FOUND;
+		} else {
+			jstring moduleNameString =  (*env)->NewStringUTF(env, moduleName);
```
Comment (keithc-ca) [inline runtime/vm/classloadersearch.c]: A check that this succeeded should be added. Also please fix the formatting (extra space after `=`).

File: runtime/vm/classloadersearch.c [hunk 4]
```diff
@@ -237,3 +242,52 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
...
+
+
+/**
+ * Loads the named module using jdk.internal.module.Modules.loadModule()
+ *
+ * @param [in] vm pointer to JVM
+ * @param [in] moduleName name of module to load
+ * @param [out] modulePtr pointer to return module object.  May be null.
+ *
+ * @return CLS_ERROR_NONEE on success, other value on failure
```
Comment (keithc-ca) [inline runtime/vm/classloadersearch.c]: Please correct the success code.

File: runtime/vm/classloadersearch.c [hunk 5]
```diff
@@ -227,6 +229,9 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
 			if ((*env)->ExceptionCheck(env)) {
 				rc = CLS_ERROR_OUT_OF_MEMORY;
 			}
+			if 	((J2SE_VERSION(vm) >= J2SE_19) && (J2SE_SHAPE(vm) >= J2SE_SHAPE_B165)) {
```
Comment (gacholio) [inline runtime/vm/classloadersearch.c]: Some wild spacing here.

Comment (gacholio) [inline runtime/vm/classloadersearch.c]: This code should not run if the above code errored.  Need an else or goto cleanup.

File: runtime/vm/classloadersearch.c (hunk 3 above)
Comment (pdbain-ibm) [reply runtime/vm/classloadersearch.c]: Thanks.  Fixed.

File: runtime/vm/classloadersearch.c (hunk 2 above)
Comment (gacholio) [reply runtime/vm/classloadersearch.c]: Not clear what you mean here.  If you're going to cache it, you'll need to move the JVMTI code out into a helper in util (definitely don't duplicate the mutexxed init code),

Comment (gacholio) [reply runtime/vm/classloadersearch.c]: Is there a good reason this isn't just in the VM constant pool?  Could then use findKnownClass to get it.

**Comment by pdbain-ibm** [comment]
I moved the code to load jdk/internal/module/Modules to a utility file per GAC's suggestion
and addressed (I hope) the other comments.  I compiled and did an ad-hoc test.  Could someone run another pull request build?

File: runtime/vm/classloadersearch.c (hunk 2 above)
Comment (pdbain-ibm) [reply runtime/vm/classloadersearch.c]: That I don't know.  I stole the code from jvmtiModules.c.  Maybe @tajila knows.

**Comment by smlambert** [comment]
Jenkins test sanity all

File: runtime/util/moduleclasses.c [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+		omrthread_monitor_enter(vm->jlmModulesInitMutex);
+		if (NULL == vm->jimModules) {
+			jclass jimModules = (*env)->FindClass(env,
+					"jdk/internal/module/Modules");
+			if (NULL == jimModules) {
+				result = -1;
+			} else {
+				jclass globalModules = (*env)->NewGlobalRef(env, jimModules);
+				if (NULL == globalModules) {
+					omrthread_monitor_exit(vm->jlmModulesInitMutex);
```
Comment (keithc-ca) [inline runtime/util/moduleclasses.c]: This yields to two calls `omrthread_monitor_exit`.

File: runtime/util/moduleclasses.c [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+ *
+ * [1] https://www.gnu.org/software/classpath/license.html
+ * [2] http://openjdk.java.net/legal/assembly-exception.html
+ *
+ * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
+ *******************************************************************************/
+#include "j9.h"
+
+IDATA
+ensureJimModules(J9JavaVM* vm, JNIEnv* env) {
```
Comment (gacholio) [inline runtime/util/moduleclasses.c]: Formatting - also, don't pass both the thread and the VM.  I also despise the use of IDATA as a return value.

File: runtime/util/moduleclasses.c (hunk 6 above)
Comment (gacholio) [reply runtime/util/moduleclasses.c]: Right, this should just be and else case.

File: runtime/util/moduleclasses.c (hunk 7 above)
Comment (gacholio) [reply runtime/util/moduleclasses.c]: I suppose IDATA follows existing (if bad) conventions.

File: runtime/util/moduleclasses.c (hunk 6 above)
Comment (pdbain-ibm) [reply runtime/util/moduleclasses.c]: Oops.  Missed that.

File: runtime/vm/classloadersearch.c (hunk 2 above)
Comment (gacholio) [reply runtime/vm/classloadersearch.c]: @tajila Actually, VMCP classes are only loaded eagerly if they have fields/methods declared in the constant pool.  If it's just the class, they are loaded on demand.

Comment (gacholio) [reply runtime/vm/classloadersearch.c]: Discussed with Tobi & Peter, we will go with the CP solution to simplify.

**Comment by pdbain-ibm** [comment]
@jdekonin or @AdamBrousseau sanity builds are failing: `ERROR: Cannot find label value matching JOB_TYPE:'build' SPEC:'aix_ppc-64_cmprssptrs' and SDK_VERSION:'11'
Finished: FAILURE`  Is this a known issue?

File: runtime/util/moduleclasses.c (hunk 7 above)
Comment (pdbain-ibm) [reply runtime/util/moduleclasses.c]: ... or I could just delete the whole file and put the class in the VM constant pool, as discussed.

**Comment by pdbain-ibm** [comment]
Compiled this locally, but not tested.  @gacholio could you do a preliminary review?

File: runtime/vm/classloadersearch.c [hunk 8]
```diff
@@ -237,3 +241,71 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
 
 	return rc;
 }
+
+jclass
+getJimModules(J9VMThread *currentThread) {
```
Comment (gacholio) [inline runtime/vm/classloadersearch.c]: Brace on it's own line,

File: runtime/vm/classloadersearch.c [hunk 9]
```diff
@@ -237,3 +241,71 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
...
+		goto done;
+	}
+
+	vmModule = (*env)->CallStaticObjectMethod(env, jimModules, loadModule, moduleNameString);
+	if ((*env)->ExceptionOccurred(env)) {
+		rc = CLS_ERROR_INTERNAL;
+	} else if (NULL != modulePtr) {
+		*modulePtr = vmModule;
+	}
+	done:
```
Comment (gacholio) [inline runtime/vm/classloadersearch.c]: No indent.

Comment (gacholio) [reply runtime/vm/classloadersearch.c]: Could do a single assignment to *modulePtr here instead of the two you have.

**Comment by gacholio** [comment]
Other than a few nitpicks, this looks good to me.

File: runtime/vm/classloadersearch.c [hunk 10]
```diff
@@ -237,3 +241,71 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
 
 	return rc;
 }
+
+jclass
+getJimModules(J9VMThread *currentThread) {
+	J9JavaVM *vm = currentThread->javaVM;
+	if (NULL == vm->jimModules) {
+		const J9InternalVMFunctions *vmFuncs = vm->internalVMFunctions;
+		/* no need for mutual exclusion since repeating this is harmless */
```
Comment (gacholio) [inline runtime/vm/classloadersearch.c]: Need to enterVMFromJNI here.

File: runtime/vm/classloadersearch.c [hunk 11]
```diff
@@ -237,3 +241,71 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
...
+		J9Class *j9JimModules = vmFuncs->internalFindKnownClass(currentThread,
+				J9VMCONSTANTPOOL_JDKINTERNALMODULEMODULES,
+				J9_FINDKNOWNCLASS_FLAG_INITIALIZE | J9_FINDKNOWNCLASS_FLAG_NON_FATAL);
+		if (NULL != j9JimModules) {
+			vm->jimModules = (jclass)&j9JimModules->classObject;
+		} else {
+			currentThread->currentException = NULL;
+			currentThread->privateFlags &= ~J9_PRIVATE_FLAGS_REPORT_EXCEPTION_THROW;
+		}
```
Comment (gacholio) [inline runtime/vm/classloadersearch.c]: ...and exitVMToJNI here.

File: runtime/vm/classloadersearch.c (hunk 10 above)
Comment (gacholio) [reply runtime/vm/classloadersearch.c]: So you won't be able to declare and initialize j9JimModules on the same line.

**Comment by gacholio** [comment]
On further reflection, I'm not sure the constant pool was the right choice, as the module stuff is all being done in a JNI context and used in JNI calls.

Using FindClass is probably a better solution. The mutex can be avoided by doing:

enterVMFromJNI
J9Class *clazz = J9VM_J9CLASS_FROM_JCLASS(vmThread, jclassForModule);
jimModule = &clazz->classObject;
exitVMToJNI

File: runtime/vm/classloadersearch.c [hunk 12]
```diff
@@ -237,3 +241,71 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
...
+getJimModules(J9VMThread *currentThread) {
+	J9JavaVM *vm = currentThread->javaVM;
+	if (NULL == vm->jimModules) {
+		const J9InternalVMFunctions *vmFuncs = vm->internalVMFunctions;
+		/* no need for mutual exclusion since repeating this is harmless */
+		J9Class *j9JimModules = vmFuncs->internalFindKnownClass(currentThread,
+				J9VMCONSTANTPOOL_JDKINTERNALMODULEMODULES,
+				J9_FINDKNOWNCLASS_FLAG_INITIALIZE | J9_FINDKNOWNCLASS_FLAG_NON_FATAL);
+		if (NULL != j9JimModules) {
+			vm->jimModules = (jclass)&j9JimModules->classObject;
```
Comment (gacholio) [inline runtime/vm/classloadersearch.c]: We should add a macro for this later, even though it will look odd to J9CLASS_FROM_JCLASS followed by JCLASS_FROM_J9CLASS.

File: runtime/vm/classloadersearch.c (hunk 9 above)
Comment (pdbain-ibm) [reply runtime/vm/classloadersearch.c]: Sorry, please clarify.

File: runtime/vm/classloadersearch.c (hunk 8 above)
Comment (pdbain-ibm) [reply runtime/vm/classloadersearch.c]: > Brace on it's own line,
No apostrophe in the possessive of "it".

File: runtime/vm/classloadersearch.c (hunk 9 above)
Comment (gacholio) [reply runtime/vm/classloadersearch.c]: I'm saying you can do a single NULL check and assignment at done.

File: runtime/vm/classloadersearch.c (hunk 12 above)
Comment (gacholio) [reply runtime/vm/classloadersearch.c]: Also probably worth a comment here that the address of j9class->classObject is considered to be a JNI global ref.  It won't keep a class alive, but that's OK here since the class in question is not a candidate for unloading.

Comment (pdbain-ibm) [reply runtime/vm/classloadersearch.c]: https://github.com/eclipse/openj9/issues/2437

**Comment by gacholio** [comment]
jenkins test sanity xlinux jdk9

**Comment by gacholio** [comment]
jenkins test sanity xlinux jdk9

**Comment by gacholio** [comment]
Intentionally cancelled travis build since it will take too long to even start,

**Comment by pdbain-ibm** [comment]
@keithc-ca would you kindly review and approve?
Thanks

File: runtime/vm/classloadersearch.c (hunk 11 above)
Comment (pdbain-ibm) [reply runtime/vm/classloadersearch.c]: fixed.

File: runtime/vm/classloadersearch.c [hunk 13]
```diff
@@ -237,3 +241,81 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
 
 	return rc;
 }
+
+jclass
+getJimModules(J9VMThread *currentThread)
+{
+	J9JavaVM *vm = NULL;
+	vm = currentThread->javaVM;
```
Comment (keithc-ca) [inline runtime/vm/classloadersearch.c]: nit: this initialization could be collapsed into the declaration.

File: runtime/vm/classloadersearch.c [hunk 14]
```diff
@@ -237,3 +241,81 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
...
+ * @param [in] moduleName name of module to load
+ * @param [out] modulePtr pointer to return module object.  May be null.
+ *
+ * @return CLS_ERROR_NONE on success, other value on failure
+ */
+static UDATA
+loadModule(J9JavaVM *vm, const char *moduleName, jobject *modulePtr)
+{
+	UDATA rc = CLS_ERROR_NONE;
+	J9VMThread *currentThread = currentVMThread(vm);
```
Comment (keithc-ca) [inline runtime/vm/classloadersearch.c]: Where this function is used, we've already retrieved the current thread: it would make sense to avoid redoing that by passing `currentThread` or `env` instead of `vm`.

File: runtime/vm/classloadersearch.c [hunk 15]
```diff
@@ -237,3 +241,81 @@ addZipToLoader(J9JavaVM * vm, const char * filename, J9ClassLoader * classLoader
...
+	loadModule = (*env)->GetStaticMethodID(env, jimModules, "loadModule", "(Ljava/lang/String;)Ljava/lang/Module;");
+	if (NULL == loadModule) {
+		rc = CLS_ERROR_NOT_FOUND;
+		goto done;
+	}
+
+	vmModule = (*env)->CallStaticObjectMethod(env, jimModules, loadModule, moduleNameString);
+	if ((*env)->ExceptionOccurred(env)) {
+		rc = CLS_ERROR_INTERNAL;
+	} else if (NULL != modulePtr) {
```
Comment (keithc-ca) [inline runtime/vm/classloadersearch.c]: I like GAC's suggestion to move this after `done` and remove the `*modulePtr = NULL;` above.

**Comment by keithc-ca** [comment]
Jenkins test sanity win jdk8,jdk10

File: runtime/vm/classloadersearch.c (hunk 14 above)
Comment (pdbain-ibm) [reply runtime/vm/classloadersearch.c]: Will fix in https://github.com/eclipse/openj9/issues/2437

File: runtime/vm/classloadersearch.c (hunk 15 above)
Comment (pdbain-ibm) [reply runtime/vm/classloadersearch.c]: Agreed.  Will fix in https://github.com/eclipse/openj9/issues/2437

**Comment by pdbain-ibm** [comment]
Per discussion with Keith and GAC, this change is needed ASAP.  Deferring improvements to #2437.

**Comment by keithc-ca** [comment]
The windows failures are due to https://github.com/eclipse/openj9/issues/2440.

**Comment by keithc-ca** [comment]
Enough builds have passed to satisfy me.
