### PR TITLE
Fix findROMClassFromPC() when romClass is in the shared cache.

### LINKED ISSUE #7641: findROMClassFromPC() incorrectly returns NULL
Discovered by @gacholio 

findROMClassFromPC() incorrectly returns NULL but the ROMClass is in the shared cache. 

In the core file, it is discovered:
findROMClassFromPC() returns NULL when the passed in pc is 00007FF6A01C2022 

```
The romclass is:
!j9romclass 0x00007FF6A01C1B08
J9ROMClass at 0x7ff6a01c1b08 {
  Fields for J9ROMClass:
        0x0: U32 romSize = 0x000005A0 (1440)
        0x4: U32 singleScalarStaticCount = 0x00000001 (1)
        0x8: J9SRP(struct J9UTF8) className = !j9utf8 0x00007FF6A01BF1CA
        ...
The method is  java/util/TaskQueue.<clinit>()V
 
j9rommethod 0x7ff6a01c200c
J9ROMMethod at 0x7ff6a01c200c {
  Fields for J9ROMMethod:
        0x0: struct J9ROMNameAndSignature nameAndSignature = !j9romnameandsignature 0x00007FF6A01C200C
        0x8: U32 modifiers = 0x11040008 (285474824)
        0xc: U16 maxStack = 0x0001 (1)
        0xe: U16 bytecodeSizeLow = 0x0011 (17)
        0x10: U8 bytecodeSizeHigh = 0x00 (0)
        0x11: U8 argCount = 0x00 (0)
        0x12: U16 tempCount = 0x0000 (0)
}
Signature: <clinit>()V

The romclass/rommethod are in the rom class segment area in the shared cache.

This failure is intermittent.

### PR DESCRIPTION
**Pull request by hangshao0**
1. Check for potential romClass segment update regardless of the return
value of readCacheUpdates()
2. Issue write barrier after updating the romClass segment list
3. Check for potential romClass segment update before returning a class
from SH_CacheMap::findROMClass()

Fixes #7641

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
With test code here https://github.com/gacholio/openj9/tree/hack from @gacholio 

100x grinder all passed on Linux x86-64.
300x grinder all passed on Linux PPC.

File: runtime/shared_common/CacheMap.cpp [hunk 1]
```diff
@@ -984,6 +984,8 @@ SH_CacheMap::updateROMSegmentListForCache(J9VMThread* currentThread, SH_Composit
 			currentROMClass += currentROMSize;
 		}
 		currentSegment->heapAlloc = cacheAlloc;
+		VM_AtomicSupport::writeBarrier();
```
Comment (pshipton) [inline runtime/shared_common/CacheMap.cpp]: Pls move the above variables currentSegSize and maxSegmentSize into the inner scope.

File: runtime/shared_common/CacheMap.cpp [hunk 2]
```diff
@@ -2863,7 +2878,9 @@ SH_CacheMap::findROMClass(J9VMThread* currentThread, const char* path, Classpath
 #endif /* !defined(J9ZOS390) && !defined(AIXPPC) */
 	}
 
-	if (returnVal) { 
+	if (returnVal) {
+		/* Call updateROMSegmentList() to ensure that heapAlloc of the romClass segment is always updated to include the returned romClass */
+		updateROMSegmentList(currentThread, true);
```
Comment (pshipton) [inline runtime/shared_common/CacheMap.cpp]: To minimize the impact of updateROMSegmentList(), we can make the following changes in updateROMSegmentList():
- it's only necessary to initialize classSegmentMutex when hasClassSegmentMutex is false
- don't bother having `J9JavaVM* vm`, it's only used once
- just use _cc and delete the _cacheletHead code

File: runtime/shared_common/CacheMap.cpp [hunk 3]
```diff
@@ -984,6 +984,8 @@ SH_CacheMap::updateROMSegmentListForCache(J9VMThread* currentThread, SH_Composit
 			currentROMClass += currentROMSize;
 		}
 		currentSegment->heapAlloc = cacheAlloc;
+		VM_AtomicSupport::writeBarrier();
+		Trc_SHR_CM_updateROMSegmentList_NewHeapAlloc(currentThread, currentSegment, cacheAlloc);
```
Comment (pshipton) [inline runtime/shared_common/CacheMap.cpp]: Do we need this enabled by default (level 2)?

File: runtime/shared_common/CacheMap.cpp [hunk 4]
```diff
@@ -1346,21 +1348,27 @@ SH_CacheMap::refreshHashtables(J9VMThread* currentThread, bool hasClassSegmentMu
...
-		if (itemsRead > 0) {
-			if (hasClassSegmentMutex) {
+		if ((UnitTest::CACHE_FULL_TEST != UnitTest::unitTest)
+			|| (itemsRead > 0)
+		) {
+			/* A previous call might enter here with hasClassSegmentMutex = false, which added romclasses to the hashtable without updating the 
+			 * romClass segment list. In this case updateROMSegmentList() needs to be called this time if hasClassSegmentMutex is true, 
+			 * regaredless of the itemsRead value.
+			 */
+				if (hasClassSegmentMutex) {
```
[the remark this answers is not in the document]
Comment (hangshao0) [reply runtime/shared_common/CacheMap.cpp]: Fixed

File: runtime/shared_common/CacheMap.cpp (hunk 1 above)
Comment (hangshao0) [reply runtime/shared_common/CacheMap.cpp]: Fixed

File: runtime/shared_common/CacheMap.cpp (hunk 3 above)
Comment (hangshao0) [reply runtime/shared_common/CacheMap.cpp]: Changed to level 4

File: runtime/shared_common/CacheMap.cpp (hunk 2 above)
Comment (hangshao0) [reply runtime/shared_common/CacheMap.cpp]: Fixed. 
> just use _cc and delete the _cacheletHead code

_cc equals to _ccHead, instead of using _cc, I changed to use _ccHead. Also removed one unnecessary NULL check for cache inside updateROMSegmentList().

File: runtime/shared_common/CacheMap.cpp [hunk 5]
```diff
@@ -883,39 +883,29 @@ SH_CacheMap::createNewSegment(J9VMThread* currentThread, UDATA type, J9MemorySeg
 void
 SH_CacheMap::updateROMSegmentList(J9VMThread* currentThread, bool hasClassSegmentMutex)
 {
-	SH_CompositeCacheImpl* cache;
+	SH_CompositeCacheImpl* cache = _ccHead;
 #if defined(J9VM_THR_PREEMPTIVE)
-	J9JavaVM* vm = currentThread->javaVM;
-
-	omrthread_monitor_t classSegmentMutex = vm->classMemorySegments->segmentMutex;
+	omrthread_monitor_t classSegmentMutex = currentThread->javaVM->classMemorySegments->segmentMutex;
```
Comment (pshipton) [inline runtime/shared_common/CacheMap.cpp]: The initialization here can move into the `if (!hasClassSegmentMutex) {` block below.

File: runtime/shared_common/CacheMap.cpp [hunk 6]
```diff
@@ -883,39 +883,29 @@ SH_CacheMap::createNewSegment(J9VMThread* currentThread, UDATA type, J9MemorySeg
...
+		Trc_SHR_Assert_ShouldHaveLocalMutex(classSegmentMutex);
 	}
+#endif
 	
 	while (cache) {
-		if (cache && cache->isStarted()) {
+		if (cache->isStarted()) {
 			updateROMSegmentListForCache(currentThread, cache);
 		}
 		cache = cache->getNext();
```
Comment (pshipton) [inline runtime/shared_common/CacheMap.cpp]: Is this loop necessary to support layered caches? If not, remove it. If so, we only need to look at the lower level caches once since they are read-only.

Comment (hangshao0) [reply runtime/shared_common/CacheMap.cpp]: We need to call this function for lower layers only during startup. Add one parameter `bool topLayerOnly` to the signature.

File: runtime/shared_common/CacheMap.cpp (hunk 5 above)
Comment (hangshao0) [reply runtime/shared_common/CacheMap.cpp]: classSegmentMutex is also used when exiting the mutex and in the trace Trc_SHR_Assert_ShouldHaveLocalMutex which are outside of the `if (!hasClassSegmentMutex) { `block

Comment (pshipton) [reply runtime/shared_common/CacheMap.cpp]: Everything was address except this comment.

Comment (pshipton) [reply runtime/shared_common/CacheMap.cpp]: Ok, I see.

**Comment by pshipton** [comment]
jenkins test sanity,extended win jdk8
