### PR TITLE
Resolve the race condition setting/reading _theca->cacheFullFlags

### LINKED ISSUE #8628: ASSERTION FAILED ** at CompositeCache.cpp:5438: (((softMaxValue - usedBytes) >= 2048))
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK/126
JLM_Tests_interface_0
```
===============================================
Running test JLM_Tests_interface_0 ...
===============================================
JLM_Tests_interface_0 Start Time: Fri Feb 21 04:04:48 2020 Epoch Time (ms): 1582275888554
variation: NoOptions
JVM_OPTIONS: -Xcompressedrefs 
JVMSHRC023E Cache does not exist
09:04:49.470 0x2373700   j9shr.1012   *   ** ASSERTION FAILED ** at CompositeCache.cpp:5438: (((softMaxValue - usedBytes) >= 2048))
```

### PR DESCRIPTION
**Pull request by hangshao0**
Compare _cacheFullFlags against _theca->cacheFullFlags to see if
_theca->cacheFullFlags has been updated. If yes, use the latest
_theca->cacheFullFlags value to set runtime flags.

Move the setting of _cacheFullFlags and its comparison against
_theca->cacheFullFlags inside _runtimeFlagsProtectMutex.

Fixes #8628

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

File: runtime/shared_common/CompositeCache.cpp [hunk 1]
```diff
@@ -6813,7 +6813,7 @@ SH_CompositeCacheImpl::updateRuntimeFullFlags(J9VMThread *currentThread)
 	if (_readOnlyOSCache || J9_ARE_ALL_BITS_SET(*_runtimeFlags, J9SHR_RUNTIMEFLAG_ENABLE_READONLY)) {
 		goto done;
 	}
-
+	cacheFullFlags = _theca->cacheFullFlags;
```
Comment (pshipton) [inline runtime/shared_common/CompositeCache.cpp]: This isn't a fix, you can use compare and swap to fix it.

Comment (hangshao0) [reply runtime/shared_common/CompositeCache.cpp]: You mean compare and swap on local variable cacheFullFlags ?

Comment (hangshao0) [reply runtime/shared_common/CompositeCache.cpp]: The time window I find in the old code is between line 6802 and line 6817. Line 6802 got a value of 0 from  _theca->cacheFullFlags.  When doing comparison at line 6817, both _theca->cacheFullFlags and _cacheFullFlags are changed by another thread. The current thread is still using a cached cacheFullFlags which is 0 .

Comment (pshipton) [reply runtime/shared_common/CompositeCache.cpp]: Compare and swap can be used to combine the test `_cacheFullFlags == cacheFullFlags` and the assignment `_cacheFullFlags = cacheFullFlags` into one operation. Sounds like the fetch of `_theca->cacheFullFlags`, the test and the assignment need to be protected by a monitor. Is the code that changed `_theca->cacheFullFlags` in another thread using any monitor?

Comment (hangshao0) [reply runtime/shared_common/CompositeCache.cpp]: The other thread is changing _theca->cacheFullFlags, _cacheFullFlags  and the runtime flags here:
 https://github.com/eclipse/openj9/blob/master/runtime/shared_common/CompositeCache.cpp#L6142to#L6150
It is not using a monitor. But it is inside the write mutex. 

We shouldn't cache the obsolete _theca->cacheFullFlags value to the local variable cacheFullFlags and use the obsolete value to update the runtime flags.  I think we should fetch the latest _theca->cacheFullFlags to update the runtime flags.

Comment (pshipton) [reply runtime/shared_common/CompositeCache.cpp]: Since a thread switch can occur at any time, and the cpu is free to move code around somewhat, changing the source to move the fetch of _theca->cacheFullFlags closer to the test isn't a proper fix. Some kind of synchronization needs to be used to guarantee consistent results.

Comment (hangshao0) [reply runtime/shared_common/CompositeCache.cpp]: Moved the setting of _cacheFullFlags and its comparison against
_theca->cacheFullFlags inside _runtimeFlagsProtectMutex.

File: runtime/shared_common/CompositeCache.cpp [hunk 2]
```diff
@@ -6813,16 +6813,19 @@ SH_CompositeCacheImpl::updateRuntimeFullFlags(J9VMThread *currentThread)
...
 		goto done;
 	}
-
-	if (_cacheFullFlags == cacheFullFlags) {
+	
+	/* It is possible we take _headerProtectMutex inside _runtimeFlagsProtectMutex.
+	 * So assert we do not hold _headerProtectMutex before taking _runtimeFlagsProtectMutex.
+	 */
+	Trc_SHR_Assert_True(1 != omrthread_monitor_owned_by_self(_headerProtectMutex));
+	omrthread_monitor_enter(_runtimeFlagsProtectMutex);
```
Comment (pshipton) [inline runtime/shared_common/CompositeCache.cpp]: I don't see the corresponding omrthread_monitor_exit()

Comment (pshipton) [reply runtime/shared_common/CompositeCache.cpp]: nm, it's already there.

**Comment by pshipton** [comment]
jenkins test sanity,extended win,plinux,zlinux,osx jdk8

**Comment by pshipton** [comment]
jenkins test extended.system win,plinux,zlinux,osx jdk8
