### PR TITLE
Make sure the cache file path is shorter than the OS limit

### LINKED ISSUE #4351: Test-extended.system win SharedClassesAPI_0 assert The softmx limit for shared cache usage is smaller than the minimum feasible value
```
STF 17:43:37.304 - +------ Step 31 - DefinedLocationGroupAccessJava: Monitor workload processes
STF 17:43:37.304 - | Wait for processes to meet expectations
STF 17:43:37.304 - |   Processes: [WL1, WL2, WL3, WL4]
STF 17:43:37.304 - |
STF 17:43:37.304 - Monitoring processes: WL1 WL2 WL3 WL4
STF 17:43:37.436 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\core.20190117.174337.2916.0001.dmp
STF 17:43:37.476 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\core.20190117.174337.7228.0001.dmp
STF 17:43:39.106 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\javacore.20190117.174337.7228.0002.txt
STF 17:43:42.090 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\Snap.20190117.174337.7228.0003.trc
STF 17:43:44.403 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\Snap.20190117.174337.2916.0003.trc
STF 17:43:44.462 - Found dump at: C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\javacore.20190117.174337.2916.0002.txt
STF 17:43:44.718 - **FAILED** Process WL3 ended with exit code (4294967295) and not the expected exit code/s (0)
STF 17:43:44.719 - Monitoring Report Summary:
STF 17:43:44.719 -   o Process WL1 has crashed unexpectedly
STF 17:43:44.720 -   o Process WL2 ended with the expected exit code (0)
STF 17:43:44.720 -   o Process WL3 has crashed unexpectedly
STF 17:43:44.720 -   o Process WL4 has crashed unexpectedly
```

in stderr output
```
JVMSHRC777W The softmx limit for shared cache usage is smaller than the minimum feasible value 3980759048 bytes.
23:43:37.434 0xee9a00   j9shr.1012   *   ** ASSERTION FAILED ** at CompositeCache.cpp:6276: (((0 != _theca) && hasWriteMutex(currentThread) && (getTotalSize() >= softMaxBytes) && (softMaxBytes >= getUsedBytes())))
```

in javacore
```
1XECTHTYPE     Current thread history (J9VMThread:0x00000000017D9A00)
3XEHSTTYPE     23:43:37:474859273 GMT j9shr.1012 - * ** ASSERTION FAILED ** at CompositeCache.cpp:6276: (((0 != _theca) && hasWriteMutex(currentThread) && (getTotalSize() >= softMaxBytes) && (softMaxBytes >= getUsedBytes()))) 
3XEHSTTYPE     23:43:37:474851307 GMT j9prt.58 -  <j9shmem_stat exit - contents of controlFile C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\caches\javasharedresources\\C290M4F1A64_DefinedLocationGroupAccessJavaWL3_G35 is corrupted 
3XEHSTTYPE     23:43:37:474838657 GMT j9prt.56 -  >j9shmem_stat entered, name = C290M4F1A64_DefinedLocationGroupAccessJavaWL3_G35 
3XEHSTTYPE     23:43:37:474830133 GMT j9shr.2197 - * CC setCacheAreaBoundaries: The softmx bytes 0 is smaller than the already used bytes 3980759048 
3XEHSTTYPE     23:43:37:474393980 GMT j9prt.58 -  <j9shmem_stat exit - contents of controlFile C:\Users\jenkins\workspace\Test-extended.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15477678633841\SharedClassesAPI_0\20190117-174310-SharedClassesAPI\results\caches\javasharedresources\\C290M4F1A64_DefinedLocationGroupAccessJavaWL3_G35 is corrupted 
3XEHSTTYPE     23:43:37:474383497 GMT j9prt.56 -  >j9shmem_stat entered, name = C290M4F1A64_DefinedLocationGroupAccessJavaWL3_G35 
3XEHSTTYPE     23:43:37:474374591 GMT j9shr.1028 -   CC setCacheAreaBoundaries: finalSegmentStart=000000000FA99000, newCacheEnd=0000000022640000, _theca->totalBytes=314572608 
3XEHSTTYPE     23:43:37:474367741 GMT j9shr.1027 -   CC setCacheAreaBoundaries: finalSegmentStart=000000000FA981E0, origCacheEnd=0000000022640000, _theca->totalBytes=314572608 
3XEHSTTYPE     23:43:37:474357480 GMT j9shr.1026 -  >CC setCacheAreaBoundaries: Entering 
3XEHSTTYPE     23:43:37:474347666 GMT j9shr.2269 -   CC startup: initializing a new cache 
```

### PR DESCRIPTION
**Pull request by hangshao0**
1. Remove duplicated define of J9SH_MAXPATH in j9sharedhelper.h
2. Make sure the length of non-persistent cache mutex name is less than _MAX_PATH on Windows.
3. Make sure the cache file path is shorter than J9SH_MAXPATH before
starting up the shared cache.

closes #4351

Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
Reviewer: @pshipton

File: runtime/shared_common/shrinit.cpp [hunk 1]
```diff
@@ -5128,4 +5138,49 @@ j9shr_findGCHints(J9VMThread* currentThread, UDATA *heapSize1, UDATA *heapSize2)
...
+ *
+ * @param [in] vm Pointer to the VM structure
+ * @param [in] cacheDirName The cache control directory
+ * @param [in] runtimeFlags The runtime flags used by this cache
+ * @param [in] cacheName The shared cache name
+ *
+ * @return 0 if the length of the cache file path is not greater than J9SH_MAXPATH, -1 otherwise.
+ */
+static IDATA
+checkCacheFilePath(J9JavaVM* vm, const char* ctrlDirName, const char* cacheName, U_64 runtimeFlags, UDATA verboseFlags)
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: Seems verboseFlags isn't used.

Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

File: runtime/shared_common/shrinit.cpp [hunk 2]
```diff
@@ -5128,4 +5138,49 @@ j9shr_findGCHints(J9VMThread* currentThread, UDATA *heapSize1, UDATA *heapSize2)
...
+{
+	char cacheNameWithVGen[J9SH_MAXPATH];
+	char cacheFilePath[J9SH_MAXPATH];
+	char cacheDirName[J9SH_MAXPATH];
+	IDATA rc = 0;
+	PORT_ACCESS_FROM_JAVAVM(vm);	
+	J9PortShcVersion versionData;
+	
+	memset(cacheNameWithVGen, 0, J9SH_MAXPATH);
```
[the remark this answers is not in the document]
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

File: runtime/shared_common/shrinit.cpp [hunk 3]
```diff
@@ -5128,4 +5138,49 @@ j9shr_findGCHints(J9VMThread* currentThread, UDATA *heapSize1, UDATA *heapSize2)
...
 }
 
+
+/**
+ * Check if the length of the cache file path is greater than J9SH_MAXPATH
+ *
+ * @param [in] vm Pointer to the VM structure
+ * @param [in] cacheDirName The cache control directory
+ * @param [in] runtimeFlags The runtime flags used by this cache
+ * @param [in] cacheName The shared cache name
```
[the remark this answers is not in the document]
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

**Comment by hangshao0** [comment]
On my second thought, we won't reach the places where Trc_SHR_Assert_ShouldNeverHappen() is added here.
SH_OSCache::getCachePathName() won't touch the actual cache file, it only compares the cache file length to J9SH_MAXPATH - 1. 
We call SH_OSCache::getCachePathName() first in checkCacheFilePath(), we continue to startup the cache only when SH_OSCache::getCachePathName() returns 0 (cache file is shorter than J9SH_MAXPATH - 1)
So later inside SH_OSCache::commonStartup(), SH_OSCachesysv::startup(), SH_OSCachesysv::restoreFromSnapshot() and j9shr_createCacheSnapshot(),  SH_OSCache::getCachePathName() won't return -1.

**Comment by pshipton** [comment]
So what happens on non-Windows if the OS path length is less than EsMaxPath?

**Comment by pshipton** [comment]
and why is setSoftMaxBytes() being called on a cache that can't be opened?

**Comment by hangshao0** [comment]
> So what happens on non-Windows if the OS path length is less than EsMaxPath?

User will not be able to startup up the shared cache. J9NLS_SHRC_OSCACHE_MMAP_STARTUP_FILEOPEN_ERROR (Error opening shared class cache file) with a portlib error code and error message will be printed out.

> and why is setSoftMaxBytes() being called on a cache that can't be opened?

On Windows, when creating the cache file, omrfile_open() returns a valid fd even when the cache file path is > 260. Later when setting softmx, we make sure softmx is < _actualFileLength. But we are not able to stat the file to get the actual file length using the same cache file path,  _actualFileLength is 0, leading to an assertion failure.

**Comment by hangshao0** [comment]
> User will not be able to startup up the shared cache. J9NLS_SHRC_OSCACHE_MMAP_STARTUP_FILEOPEN_ERROR....

Assuming file open API works properly on non-Windows.

**Comment by pshipton** [comment]
> omrfile_open() returns a valid fd even when the cache file path is > 260

Seems strange, is there a bug in omrfile_open()? What happens if the fd is used to write data?

**Comment by hangshao0** [comment]
> Seems strange, is there a bug in omrfile_open()? What happens if the fd is used to write data?

omrfile_open() calls Windows API CreateFileW(). I don't see anything special there. 
https://github.com/eclipse/omr/blob/master/port/win32/omrfile.c#L594

We can successfully write data to the fd.

**Comment by pshipton** [comment]
And the file doesn't exist on the machine?

**Comment by hangshao0** [comment]
> And the file doesn't exist on the machine?

The file is there on the machine. But it cannot be found by omrfile_attr() (which calls GetFileAttributesW())

**Comment by hangshao0** [comment]
Another thing I noticed is that the JVM hangs if I remove the assertion of softmx < _actualFileLength

**Comment by hangshao0** [comment]
> But it cannot be found by omrfile_attr() (which calls GetFileAttributesW())

Correction: omrfile_attr() is working properly. The reason omrfile_attr() does not find the cache file is because I changed J9SH_MAXPATH to MAX_PATH, if I revert this change. omrfile_attr() is able to find the cache file. 

The story here is that on Windows, if file path length is > 260, `\\?\ `needs to be prepended to the path. 

From https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation
`To specify an extended-length path, use the "\\?\" prefix. For example, "\\?\D:\very long path".`

The OMR file APIs are using file_get_unicode_path() to prepend `\\?\`. So when creating the cache file (whose length > 260) via omrfile_open(), `\\?\` is prepended and the cache file can be successfully created. However, there are cases where we are directly accessing the cache file using APIs in j9shmem.c. j9shsem.c (like j9shmem_stat()) rather than the omr file APIs. `\\?\ `is not prepended there, so we get errors when using these APIs. I tried fixing all the APIs in j9shmem.c. j9shsem.c and j9shsem_deprecated.c to prepend `\\?\ `when necessary, but I found out CreateMutexW() does not support path to be > 260. We failed on creating the mutex. 
See 
https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-createmutexw
https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-createmutexexw

```
lpName

The name of the mutex object. The name is limited to MAX_PATH characters. 
```

On Windows, we need to restrict the path length of non-persistent cache file to < 260.

**Comment by hangshao0** [comment]
This change is ready to be reviewed again.

File: runtime/oti/j9port.h [hunk 4]
```diff
@@ -170,8 +170,10 @@
 #define J9PORT_SHSEM_MODE_NOWAIT ((uintptr_t) 2)
 /** @} */
 
-/* The following defines are used by j9shmem and j9shsem */
+/* The following defines are used by j9shmem.c, j9shsem.c and j9shsem_deprecated.c */
 #define J9SH_MAXPATH EsMaxPath
+#define MUTEX_STR "_mutex"
```
Comment (pshipton) [inline runtime/oti/j9port.h]: Should be J9SH_MUTEX_STR and J9SH_SET_STR to be consistent with the other defines and help qualify their purpose.

File: runtime/shared_common/CacheLifecycleManager.cpp [hunk 5]
```diff
@@ -987,55 +987,57 @@ j9shr_destroy_snapshot(struct J9JavaVM* vm, const char* ctrlDirName, UDATA verbo
...
-			if (0 == rc) {
-				noSnapshotExists = false;
-				snapshotStatus = J9SH_DESTROYED_OLDER_GEN_SNAPSHOT;
-				CLM_TRACE1(J9NLS_SHRC_CLCM_SNAPSHOT_REMOVED_OLDER_GEN, snapshotName);
-			} else if (-2 == rc) {
-				noSnapshotExists = false;
-				snapshotStatus = J9SH_DESTROY_FAILED_OLDER_GEN_SNAPSHOT;
-				returnVal = snapshotStatus;
-				CLM_TRACE1(J9NLS_SHRC_CLCM_SNAPSHOT_FAILED_REMOVED_OLDER_GEN, snapshotName);
+		if (SH_OSCache::getCachePathName(PORTLIB, cacheDirName, pathFileName, J9SH_MAXPATH, nameWithVGen) == 0) {
```
Comment (pshipton) [inline runtime/shared_common/CacheLifecycleManager.cpp]: Should be  `0 == ...`

File: runtime/shared_common/CacheLifecycleManager.cpp [hunk 6]
```diff
@@ -987,55 +987,57 @@ j9shr_destroy_snapshot(struct J9JavaVM* vm, const char* ctrlDirName, UDATA verbo
...
-				memset(&versionData, 0, sizeof(J9PortShcVersion));
-				/* Do not care about the getValuesFromShcFilePrefix() return value */
-				getValuesFromShcFilePrefix(PORTLIB, nameWithVGen, &versionData);
-				if (J9SH_FEATURE_COMPRESSED_POINTERS == versionData.feature) {
-					CLM_TRACE1(J9NLS_SHRC_CLCM_SNAPSHOT_DESTROYED_CR, snapshotName);
-				} else if (J9SH_FEATURE_NON_COMPRESSED_POINTERS == versionData.feature) {
-					CLM_TRACE1(J9NLS_SHRC_CLCM_SNAPSHOT_DESTROYED_NONCR, snapshotName);
-				} else {
-					CLM_TRACE1(J9NLS_SHRC_CLCM_SNAPSHOT_DESTROYED, snapshotName);
+		if (SH_OSCache::getCachePathName(PORTLIB, cacheDirName, pathFileName, J9SH_MAXPATH, nameWithVGen) == 0) {
```
Comment (pshipton) [inline runtime/shared_common/CacheLifecycleManager.cpp]: Should be `0 == ...`

File: runtime/shared_common/OSCachesysv.cpp [hunk 7]
```diff
@@ -2673,8 +2677,12 @@ SH_OSCachesysv::restoreFromSnapshot(J9JavaVM* vm, const char* cacheName, UDATA n
 	}
 
 	SH_OSCache::getCacheVersionAndGen(PORTLIB, vm, nameWithVGen, CACHE_ROOT_MAXLEN, cacheName, &versionData, OSCACHE_CURRENT_CACHE_GEN, false);
-	/* No check for the return value of getCachePathName() as it always returns 0 */
-	SH_OSCache::getCachePathName(PORTLIB, cacheDirName, pathFileName, J9SH_MAXPATH, nameWithVGen);
+
+	if (SH_OSCache::getCachePathName(PORTLIB, cacheDirName, pathFileName, J9SH_MAXPATH, nameWithVGen) != 0) {
```
Comment (pshipton) [inline runtime/shared_common/OSCachesysv.cpp]: Should be `0 != ...`

File: runtime/shared_common/shrinit.cpp [hunk 8]
```diff
@@ -5128,4 +5156,60 @@ j9shr_findGCHints(J9VMThread* currentThread, UDATA *heapSize1, UDATA *heapSize2)
 	return returnVal;
 }
 
+
+/**
+ * Check if the length of the cache file path is greater than the maximum limit.
+ *
+ * @param [in] vm Pointer to the VM structure
+ * @param [in] cacheDirName The cache control directory
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: Called ctrlDirName in the function declaration.

File: runtime/shared_common/shrinit.cpp [hunk 9]
```diff
@@ -5128,4 +5156,60 @@ j9shr_findGCHints(J9VMThread* currentThread, UDATA *heapSize1, UDATA *heapSize2)
...
+ * @param [in] cacheName The shared cache name
+ * @param [in] cacheType The type of the shared cache
+
+ *
+ * @return 0 if the length of the cache file path is not greater than maximum limit, -1 otherwise.
+ */
+static IDATA
+checkCacheFilePath(J9JavaVM* vm, const char* ctrlDirName, const char* cacheName, U_32 cacheType)
+{
+	char cacheNameWithVGen[J9SH_MAXPATH];
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: These first two can be moved to the inner scope.

File: runtime/shared_common/shrinit.cpp [hunk 10]
```diff
@@ -5128,4 +5156,60 @@ j9shr_findGCHints(J9VMThread* currentThread, UDATA *heapSize1, UDATA *heapSize2)
...
+	PORT_ACCESS_FROM_JAVAVM(vm);	
+	J9PortShcVersion versionData;
+	
+	memset(cacheNameWithVGen, 0, sizeof(cacheNameWithVGen));
+	memset(cacheDirName, 0, sizeof(cacheDirName));
+	memset(cacheFilePath, 0, sizeof(cacheFilePath));
+	setCurrentCacheVersion(vm, J2SE_VERSION(vm), &versionData);
+	
+	versionData.cacheType = cacheType;
+	if (-1 == SH_OSCache::getCacheDir(vm, ctrlDirName, cacheDirName, J9SH_MAXPATH, versionData.cacheType)) {
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: sizeof(cacheDirName) instead of J9SH_MAXPATH

File: runtime/shared_common/shrinit.cpp [hunk 11]
```diff
@@ -5128,4 +5156,60 @@ j9shr_findGCHints(J9VMThread* currentThread, UDATA *heapSize1, UDATA *heapSize2)
...
+checkCacheFilePath(J9JavaVM* vm, const char* ctrlDirName, const char* cacheName, U_32 cacheType)
+{
+	char cacheNameWithVGen[J9SH_MAXPATH];
+	char cacheFilePath[J9SH_MAXPATH];
+	char cacheDirName[J9SH_MAXPATH];
+	IDATA rc = 0;
+	PORT_ACCESS_FROM_JAVAVM(vm);	
+	J9PortShcVersion versionData;
+	
+	memset(cacheNameWithVGen, 0, sizeof(cacheNameWithVGen));
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: Are the memset's really required?

File: runtime/shared_common/shrinit.cpp [hunk 12]
```diff
@@ -5128,4 +5156,60 @@ j9shr_findGCHints(J9VMThread* currentThread, UDATA *heapSize1, UDATA *heapSize2)
...
+	versionData.cacheType = cacheType;
+	if (-1 == SH_OSCache::getCacheDir(vm, ctrlDirName, cacheDirName, J9SH_MAXPATH, versionData.cacheType)) {
+		rc = -1;
+	} else {
+		/* Check for the shared memory file if it is persistent cache. Otherwise check the semaphore file as the name of semaphore file is longer than the shared memory/cache snapshot file */
+		SH_OSCache::getCacheVersionAndGen(
+				PORTLIB,
+				vm,
+				cacheNameWithVGen,
+				J9SH_MAXPATH,
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: sizeof(cacheNameWithVGen) instead of J9SH_MAXPATH

File: runtime/shared_common/shrinit.cpp [hunk 13]
```diff
@@ -5128,4 +5156,60 @@ j9shr_findGCHints(J9VMThread* currentThread, UDATA *heapSize1, UDATA *heapSize2)
...
+				cacheName,
+				&versionData,
+				SH_OSCache::getCurrentCacheGen(),
+				J9PORT_SHR_CACHE_TYPE_PERSISTENT == versionData.cacheType);
+		rc = SH_OSCache::getCachePathName(PORTLIB, cacheDirName, cacheFilePath, J9SH_MAXPATH, cacheNameWithVGen);
```
Comment (pshipton) [inline runtime/shared_common/shrinit.cpp]: sizeof(cacheFilePath) instead of J9SH_MAXPATH

File: runtime/oti/j9port.h (hunk 4 above)
Comment (hangshao0) [reply runtime/oti/j9port.h]: Fixed

File: runtime/shared_common/CacheLifecycleManager.cpp (hunk 5 above)
Comment (hangshao0) [reply runtime/shared_common/CacheLifecycleManager.cpp]: Fixed

File: runtime/shared_common/CacheLifecycleManager.cpp (hunk 6 above)
Comment (hangshao0) [reply runtime/shared_common/CacheLifecycleManager.cpp]: Fixed

File: runtime/shared_common/shrinit.cpp (hunk 8 above)
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Changed the declaration.

File: runtime/shared_common/shrinit.cpp (hunk 10 above)
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

File: runtime/shared_common/shrinit.cpp (hunk 12 above)
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

File: runtime/shared_common/shrinit.cpp (hunk 13 above)
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

File: runtime/shared_common/shrinit.cpp (hunk 11 above)
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: I don't want any garbage value in theses arrays. I prefer keeping the memset's.

File: runtime/shared_common/shrinit.cpp (hunk 9 above)
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

File: runtime/shared_common/OSCachesysv.cpp (hunk 7 above)
Comment (hangshao0) [reply runtime/shared_common/OSCachesysv.cpp]: Fixed

File: runtime/shared_common/shrinit.cpp (hunk 8 above)
Comment (pshipton) [reply runtime/shared_common/shrinit.cpp]: This comment still needs to be fixed to match the function declaration.

**Comment by pshipton** [comment]
jenkins test sanity win jdk8

File: runtime/shared_common/shrinit.cpp (hunk 8 above)
Comment (hangshao0) [reply runtime/shared_common/shrinit.cpp]: Fixed

**Comment by pshipton** [comment]
Reverted as per https://github.com/eclipse/openj9/issues/4614#issuecomment-461216574
