### PR TITLE
Return GB18030 for codepage 936 on Java 8 only

### LINKED ISSUE #2824: GB18030 is absent in openjdk9-openj9 and openjdk10-openj9 on windows 10
When I test openjdk9-openj9 and openjdk10-openj9 on windows 10, the locale is zh_CN, i got the error bellow:
```
E:\temp\src>java -version
线程 "main" 中发生异常java/lang/ExceptionInInitializerError
        位于 java/lang/J9VMInternals.ensureError (java.base@9/J9VMInternals.java:191)
        位于 java/lang/J9VMInternals.recordInitializationFailure (java.base@9/J9VMInternals.java:180)
        位于 sun/nio/fs/WindowsFileSystemProvider.getFileAttributeView (java.base@9/WindowsFileSystemProvider.java:163)
        位于 sun/nio/fs/WindowsFileSystemProvider.readAttributes (java.base@9/WindowsFileSystemProvider.java:194)
        位于 sun/nio/fs/AbstractFileSystemProvider.isRegularFile (java.base@9/AbstractFileSystemProvider.java:137)
        位于 java/nio/file/Files.isRegularFile (java.base@9/Files.java:2265)
        位于 jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:257)
        位于 jdk/internal/loader/BuiltinClassLoader.access$100 (java.base@9/BuiltinClassLoader.java:109)
        位于 jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:296)
        位于 jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:286)
        位于 jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:354)
        位于 jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:108)
        位于 jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:218)
        位于 java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:217)
        位于 java/lang/Thread.initialize (java.base@9/Thread.java:422)
        位于 java/lang/Thread.<init> (java.base@9/Thread.java:153)
java/nio/charset/UnsupportedCharsetException: GB18030
        位于 java/nio/charset/Charset.forName (java.base@9/Charset.java:529)
        位于 sun/nio/fs/Util.<clinit> (java.base@9/Util.java:40)
        位于 sun/nio/fs/WindowsFileSystemProvider.getFileAttributeView (java.base@9/WindowsFileSystemProvider.java:163)
        位于 sun/nio/fs/WindowsFileSystemProvider.readAttributes (java.base@9/WindowsFileSystemProvider.java:194)
        位于 sun/nio/fs/AbstractFileSystemProvider.isRegularFile (java.base@9/AbstractFileSystemProvider.java:137)
        位于 java/nio/file/Files.isRegularFile (java.base@9/Files.java:2265)
        位于 jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:257)
        位于 jdk/internal/loader/BuiltinClassLoader.access$100 (java.base@9/BuiltinClassLoader.java:109)
        位于 jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:296)
        位于 jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:286)
        位于 jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:354)
        位于 jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:108)
        位于 jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:218)
        位于 java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:217)
        位于 java/lang/Thread.initialize (java.base@9/Thread.java:422)
        位于 java/lang/Thread.<init> (java.base@9/Thread.java:153)
```

### PR DESCRIPTION
**Pull request by hangshao0**
Fixes #2824

Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

File: runtime/jcl/win32/syshelp.c [hunk 1]
```diff
@@ -217,8 +217,12 @@ char* getPlatformFileEncoding(JNIEnv *env, char *codepage, int size, int encodin
...
-			if (IsValidCodePage(54936))
-				return "GB18030";
+			J9JavaVM* vm = ((J9VMThread *)env)->javaVM;
+			if (J2SE_VERSION(vm) < J2SE_19) {
+				if (IsValidCodePage(54936)) {
+					return "GB18030";
+				}
+			}
 			return "GBK";
 		} else if (cp == 54936) return "GB18030";
```
Comment (pshipton) [inline runtime/jcl/win32/syshelp.c]: Is this a code page that can be configured on Windows? It seems this case won't work either.

Comment (hangshao0) [reply runtime/jcl/win32/syshelp.c]: I didn't find a way to configure code page to 54396 on my windows. I can only configure it to 396.

**Comment by pshipton** [comment]
jenkins compile win jdk8
