### PR TITLE
Replace the incorrect assert with verbose log

### LINKED ISSUE #5149: JITaaS in remote AOT mode fails the sanity test with -Xlockword
JITaaS fails sanity `_cmdLineTest_J9test_SE80_0` in remote AOT mode with `TR_DisableDelayRelocationForAOTCompilations` and `disableSymbolValidationManager`. 

```
---SUMMARY OF FAILED TESTS---
-Xlockword default mode
-Xlockword minimizeFootprint mode
-Xlockword all mode
-Xlockword setting lockword
-Xlockword setting noLockword
-Xlockword setting what
-Xlockword with two instance on command line
-Xlockword with duplicates
-----------------------------
```
```
 [ERR] JIT: env var TR_EnableJITaaSRemoteAOT is set to 1
 [ERR] JIT: env var TR_OptionsAOT is set to forceAOT
 [ERR] JIT: env var TR_Options is set to forceAOT
 [ERR] JIT: env var TR_EnableJITaaSRemoteAOT is set to 1
 [ERR] Assertion failed at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/runtime/RelocationRuntime.cpp:902: false
 [ERR] 	AOT header validation failed: incompatible lockword options
 [ERR] #0: function TR_LinuxCallStackIterator::printStackBacktrace(TR::Compilation*)+0x45 [0x7fedcf764f3b]
 [ERR] #1: function TR_Debug::printStackBacktrace()+0x2f [0x7fedcf777d0f]
 [ERR] #2: /root/home/ahuo/sdk/jvmxa6480_jitaas_411001/jre/lib/amd64/compressedrefs/libj9jit29.so(+0xfa4e24) [0x7fedcf3e7e24]
 [ERR] #3: function TR::assertion(char const*, int, char const*, char const*, ...)+0xc3 [0x7fedcf3e7fda]
 [ERR] #4: function TR_SharedCacheRelocationRuntime::incompatibleCache(unsigned int, unsigned int, char*)+0x3b [0x7fedceff6613]
 [ERR] #5: function TR_SharedCacheRelocationRuntime::validateAOTHeader(J9JavaVM*, TR_FrontEnd*, J9VMThread*)+0x340 [0x7fedceff6e9e]
 [ERR] #6: function TR::CompilationInfo::compileOnSeparateThread(J9VMThread*, TR::IlGeneratorMethodDetails&, void*, TR_YesNoMaybe, TR_CompilationErrorCode*, bool*, TR_OptimizationPlan*)+0xbeb [0x7fedcee1e075]
 [ERR] #7: function TR::CompilationInfo::compileMethod(J9VMThread*, TR::IlGeneratorMethodDetails&, void*, TR_YesNoMaybe, TR_CompilationErrorCode*, bool*, TR_OptimizationPlan*)+0x8ff [0x7fedcee1d2c1]
```

### PR DESCRIPTION
**Pull request by a7ehuo**
`validateAOTHeader()` is supposed to fail when the current lockword
hash value does not match the one in the shared cache.
The assert in `incompatibleCache()` and `generateError()`
are too harsh. Replace it with the verbose log.

Fixes #5149

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
@dsouzai Could you help review and launch Jenkins? Thanks.

File: runtime/compiler/runtime/RelocationRuntime.cpp [hunk 1]
```diff
@@ -876,7 +876,11 @@ TR_SharedCacheRelocationRuntime::useDFPHardware(TR_FrontEnd *fe)
 void
 TR_SharedCacheRelocationRuntime::incompatibleCache(U_32 module_name, U_32 reason, char *assumeMessage)
    {
-   TR_ASSERT(false, assumeMessage);
+   if (TR::Options::isAnyVerboseOptionSet(TR_VerboseCompileRequest, TR_VerboseCompileEnd))
```
Comment (dsouzai) [inline runtime/compiler/runtime/RelocationRuntime.cpp]: I'd change this to `TR::Options::isAnyVerboseOptionSet()`

**Comment by dsouzai** [comment]
jenkins test sanity xlinux jdk8,jdk11
