### PR TITLE
memset controlFileStatus to 0 on Windows to avoid garbage values

### LINKED ISSUE #11843: shrtest_win_SE80_0 testFailedConstructor abort
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_0/240/
shrtest_win_SE80_0
```
testFailedConstructor begin
JVMSHRC659E An error has occurred while opening shared memory
JVMSHRC336E Port layer error code = -108
JVMSHRC337E Platform error message: (2) The system cannot find the file specified.
JVMSHRC662I Error recovery: destroyed semaphore set associated with shared class cache.
JVMSHRC680E Error recovery failure: Failed to remove the semaphore set control file C290M4F0A32_testConstructor_G41L00 associated with shared class cache.
JVMSHRC336E Port layer error code = 17

An unhandled error (4) has occurred.
J9Generic_Signal_Number=00000004
ExceptionCode=c0000005
ExceptionAddress=726DBFE0
ContextFlags=0001007f
Handler1=00D86450
Handler2=726D55D0
InaccessibleReadAddress=00000013
EDI=0063E38C
ESI=00000013
EAX=FFFFFFFF
EBX=00000000
ECX=00000014
EDX=FFFFFFFF
EIP=726DBFE0
ESP=0063E2D4
EBP=FFFFFFFF
EFLAGS=00210246
Module=F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_0\openjdkbinary\j2sdk-image\jre\bin\default\J9PRT29.dll
Module_base_address=726C0000
Offset_in_DLL=0001bfe0
JVMDUMP039I Processing dump event "abort", detail "" at 2021/01/30 22:24:31 - please wait.
```

### LINKED ISSUE #11908: shrtest_win_SE80_0 testConstructor The specified module could not be found
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1/246
shrtest_win_SE80_0
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1/246/functional_test_output.tar.gz
```
OSCacheTests started
OSCacheTestSysv begin
testBasic begin
testBasic: block accessed of length 1048384
testBasic: contents correct
JVMSHRC010I Shared cache "OSCacheUnitTest1" is destroyed
testBasic: PASS
testMultipleCreate begin
JVMSHRC010I Shared cache "OSCTest1" is destroyed
JVMSHRC010I Shared cache "OSCTest1" is destroyed
testMultipleCreate: PASS
testConstructor begin
JVMSHRC659E An error has occurred while opening shared memory
JVMSHRC336E Port layer error code = 1
JVMSHRC337E Platform error message: The specified module could not be found
JVMSHRC662I Error recovery: destroyed semaphore set associated with shared class cache.
JVMSHRC680E Error recovery failure: Failed to remove the semaphore set control file C290M4F0A32_testConstructor_G41L00 associated with shared class cache.
JVMSHRC336E Port layer error code = 17

An unhandled error (4) has occurred.
J9Generic_Signal_Number=00000004
ExceptionCode=c0000005
ExceptionAddress=71F7BFE0
ContextFlags=0001007f
Handler1=01036450
Handler2=71F755D0
InaccessibleReadAddress=00000013
EDI=0053E280
ESI=00000013
EAX=FFFFFFFF
EBX=00000000
ECX=00000014
EDX=FFFFFFFF
EIP=71F7BFE0
ESP=0053E1C8
EBP=FFFFFFFF
EFLAGS=00210246
Module=F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1\openjdkbinary\j2sdk-image\jre\bin\default\J9PRT29.dll
Module_base_address=71F60000
Offset_in_DLL=0001bfe0
JVMDUMP039I Processing dump event "abort", detail "" at 2021/02/07 22:34:56 - please wait.
JVMDUMP032I JVM requested System dump using 'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1\openjdk-tests\TKG\output_16127567165590\shrtest_win_SE80_0\core.20210207.223456.2548.0001.dmp' in response to an event
JVMDUMP010I System dump written to F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1\openjdk-tests\TKG\output_16127567165590\shrtest_win_SE80_0\core.20210207.223456.2548.0001.dmp
JVMDUMP032I JVM requested Java dump using 'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1\openjdk-tests\TKG\output_16127567165590\shrtest_win_SE80_0\javacore.20210207.223456.2548.0002.txt' in response to an event
JVMDUMP010I Java dump written to F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1\openjdk-tests\TKG\output_16127567165590\shrtest_win_SE80_0\javacore.20210207.223456.2548.0002.txt
JVMDUMP032I JVM requested Snap dump using 'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1\openjdk-tests\TKG\output_16127567165590\shrtest_win_SE80_0\Snap.20210207.223456.2548.0003.trc' in response to an event
JVMDUMP010I Snap dump written to F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1\openjdk-tests\TKG\output_16127567165590\shrtest_win_SE80_0\Snap.20210207.223456.2548.0003.trc
JVMDUMP032I JVM requested JIT dump using 'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1\openjdk-tests\TKG\output_16127567165590\shrtest_win_SE80_0\jitdump.20210207.223456.2548.0004.dmp' in response to an event
JVMDUMP010I JIT dump written to F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1\openjdk-tests\TKG\output_16127567165590\shrtest_win_SE80_0\jitdump.20210207.223456.2548.0004.dmp
JVMDUMP013I Processed dump event "abort", detail "".
```

### PR DESCRIPTION
**Pull request by hangshao0**
The same as Unix implementation, in j9shmem_open() and
j9shsem_deprecated_open() controlFileStatus should be memset to 0 on
Windows.

Closes #11908 
Closes #11843

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

File: runtime/port/win32/j9shmem.c [hunk 1]
```diff
@@ -90,6 +90,10 @@ j9shmem_open(struct J9PortLibrary *portLibrary, const char* cacheDirName, uintpt
 		Trc_PRT_shmem_j9shmem_open_ExitNullCacheDirName();
 		return J9PORT_ERROR_SHMEM_OPFAILED;
 	}
+	
+	if (NULL != controlFileStatus) {
+		memset(controlFileStatus, 0, sizeof(J9ControlFileStatus));
```
Comment (pshipton) [inline runtime/port/win32/j9shmem.c:95]: Technically, this should be done before the `return J9PORT_ERROR_SHMEM_OPFAILED` above.

Comment (hangshao0) [reply runtime/port/win32/j9shmem.c]: Updated.

**Comment by pshipton** [comment]
jenkins compile win32 jdk8

File: runtime/port/win32/j9shmem.c (hunk 1 above)
Comment (pshipton) [reply runtime/port/win32/j9shmem.c]: We should update Unix as well, but that can be done in a separate PR.

**Review by pshipton — APPROVED** [review]

File: runtime/port/win32/j9shmem.c (hunk 1 above)
Comment (hangshao0) [reply runtime/port/win32/j9shmem.c]: > We should update Unix as well, but that can be done in a separate PR.

PR: https://github.com/eclipse/openj9/pull/12003
