### PR TITLE
Fix withField access check

### LINKED ISSUE #11084: ValueTypes: Withfeld instruction disallows access to private final in nest member
The resolution with withfield uses `J9_RESOLVE_FLAG_WITH_FIELD` as well as `J9_RESOLVE_FLAG_FIELD_SETTER`. The field setter flags follow the final field rules described  <a href="https://docs.oracle.com/javase/specs/jvms/se15/html/jvms-6.html#jvms-6.5.putfield">here </a>. 

`Otherwise, if the resolved field is final, it must be declared in the current class, and the instruction must occur in an instance initialization method of the current class. Otherwise, an IllegalAccessError is thrown.`
 
Withfield however must follow these rules:

`Otherwise, if the resolved field is not declared by a class that belongs to the same nest as the current class, any of the exceptions pertaining to the nestmate test (5.4.4) may be thrown.`

We need to modify the withfield <a href="https://github.com/eclipse/openj9/blob/master/runtime/vm/BytecodeInterpreter.hpp#L8662">bytecode</a> to pass the withfield resolve flag and not the field setter flag. The resolve code `resolveInstanceFieldRef` needs to be updated to perform nest check.

### PR DESCRIPTION
**Pull request by hangshao0**
1. Remove J9_RESOLVE_FLAG_FIELD_SETTER on withField.
2. Add nestmate check for withField.

Fixes #11084

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

File: runtime/vm/resolvesupport.cpp [hunk 1]
```diff
@@ -931,6 +931,7 @@ resolveInstanceFieldRefInto(J9VMThread *vmStruct, J9Method *method, J9ConstantPo
 		J9Class *flattenableClass = NULL;
 		J9FlattenedClassCache *flattenedClassCache = NULL;
 #endif		
+		bool isWithField = false;
```
Comment (gacholio) [inline runtime/vm/resolvesupport.cpp:934]: C++ file, so you can declare the variable when it is assigned below.

File: runtime/vm/BytecodeInterpreter.hpp [hunk 2]
```diff
@@ -8674,12 +8674,12 @@ class INTERPRETER_CLASS
 		 * a field ref as resolved if only one of the two values has been set (by
 		 * another thread that is in the middle of a resolve).
 		 */
-		if (J9_UNEXPECTED((flags <= valueOffset) || J9_ARE_NO_BITS_SET(flags, J9FieldFlagPutResolved))) {
```
Comment (tajila) [inline runtime/vm/BytecodeInterpreter.hpp:8677]: why is the `J9FieldFlagPutResolved` check removed

Comment (tajila) [reply runtime/vm/BytecodeInterpreter.hpp:8677]: ah I see, its only set with the `J9_RESOLVE_FLAG_FIELD_SETTER` flag

**Comment by tajila** [comment]
https://github.com/eclipse/openj9/pull/11339/files#diff-10049424d527282d92c9d8c1dc92d1b1eda68629b22c9982e9d32beba898966eR1077-R1078

That barrier is no longer valid since the offsets are written to the FCC during class linkage

File: runtime/vm/resolvesupport.cpp (hunk 1 above)
Comment (hangshao0) [reply runtime/vm/resolvesupport.cpp:934]: If I move the declaration to where it is assigned below, I get a compilation error. There is a `goto illegalAccess` before the assignment.

File: runtime/vm/BytecodeInterpreter.hpp (hunk 2 above)
Comment (tajila) [reply runtime/vm/BytecodeInterpreter.hpp:8677]: Minor: we can start using `!VM_VMHelpers::instanceFieldRefIsResolved(flags, valueOffset)` for this check

**Comment by gacholio** [comment]
@tajila I don't see what your previous comment refers to. Can you be more specific (better yet, annotate the code in place)?

**Comment by tajila** [comment]
> I don't see what your previous comment refers to. Can you be more specific (better yet, annotate the code in place)?

I'm referring to this code

```
						modifiers |= J9FieldFlagFlattened;
						valueOffset = (UDATA) J9_VM_FCC_ENTRY_FROM_FCC(flattenedClassCache, fieldIndex);
						/* offset must be written to flattenedClassCache before fieldref is marked as resolved */
						issueWriteBarrier();
```

File: runtime/vm/resolvesupport.cpp (hunk 1 above)
Comment (gacholio) [reply runtime/vm/resolvesupport.cpp:934]: OK.

**Comment by gacholio** [comment]
I'm not convinced - the line just above what you pasted does set the FCC entry.

**Comment by tajila** [comment]
> I'm not convinced - the line just above what you pasted does set the FCC entry.

Basically `fccEntryFieldNotSet` is always false now. So we never actually call the `instanceFieldOffsetWithSourceClass` call. 

It doesn't have to be addressed here.

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins test sanity,extended xlinuxval jdknext

File: runtime/vm/BytecodeInterpreter.hpp (hunk 2 above)
Comment (hangshao0) [reply runtime/vm/BytecodeInterpreter.hpp:8677]: Updated.

**Comment by tajila** [comment]
jenkins test sanity,extended xlinuxval jdknext

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8
