### PR TITLE
 DDR: add support for OSX core files

### LINKED ISSUE #3366: DDR Tests do not compile with OpenJ9 OSX builds
From https://ci.adoptopenjdk.net/view/Test_weekly/job/openjdk11_j9_functionaltest_x86-64_macos/4/consoleFull

00:08:49     [javac] /Users/jenkins/workspace/openjdk11_j9_functionaltest_x86-64_macos/openjdk-tests/functional/DDR_Test/src/j9vm/test/ddrext/AutoRun.java:60: error: package com.ibm.j9ddr.tools.ddrinteractive does not exist
00:08:49     [javac] import com.ibm.j9ddr.tools.ddrinteractive.Context;
00:08:49     [javac]         
...

For developer builds I have been deleting the directory, to workaround this, but we should address it properly as we proceed.

### LINKED ISSUE #3444: MacOS: DDR: No Image sources found for dump file
To reproduce:
Create a dump file, e.g. `java -Xdump:system:events=vmstop HelloWorld`, then try to open it:
`jdmpview -core core.20181025.090255.99913.0001.dmp`.

```
DTFJView version 4.29.5, using DTFJ version 1.12.29003
Loading image from DTFJ...

Could not load dump file and/or could not load XML file: No Image sources were found for /some/random/directory/core.20181025.090255.99913.0001.dmp
```

### LINKED ISSUE #3483: DDR support on OSX
Work to get DDR working on OSX should be made up of the following broad tasks:

- [x] Get OMR's ddrgen working (PRs: https://github.com/eclipse/openj9/pull/3489 and https://github.com/eclipse/omr/pull/3136)
- [ ] Add a core file reader for Mach core files (#3444)
- [ ] Enable and get DDR tests working (#3366)
- [x] Enable DDR by default on OSX (ibmruntimes/openj9-openjdk-jdk8#225, ibmruntimes/openj9-openjdk-jdk11#82, ibmruntimes/openj9-openjdk-jdk12#1, ibmruntimes/openj9-openjdk-jdk#61)

Part of https://github.com/eclipse/openj9/issues/378

### PR DESCRIPTION
**Pull request by mikezhang1234567890**
Added a core reader for reading OSX Mach-O core files.
Also re-enables DDR tests for OSX.

Resolves #3444, resolves #3366, resolves #3483

Signed-off-by: Mike Zhang <mike.h.zhang@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Please fix the copyright check problems 
https://ci.eclipse.org/openj9/job/PullRequest-CopyrightCheck-OpenJ9/13521/

**Comment by pshipton** [comment]
jenkins test sanity osx jdk11

**Comment by pshipton** [comment]
jenkins test extended osx jdk11

File: debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/BuildVersionCommand.java [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+	public static class Version {
+		int major;
+		int minor;
+		int patch;
+
+		public Version(int encoding) {
+			int mask;
+			for (int i = 8; i > 4; i--) {
+				mask = 0xf << (i * 4);
+				major = major * 10 + ((encoding & mask) >>> (i * 4));
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/BuildVersionCommand.java]: If you apply the mask after shifting, it becomes a constant (`0xf`):
> 	major = major * 10 + (((encoding >>> (i * 4)) & 0xf);

**Comment by pshipton** [comment]
@mikezhang1234567890 please try signing the eca again, it has worked for others today.

**Comment by DanHeidinga** [comment]
@keithc-ca Can you review this again?  It looks like Mike has updated it

**Comment by keithc-ca** [comment]
Looking at this now.

File: debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/SourceVersionCommand.java [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+		return this;
+	}
+
+	public String getVersionString()
+	{
+		int v1 = (int)((0xFFFFFF0000000000L & version) >>> 40);
+		int v2 = (int)((0xFFC0000000L & version) >>> 30);
+		int v3 = (int)((0x3FF00000L & version) >>> 20);
+		int v4 = (int)((0xFFC00L & version) >>> 10);
+		int v5 = (int)(0x3FFL & version);
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/SourceVersionCommand.java]: These masks can all be small if the shifts are done first.

File: debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/ThreadCommand.java [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+		public static long readLong(byte[] data, int start)
+		{
+			return (0xFF00000000000000L & (((long) data[start + 7]) << 56))
+					| (0x00FF000000000000L & (((long) data[start + 6]) << 48))
+					| (0x0000FF0000000000L & (((long) data[start + 5]) << 40))
+					| (0x000000FF00000000L & (((long) data[start + 4]) << 32))
+					| (0x00000000FF000000L & (((long) data[start + 3]) << 24))
+					| (0x0000000000FF0000L & (((long) data[start + 2]) << 16))
+					| (0x000000000000FF00L & (((long) data[start + 1]) << 8))
+					| (0x00000000000000FFL & (data[start + 0]));
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/ThreadCommand.java]: Is this and similar functions below not affected by the byte-order of the core file?

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/VMRegMapHelper.java [hunk 4]
```diff
@@ -83,30 +83,33 @@ public static void printRegisters(J9JavaVMPointer vm, int level, PrintStream out
...
 		case ZOS:
 			if (is64BitPlatform) {
 				printRegistersForZOS64BitS390(level, out);
 			} else {
 				printRegistersForZOS32BitS390(level, out);
 			}
 			break;
-		
+
+		case OSX:
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/VMRegMapHelper.java]: The case labels were in alphabetical order: can you retain that order, please?

File: debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java [hunk 5]
```diff
@@ -0,0 +1,505 @@
...
+		long streamOffset;
+
+		public MachFile64() {}
+
+		public Collection<? extends IMemorySource> getMemoryRangesWithOffset(long coreOffset) throws IOException
+		{
+			List<IMemorySource> ranges = new LinkedList<IMemorySource>();
+			for (SegmentCommand64 segment : segments) {
+				if (segment.fileSize != 0) {
+					if ((MachoDumpReader.this._fileReader.length() < 0) || (streamOffset + segment.fileOffset + segment.fileSize < MachoDumpReader.this._fileReader.length())) {
```
[the remark this answers is not in the document]
Comment (mikezhang1234567890) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java]: The first condition is just if the length is unknown. `length()` returns -1 if it can't be determined.

[the remark this answers is not in the document]
Comment (keithc-ca) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java]: Can you add a comment explaining that?

File: debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/SourceVersionCommand.java [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+	public SourceVersionCommand readCommand(ImageInputStream stream, long streamSegmentOffset) throws IOException
+	{
+		super.readCommand(stream, streamSegmentOffset);
+		version = stream.readLong();
+		return this;
+	}
+
+	public String getVersionString()
+	{
+		int v1 = (int)(0x3FFL & (version >>> 40));
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/SourceVersionCommand.java]: The previous version of this was:
>		int v1 = (int)((0xFFFFFF0000000000L & version) >>> 40);

This is not equivalent. I think you want (to select the same number (24) of bits):
>		int v1 = ((int)(version >>> 40)) & 0xFFFFFF;

File: debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java [hunk 7]
```diff
@@ -0,0 +1,505 @@
...
+	}
+
+	public class OSXThread implements IOSThread
+	{
+
+		private final Map<String, Number> registers;
+		private final Properties properties;
+		private final long threadId;
+		private final List<IMemoryRange> memoryRanges = new LinkedList<IMemoryRange>();
+		private final List<IOSStackFrame> stackFrames = new LinkedList<IOSStackFrame>();
```
[the remark this answers is not in the document]
Comment (keithc-ca) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java]: Not all of these have been addressed, but it can wait for a future (cleanup) pull request.

File: debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/OSXProcessAddressSpace.java [hunk 8]
```diff
@@ -0,0 +1,165 @@
...
+		}
+		
+		int stringLength = (int)(ptr - nameAddress);
+		
+		byte[] stringBuffer = new byte[stringLength];
+		
+		getBytesAt(nameAddress, stringBuffer);
+		
+		try {
+			return new String(stringBuffer, "ASCII");
```
[the remark this answers is not in the document]
Comment (keithc-ca) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/OSXProcessAddressSpace.java]: Please also fix `LoadCommand` and `SymtabCommand`.

File: debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java [hunk 9]
```diff
@@ -0,0 +1,510 @@
...
+							break;
+					}
+				}
+			} catch (EOFException e) {
+				// nothing to process if we have a truncated file
+			}
+		}
+		for (LoadCommand lc : dumpFile.otherLoads) {
+			if (lc instanceof ThreadCommand) {
+				dumpFile.threads = (ThreadCommand) lc;
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java]: Please open an issue to improve this to handle core files with more than one thread.

**Comment by keithc-ca** [comment]
Jenkins test extended osx,zlinux jdk11

**Comment by pshipton** [comment]
Jenkins test sanity osx,zlinux jdk11

**Comment by pshipton** [comment]
@keithc-ca approved and the test has passed.

**Comment by keithc-ca** [comment]
@pshipton Thanks for merging.

**Comment by pshipton** [comment]
jkd8 DDR tests are failing
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/104
```
 [ERR] _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
 [ERR] 2019-03-23 02:03:35.362 jdmpview[37189:54586460] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
```

**Comment by keithc-ca** [comment]
Maybe those tests need `-XstartOnFirstThread` on OSX?

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/278 seems to have fixed jdmpview, but the two testDDRExt_* tests must not be using jdmpview and will need to be fixed separately.
