### PR TITLE
Fix the exception for mismatched number of args

### LINKED ISSUE #6729: JITServer exception/assert: Arity mismatch: Expected 1 args to unpack but got 9-tuple
It looks to me if this exception or assert is generated at the end of the compilation, it could be false positive. 

Two issues here: 
1. The error message might not be accurate. The code checks the received message size against the number of args to be expected. It'd be more accurate to say `"Received " + std::to_string(message->data_size()) + " args to unpack but expect " + std::to_string(sizeof...(Args)) + "-tuple");`

```C++
   template <typename... Args>
   std::tuple<Args...> getArgs(const AnyData *message)
      {
      if (sizeof...(Args) != message->data_size())
         throw StreamArityMismatch("Expected " + std::to_string(message->data_size()) + " args to unpack but got " + std::to_string(sizeof...(Args)) + "-tuple");
      return GetArgs<Args...>::getArgs(message, 0);
      }
```

2. It could be a false positive for the end of compilation messages. If there is a compilation failure on the server side. `finishCompilation()` with `MessageType::compilationCode` will not send tuple back to the client but send only the statusCode. 

```
=== Server === 
#FAILURE:  <EARLY TRANSLATION FAILURE: compilation aborted>finishCompilation: statusCode 55, arguments size 0

=== Client ===
#9  <signal handler called>
#10 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#11 0x00007ffff73e8801 in __GI_abort () at abort.c:79
#12 0x00007ffff73d839a in __assert_fail_base (fmt=0x7ffff755f7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fffef776755 "0", 
    file=file@entry=0x7fffef776700 "/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/infra/Assert.cpp", line=line@entry=69, 
    function=function@entry=0x7fffef7767d0 <TR::trap()::__PRETTY_FUNCTION__> "void TR::trap()") at assert.c:92
#13 0x00007ffff73d8412 in __GI___assert_fail (assertion=0x7fffef776755 "0", 
    file=0x7fffef776700 "/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/infra/Assert.cpp", line=69, 
    function=0x7fffef7767d0 <TR::trap()::__PRETTY_FUNCTION__> "void TR::trap()") at assert.c:101
#14 0x00007fffeefb3d45 in TR::trap () at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/infra/Assert.cpp:69
#15 0x00007fffeefb41e7 in TR::fatal_assertion (file=0x7fffef657438 "/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/net/StreamExceptions.hpp", line=127, 
    condition=0x7fffef657117 "false", format=0x7fffef6574c4 "Arity mismatch: %s") at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/infra/Assert.cpp:160
#16 0x00007fffeefb411c in TR::assertion (file=0x7fffef657438 "/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/net/StreamExceptions.hpp", line=127, 
    condition=0x7fffef657117 "false", format=0x7fffef6574c4 "Arity mismatch: %s") at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/infra/Assert.cpp:151
#17 0x00007fffee9a5aa6 in JITServer::StreamArityMismatch::StreamArityMismatch (this=0x7fffd0029870, message=..., __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/net/StreamExceptions.hpp:127
#18 0x00007fffeebf6b86 in JITServer::getArgs<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::tuple<std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, std::vector<TR_ResolvedMethod*, std::allocator<TR_ResolvedMethod*> >, std::vector<TR_VirtualGuardSite, std::allocator<TR_VirtualGuardSite> >, std::vector<std::tuple<VirtualGuardInfoForCHTable, std::vector<TR_VirtualGuardSite, std::allocator<TR_VirtualGuardSite> >, std::vector<VirtualGuardInfoForCHTable, std::allocator<VirtualGuardInfoForCHTable> > >, std::allocator<std::tuple<VirtualGuardInfoForCHTable, std::vector<TR_VirtualGuardSite, std::allocator<TR_VirtualGuardSite> >, std::vector<VirtualGuardInfoForCHTable, std::allocator<VirtualGuardInfoForCHTable> > > > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, unsigned char*>, std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<TR_ResolvedJ9Method*, std::allocator<TR_ResolvedJ9Method*> >, TR_OptimizationPlan> (message=0x7fffd000fee0) at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/net/ProtobufTypeConvert.hpp:283
#19 0x00007fffeebe5f9e in JITServer::ClientStream::getRecvData<unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::tuple<std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, std::vector<TR_ResolvedMethod*, std::allocator<TR_ResolvedMethod*> >, std::vector<TR_VirtualGuardSite, std::allocator<TR_VirtualGuardSite> >, std::vector<std::tuple<VirtualGuardInfoForCHTable, std::vector<TR_VirtualGuardSite, std::allocator<TR_VirtualGuardSite> >, std::vector<VirtualGuardInfoForCHTable, std::allocator<VirtualGuardInfoForCHTable> > >, std::allocator<std::tuple<VirtualGuardInfoForCHTable, std::vector<TR_VirtualGuardSite, std::allocator<TR_VirtualGuardSite> >, std::vector<VirtualGuardInfoForCHTable, std::allocator<VirtualGuardInfoForCHTable> > > > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocat--Type <RET> for more, q to quit, c to continue without paging--
or<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, unsigned char*>, std::vector<TR_OpaqueClassBlock*, std::allocator<TR_OpaqueClassBlock*> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<TR_ResolvedJ9Method*, std::allocator<TR_ResolvedJ9Method*> >, TR_OptimizationPlan> (this=0x7fffec449af8) at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/net/ClientStream.hpp:138
#20 0x00007fffeebcdc5d in remoteCompile (vmThread=0x637e00, compiler=0x7fff82000000, compilee=0x7fffeb1c9938, method=0x66bc00, details=..., compInfoPT=0x7fffec3e1970)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/JITaaSCompilationThread.cpp:2674
#21 0x00007fffee9c2846 in TR::CompilationInfoPerThreadBase::compile (this=0x7fffec3e1970, vmThread=0x637e00, compiler=0x7fff82000000, compilee=0x7fffeb1c9938, vm=..., 
    optimizationPlan=0x7fffec491870, scratchSegmentProvider=...) at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:8901
#22 0x00007fffee9c0a89 in TR::CompilationInfoPerThreadBase::wrappedCompile (portLib=0x7ffff63eb3a0 <j9portLibrary>, opaqueParameters=0x7fffeb1c96b0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:8403
#23 0x00007ffff5578d93 in omrsig_protect (portLibrary=0x7ffff63eb3a0 <j9portLibrary>, 
    fn=0x7fffee9be34a <TR::CompilationInfoPerThreadBase::wrappedCompile(J9PortLibrary*, void*)>, fn_arg=0x7fffeb1c96b0, 
    handler=0x7fffee9a93a8 <jitSignalHandler(J9PortLibrary*, U_32, void*, void*)>, handler_arg=0x637e00, flags=249, result=0x7fffeb1c9680) at ../../omr/port/unix/omrsignal.c:416
#24 0x00007fffee9bded5 in TR::CompilationInfoPerThreadBase::compile (this=0x7fffec3e1970, vmThread=0x637e00, entry=0x7ffff045c1c0, scratchSegmentProvider=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:7593
#25 0x00007fffee9b4689 in TR::CompilationInfoPerThread::processEntry (this=0x7fffec3e1970, entry=..., scratchSegmentProvider=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:4141
#26 0x00007fffee9b388d in TR::CompilationInfoPerThread::processEntries (this=0x7fffec3e1970)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:3847
#27 0x00007fffee9b312e in TR::CompilationInfoPerThread::run (this=0x7fffec3e1970)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:3717
#28 0x00007fffee9b2eea in protectedCompilationThreadProc (compInfoPT=0x7fffec3e1970)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:3660
#29 0x00007ffff5578d93 in omrsig_protect (portLibrary=0x7ffff63eb3a0 <j9portLibrary>, 
    fn=0x7fffee9b2d04 <protectedCompilationThreadProc(J9PortLibrary*, TR::CompilationInfoPerThread*)>, fn_arg=0x7fffec3e1970, handler=0x7ffff5c92400 <structuredSignalHandler>, 
    handler_arg=0x637e00, flags=506, result=0x7fffeb1cad98) at ../../omr/port/unix/omrsignal.c:416
#30 0x00007fffee9b2ca8 in compilationThreadProc (entryarg=0x7fffec3e1970) at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:3565
#31 0x00007ffff59e62c6 in thread_wrapper (arg=0x7ffff00d1620) at ../omr/thread/common/omrthread.c:1605
#32 0x00007ffff7bbd6db in start_thread (arg=0x7fffeb1cd700) at pthread_create.c:463
#33 0x00007ffff74c988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 

(gdb) f 20
#20 0x00007fffeebcdc5d in remoteCompile (vmThread=0x637e00, compiler=0x7fff82000000, compilee=0x7fffeb1c9938, method=0x66bc00, details=..., compInfoPT=0x7fffec3e1970)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/control/JITaaSCompilationThread.cpp:2674
2674	                                      std::string, std::string, std::vector<TR_ResolvedJ9Method*>, TR_OptimizationPlan>();
(gdb) list -
2669	         comp->failCompilation<TR::CompilationInterrupted>("Compilation interrupted in remoteCompile");
2670	         }
2671	
2672	      while(!handleServerMessage(client, compiler->fej9vm()));
2673	      auto recv = client->getRecvData<uint32_t, std::string, std::string, CHTableCommitData, std::vector<TR_OpaqueClassBlock*>,
2674	                                      std::string, std::string, std::vector<TR_ResolvedJ9Method*>, TR_OptimizationPlan>();
```

### PR DESCRIPTION
**Pull request by a7ehuo**
There are two issues with the exception
`Arity mismatch: Expected 1 args to unpack but got 9-tuple`:
1. The error message was misleading. What it should say is
`Received 1 args to unpack but expect 9-tuple`.
2. If `statusCode` is not `compilationOK`, except for the statusCode,
the server does not send any argument to the client.
The argument mismatch exception should not be thrown in this case.

== Changes include ==
- Add a new message type `compilationFailure` to handle the error path case.
- Add a new API `writeError()` to `ServerStream` to send statusCode in
  `compilationFailure` message to client. `finishCompilation()` will no longer take
  `statusCode` since this API by default means `compilationOK`.
- Make `handleServerMessage()` local to JITaaSCompilationThread.cpp.
- Removed white trailing spaces in header files.

Fixes #6729

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

File: runtime/compiler/control/JITaaSCompilationThread.cpp [hunk 1]
```diff
@@ -252,7 +251,7 @@ bool handleServerMessage(JITServer::ClientStream *client, TR_J9VM *fe)
    uint8_t interruptReason = compInfoPT->compilationShouldBeInterrupted();
    if (interruptReason)
       {
-      if (response != MessageType::compilationCode)
+      if (response != MessageType::compilationEndCode)
```
Comment (mpirvu) [inline runtime/compiler/control/JITaaSCompilationThread.cpp]: Here we need both `compilationEndCode` and `compilationEndErrCode` because if the compilation finished with an error code it doesn't make sense to send another message to the server to request to interrupt the compilation.

File: runtime/compiler/control/JITaaSCompilationThread.cpp [hunk 2]
```diff
@@ -267,7 +266,8 @@ bool handleServerMessage(JITServer::ClientStream *client, TR_J9VM *fe)
    bool done = false;
```
Comment (mpirvu) [inline runtime/compiler/control/JITaaSCompilationThread.cpp]: I would move the line `serverMsgTypeCount[response] += 1;` up so that we can count all messages

File: runtime/compiler/control/JITaaSCompilationThread.cpp [hunk 3]
```diff
@@ -2664,23 +2664,35 @@ remoteCompile(
...
+         dataCacheStr = std::get<2>(recv);
+         chTableData = std::get<3>(recv);
+         classesThatShouldNotBeNewlyExtended = std::get<4>(recv);
+         logFileStr = std::get<5>(recv);
+         svmSymbolToIdStr = std::get<6>(recv);
+         resolvedMirrorMethodsPersistIPInfo = std::get<7>(recv);
+         modifiedOptPlan = std::get<8>(recv);
+         }
+      else
+         {
```
Comment (mpirvu) [inline runtime/compiler/control/JITaaSCompilationThread.cpp]: Please place an assert here that only a `compilationEndErrorCode` can happen here. This will catch future transgressions.

File: runtime/compiler/net/protos/compile.proto [hunk 4]
```diff
@@ -47,14 +47,15 @@ message AnyData
...
    {
-   compilationCode = 0;
-   mirrorResolvedJ9Method = 1;
-   get_params_to_construct_TR_j9method = 2;
-   getUnloadedClassRanges = 3;
-   compilationRequest = 4; // type used when client sends remote compilation requests
-   compilationInterrupted = 5; // type used when client informs the server to abort the remote compilation
-   clientSessionTerminate = 6; // type used when client process is about to terminate
-   connectionTerminate = 7; // type used when client informs the server to close the connection
+   compilationEndCode = 0;
```
Comment (mpirvu) [inline runtime/compiler/net/protos/compile.proto]: I cannot decide on these names. Originally we had `compilationCode` which meant that the server was sending the compiled code back (at least that's how I interpret it). Would it make sense to keep `compilationCode` and add `compilationFailure` or something like that?

File: runtime/compiler/control/JITaaSCompilationThread.cpp (hunk 2 above)
Comment (a7ehuo) [reply runtime/compiler/control/JITaaSCompilationThread.cpp]: Not sure I'm following. Move `serverMsgTypeCount[response] += 1;` after `   response = client->read();`?

Comment (mpirvu) [reply runtime/compiler/control/JITaaSCompilationThread.cpp]: yes. Otherwise the messages that are sent when the client detects an interruption are not counted

File: runtime/compiler/net/protos/compile.proto (hunk 4 above)
Comment (a7ehuo) [reply runtime/compiler/net/protos/compile.proto]: I see. Thought `compilationCode` was meant to use at the end of the compilation. Sending the compiled code back to the client makes sense for `compilationCode`. Will update `compilationEndErrCode` to  `compilationFailure`.

Comment (a7ehuo) [reply runtime/compiler/net/protos/compile.proto]: `compilationFailure` is already defined in `compilationErrorNames[]` in `rossa.cpp`. We could still define  `compilationFailure` as proto message type. Or to reduce confusion, how about `compilationErrors` ?

Comment (mpirvu) [reply runtime/compiler/net/protos/compile.proto]: If we always use it with `MessageType::` in front then there is no confusion.
Also, I saw some inclusion of rossa.h. Let me comment on that one as well

File: runtime/compiler/net/ServerStream.hpp [hunk 5]
```diff
@@ -23,19 +23,20 @@
 #ifndef SERVER_STREAM_H
 #define SERVER_STREAM_H
 
-#include <google/protobuf/io/zero_copy_stream_impl.h> 
+#include <google/protobuf/io/zero_copy_stream_impl.h>
 #include "net/ProtobufTypeConvert.hpp"
 #include "net/CommunicationStream.hpp"
 #include "env/VerboseLog.hpp"
 #include "control/Options.hpp"
+#include "control/rossa.h"
```
Comment (mpirvu) [inline runtime/compiler/net/ServerStream.hpp]: Why do we need rossa.h? Ideally the communication code should not include j9 files because we may want to move this to omr in the future.

Comment (a7ehuo) [reply runtime/compiler/net/ServerStream.hpp]: `statusCode` is checked in `finishCompilation()` as below to decide which message type to use: `compilationCode` or `compilationFailure`. `compilationOK` is defined in `TR_CompilationErrorCode` in `control/rossa.h`. We could check it against `0` instead of `compilationOK` but it'd be a risky assumption though. 
```C++
         if (compilationOK == statusCode)
```

Comment (harryyu1994) [reply runtime/compiler/net/ServerStream.hpp]: I think it would be better to add a messageType to `finishCompilation()` so that `compilationOK` doesn't need to be checked inside `finishCompilation()` thus avoiding the `rossa.h` file

Comment (mpirvu) [reply runtime/compiler/net/ServerStream.hpp]: Yeah, I was thinking too about the different API:
`void finishCompilation(T... args)` with no statusCode because implicitly it's going to be `compilationOK` and
`void writeError(uint32_t statusCode)` for error situations (the client has a writeError routine as well)

`finishCompilationSuccess` and `finishCompilationFailure` are good names too

Comment (a7ehuo) [reply runtime/compiler/net/ServerStream.hpp]: Thanks @harryyu1994, @mpirvu. Adding different APIs to handle the error path is a better choice.`finishCompilationSuccess` and `finishCompilationFailure` are good names. Adding `void writeError(uint32_t statusCode)` to `ServerStream` would make it more consistent with the `ClientStream` APIs. Will implement the latter.

**Comment by a7ehuo** [comment]
@mpirvu updated and ready for review. Thanks!

File: runtime/compiler/control/CompilationThread.cpp [hunk 6]
```diff
@@ -2033,7 +2033,7 @@ bool TR::CompilationInfo::shouldAbortCompilation(TR_MethodToBeCompiled *entry, T
 
    if (entry->_unloadedMethod) // method was unloaded while we were trying to compile it
       {
-      TR_ASSERT(entry->_compErrCode == compilationInterrupted, "if method was unloaded we must return we an error code of compilationInterrupted");
+      TR_ASSERT(entry->_compErrCode == compilationInterrupted, "Recevied error code %u, expect compilationInterrupted when the method was unloaded", entry->_compErrCode);
```
Comment (mpirvu) [inline runtime/compiler/control/CompilationThread.cpp]: Small typo: Recevied -> Received

Comment (a7ehuo) [reply runtime/compiler/control/CompilationThread.cpp]: My bad. Updated and ready for review. Thanks!

**Comment by mpirvu** [comment]
@a7ehuo Could you please resolve conflicts, so that I can start testing? Thanks

**Comment by a7ehuo** [comment]
@mpirvu Conflicts are resolved.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
The only failure is the known "cmdLineTester_gcsuballoctests_0", thus the PR is safe to merge.
