### PR TITLE
Fix NoSuchFieldError in SCC DDR command

### LINKED ISSUE #12357: Jdmpview from Java 8.0.6.26 does not work with system core file from Java 8.0.5.37
$ <path>/sdks/pap6480sr6fp26-20210216_01-sdk/bin/jdmpview -core core.20210401.233037.3628.0001.dmp

> context
Available contexts (* = currently selected context) :

Source : file:///.../core.20210401.233037.3628.0001.dmp.zip_unpack/core.20210401.233037.3628.0001.dmp
        *0 : PID: 3628 :
                JRE 1.8.0 Windows Server 2012 R2 amd64-64

> !shrc name
!j9sharedclassconfig 0x000000000E5974B0

Error executing DDR command !shrc name : null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:258)
        at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:169)
        at com.ibm.jvm.dtfjview.Session.execute(Session.java:811)
        at com.ibm.jvm.dtfjview.Session.execute(Session.java:765)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
        at com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:739)
        at com.ibm.jvm.dtfjview.Session.run(Session.java:663)
        at com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
        at com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/SH_CacheMap.__ccTailOffset_
        at com.ibm.j9ddr.vm29.pointer.generated.SH_CacheMapPointer._ccTail(SH_CacheMapPointer.java:321)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.ShrCCommand.dbgShrcReadConfig(ShrCCommand.java:1209)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.ShrCCommand.getSharedCacheMetadataStart(ShrCCommand.java:1311)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.ShrCCommand.run(ShrCCommand.java:105)
        at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
        at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
        at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
        at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
        at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
        ... 16 more

### PR DESCRIPTION
**Pull request by hangshao0**
Catch NoSuchFieldError when running on an old core where SH_CacheMap
does not have field _ccTail. Fall back to code before #6883 i.e. use
cacheMap._cc() to set compositeCacheImpl in this case.

Fixes #12357

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Are there any other places or any other fields that need to be fixed?

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java [hunk 1]
```diff
@@ -1202,9 +1202,14 @@ ShrcConfig dbgShrcReadConfig(J9SharedClassConfigPointer sharedClassConfig, Print
...
-					SH_CompositeCacheImplPointer compositeCacheImpl = cacheMap._ccTail();
-					for (int tmplayer = 0; tmplayer < layer; tmplayer++) {
-						compositeCacheImpl = compositeCacheImpl._previous();
+					SH_CompositeCacheImplPointer compositeCacheImpl = null;
+					try {
+						compositeCacheImpl = cacheMap._ccTail();
+						for (int tmplayer = 0; tmplayer < layer; tmplayer++) {
+							compositeCacheImpl = compositeCacheImpl._previous();
+						}
+					} catch (NoSuchFieldError e) {
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java:1211]: This is not sufficient. When accessing an older core file from an openj9 VM, the type `SH_CompositeCacheImplPointer` will be dynamically generated without the `_ccTail()` method. This either needs to catch `NoSuchMethodError` or key off some other feature of old core files to avoid the call.

**Review by keithc-ca — CHANGES_REQUESTED** [review]

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java (hunk 1 above)
Comment (hangshao0) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java]: Added code to catch `NoSuchMethodError`.

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java [hunk 2]
```diff
@@ -1202,9 +1202,14 @@ ShrcConfig dbgShrcReadConfig(J9SharedClassConfigPointer sharedClassConfig, Print
 					/*  _ccHead -------------> ccNext ---------> ccNext --------> ........---------> ccTail
 					 * (top layer)         (middle layer)     (middle layer)      ........         (layer 0)
 					 */
-					SH_CompositeCacheImplPointer compositeCacheImpl = cacheMap._ccTail();
-					for (int tmplayer = 0; tmplayer < layer; tmplayer++) {
-						compositeCacheImpl = compositeCacheImpl._previous();
+					SH_CompositeCacheImplPointer compositeCacheImpl = null;
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java:1205]: Please remove the unnecessary initialization to `null` (the java compiler will issue an error if it's not guaranteed to have a value before it's used).

Comment (hangshao0) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java]: Fixed.

**Comment by hangshao0** [comment]
> Are there any other places (no) or any other fields (I don't think so) that need to be fixed?

The new fields that I see used in DDR are `SH_CacheMap._ccTail, SH_CompositeCacheImpl._previous` and `J9SharedClassCacheDescriptor.previous`.  

`SH_CacheMap._ccTail, SH_CompositeCacheImpl._previous` are handled by this PR. `J9SharedClassCacheDescriptor.previous` are all protected by` if (topLayer > 0) `.

**Comment by keithc-ca** [comment]
Jenkins test sanity,extended zlinux jdk16

**Comment by pshipton** [comment]
Assuming the tests pass, we'll need a PR for the 0.26 release as well.

**Comment by hangshao0** [comment]
> we'll need a PR for the 0.26 release as well

https://github.com/eclipse/openj9/pull/12364/

**Review by keithc-ca — APPROVED** [review]
