### PR TITLE
Change TR_ASSERT_FATAL into failCompilation call in SymRefTab

### LINKED ISSUE #9416: VM build failure - VMState: 0x00050080 or 0x000501ff
Got this on https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/573 (`build-macstadium-macos1014-1`)
```
* For target support_jmods_java.compiler.jmod:
Assertion failed at /Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/build/macosx-x86_64-normal-server-release/vm/compiler/../compiler/compile/J9SymbolReferenceTable.cpp:811: containingClass != NULL
VMState: 0x00050080
	failed to get defining class of field ref cpIndex=35 in owning method J9Method=0xc5e3660
compiling jdk/internal/org/objectweb/asm/ClassWriter.<init>(I)V at level: warm

JVMDUMP039I Processing dump event "abort", detail "" at 2020/04/30 00:59:05 - please wait.
JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/make/core.20200430.005905.52000.0001.dmp' in response to an event
JVMDUMP012E Error in System dump: The core file created by child process with pid = 52079 was not found. Expected to find core file with name "/cores/core.52079"
JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/make/javacore.20200430.005905.52000.0002.txt' in response to an event
JVMDUMP010I Java dump written to /Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/make/javacore.20200430.005905.52000.0002.txt
JVMDUMP032I JVM requested Snap dump using '/Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/make/Snap.20200430.005905.52000.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/make/Snap.20200430.005905.52000.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/make/jitdump.20200430.005905.52000.0004.dmp'
JVMDUMP010I JIT dump written to /Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/make/jitdump.20200430.005905.52000.0004.dmp
JVMDUMP013I Processed dump event "abort", detail "".

* All command lines available in /Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/build/macosx-x86_64-normal-server-release/make-support/failure-logs.
```
Access to the machine can be granted by opening an issue at https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues

### PR DESCRIPTION
**Pull request by Leonardo2718**
`findOrCreateShadowSymbol()` tries to reuse symrefs produced by `findOrFabricateShadowSymbol()` when the shadow corresponds to the same field. Detecting that the fields are in fact the same requires checking that the defining class is the same. Normally, the expectation is that if a cp field ref is resolved, then the cp ref pointing to the defining class must also be resolved. However, in #9416, it was discovered that this assumption does not hold in some cases. Under AOT, loading class data from the SCC using `findSharedData()` may fail, which is propagated to the JIT as a NULL defining class. In addition, if a class is redefined between the point where a field is looked up and where the defining class is looked, the latter may become NULL.

Since the code in question will not work correctly if the defining class is null, this PR tactically replaces the assert with a call to `failCompilation()`.

In addition, this PR also reverts commits that introduced temporary instrumentation that helped diagnose the issue.

Fixes #9416

### CODE REVIEW

**Review by dsouzai — APPROVED** [review]

**Comment by dsouzai** [comment]
jenkins test sanity xlinux jdk11

**Comment by JamesKingdon** [comment]
I'd just like to record my thanks for this work.

**Review by 0xdaryl — APPROVED** [review]

File: runtime/compiler/compile/J9SymbolReferenceTable.cpp [hunk 1]
```diff
@@ -897,59 +889,20 @@ J9::SymbolReferenceTable::findOrCreateShadowSymbol(TR::ResolvedMethodSymbol * ow
...
-            fromResolvedJ9Method,
-            comp()->getOption(TR_UseSymbolValidationManager));
-         }
-      else
-         {
-         TR_ASSERT_FATAL(
-            containingClass != NULL,
-            "failed to get defining class of field ref cpIndex=%d in owning method J9Method=%p",
+      if (containingClass == NULL)
+         comp()->failCompilation<TR::CompilationException>(
```
Comment (0xdaryl) [inline runtime/compiler/compile/J9SymbolReferenceTable.cpp:893]: Actually, I wonder if dropping in a comment here that is some variant of your commit message would be useful for documentation purposes:

>findOrCreateShadowSymbol() tries to reuse symrefs produced by findOrFabricateShadowSymbol() when the shadow corresponds to the same field. Detecting that the fields are in fact the same requires checking that the defining class is the same. Normally, the expectation is that if a cp field ref is resolved, then the cp ref pointing to the defining class must also be resolved. However, in #9416, it was discovered that this assumption does not hold in some cases. Under AOT, loading class data from the SCC using findSharedData() may fail, which is propagated to the JIT as a NULL defining class. In addition, if a class is redefined between the point where a field is looked up and where the defining class is looked, the latter may become NULL.
>
>Since the code in question will not work correctly if the defining class is null, this PR tactically replaces the assert with a call to failCompilation().

Comment (Leonardo2718) [reply runtime/compiler/compile/J9SymbolReferenceTable.cpp:903]: Fixed in force push.

Comment (0xdaryl) [reply runtime/compiler/compile/J9SymbolReferenceTable.cpp:903]: Thanks.  LGTM.

**Comment by dsouzai** [comment]
Merging because the tests prior to the force push passed, and the force push only added comments.
