### PR TITLE
Set the maximum direct byte buffer memory based on heap size

### LINKED ISSUE #2604: Eclipse OpenJ9 VM: Java OutOfMemoryError encountered when more than roughly 67M of Direct Byte Buffers are allocated.
Per J9 documentation (https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/xxmaxdirectmemorysize.html), we were under the impression that the amount of memory reserved for Direct Byte Buffers is dynamically expanded from a "soft" limit of 64MB. We are not finding this in practice. When our application has allocated roughly 67M of direct memory we see the following exception:

java.lang.OutOfMemoryError: Direct buffer memory
at java.nio.Bits.reserveMemory(Bits.java:703) ~[?:1.8.0_181]
at java.nio.DirectByteBuffer.(DirectByteBuffer.java:126) ~[?:1.8.0_181]
at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[?:1.8.0_181]

We are using the option -XX:MaxDirectMemorySize=512m to work around the issue.

Note that we encountered this while migrating from a stable application that has been using a HotSpot VM. This issue does not occur when using a HotSpot VM. We have encountered this using recent builds for Windows (64 and 32 bit) as well as Linux x64.

I can also recreate this issue using a very simple test program which simply allocates direct byte buffers:

    byte[] byteData = new byte[1024];
    Arrays.fill(byteData,(byte)1);
    ByteBuffer[] bbuffs = new ByteBuffer[70000];
    for (int i=0;i<70000;i++)
    {
        System.out.println("direct mem allocation: " + i * 1024);
        bbuffs[i] = ByteBuffer.allocateDirect(1024);
        bbuffs[i].put(byteData);
    }

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Fixes #2604

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
@gacholio would you kindly review? I have run a personal build on Windows and Linux PPC.  Compilations succeeded, sanity tests are in progress.

**Comment by pdbain-ibm** [comment]
Fixes https://github.com/eclipse/openj9/issues/2604

File: runtime/jcl/common/system.c [hunk 1]
```diff
@@ -356,13 +357,30 @@ jobject getPropertyList(JNIEnv *env)
 		}
 		strings[propIndex++] = !usernameAlloc || result ? "unknown" : usernameAlloc;
 	}
-
 #undef USERNAME_LENGTH
 
+#define MAX_DIRECTMEM_SIZE_STRING 16
```
Comment (gacholio) [inline runtime/jcl/common/system.c]: For a small constant buffer, why not put this in a local char[]?

File: runtime/jcl/common/system.c [hunk 2]
```diff
@@ -356,13 +357,30 @@ jobject getPropertyList(JNIEnv *env)
...
+	/* Set the maximum direct byte buffer allocation amount */
+	maxDirectMemAlloc = jclmem_allocate_memory(env, MAX_DIRECTMEM_SIZE_STRING);
+	if (NULL != maxDirectMemAlloc) {
+		UDATA heapSize = javaVM->memoryManagerFunctions->j9gc_get_maximum_heap_size(javaVM);
+		/* allow up to 7/8 of the heap to be direct byte buffers */
+		UDATA directMemoryMax = heapSize - (heapSize/8);
```
Comment (gacholio) [inline runtime/jcl/common/system.c]: Spaces around the /

**Comment by fjeremic** [comment]
@pdbain-ibm FYI if you add the "Fixes #2604" to your PR description GitHub will automatically close the corresponding issue when this PR is merged [1]. I've amended the PR for you and removed the comment. Hope that is ok with you!

[1] https://help.github.com/articles/closing-issues-using-keywords/

File: runtime/jcl/common/system.c (hunk 2 above)
Comment (pdbain-ibm) [reply runtime/jcl/common/system.c]: Fixed.

**Comment by pdbain-ibm** [comment]
@gacholio Updated and tested manually on Linux x86.

File: runtime/jcl/common/system.c [hunk 3]
```diff
@@ -356,11 +358,23 @@ jobject getPropertyList(JNIEnv *env)
 		}
 		strings[propIndex++] = !usernameAlloc || result ? "unknown" : usernameAlloc;
 	}
-
 #undef USERNAME_LENGTH
 
+	/* Set the maximum direct byte buffer allocation amount */
+
+	UDATA heapSize = javaVM->memoryManagerFunctions->j9gc_get_maximum_heap_size(javaVM);
```
Comment (gacholio) [inline runtime/jcl/common/system.c]: This won't compile on various platforms (.c file, not .cpp).

Comment (pdbain-ibm) [reply runtime/jcl/common/system.c]: Sad but true.  Fixed.

File: runtime/jcl/common/system.c [hunk 4]
```diff
@@ -356,11 +360,23 @@ jobject getPropertyList(JNIEnv *env)
...
+	/* Set the maximum direct byte buffer allocation amount */
+
+	heapSize = javaVM->memoryManagerFunctions->j9gc_get_maximum_heap_size(javaVM);
+	/* allow up to 7/8 of the heap to be direct byte buffers */
+	directMemoryMax = heapSize - (heapSize / 8);
+	/* this property is consumed by java.nio.Bits */
+	strings[propIndex] = "sun.nio.MaxDirectMemorySize";
+	propIndex += 1;
+	j9str_printf(PORTLIB, maxDirectMemAlloc,
+			sizeof(maxDirectMemAlloc) / sizeof(maxDirectMemAlloc[0]), "%zu", directMemoryMax);
```
Comment (gacholio) [inline runtime/jcl/common/system.c]: Simple sizeof is sufficient here.

Comment (pdbain-ibm) [reply runtime/jcl/common/system.c]: Okay.  Done.

**Comment by gacholio** [comment]
jenkins test sanity win jdk8

File: runtime/jcl/common/system.c [hunk 5]
```diff
@@ -356,11 +360,22 @@ jobject getPropertyList(JNIEnv *env)
...
+
+	heapSize = javaVM->memoryManagerFunctions->j9gc_get_maximum_heap_size(javaVM);
+	/* allow up to 7/8 of the heap to be direct byte buffers */
+	directMemoryMax = heapSize - (heapSize / 8);
+	/* this property is consumed by java.nio.Bits */
+	strings[propIndex] = "sun.nio.MaxDirectMemorySize";
+	propIndex += 1;
+	j9str_printf(PORTLIB, maxDirectMemAlloc, sizeof(maxDirectMemAlloc)), "%zu", directMemoryMax);
+	strings[propIndex] = maxDirectMemAlloc;
+	propIndex += 1;
```
Comment (DanHeidinga) [inline runtime/jcl/common/system.c]: This can also be set by `-XX:MaxDirectMemorySize` command line option.  Search our code for `VMOPT_XXMAXDIRECTMEMORYSIZEEQUALS`.

Setting it here would override the user's setting.

Comment (DanHeidinga) [reply runtime/jcl/common/system.c]: See code in https://github.com/eclipse/openj9/blob/f1ade0f8f3baa4be78b00afa7ad499e67e196b30/runtime/util/vmargs.c#L1587-L1609 for where we set `sun.nio.MaxDirectMemorySize`

Comment (pdbain-ibm) [reply runtime/jcl/common/system.c]: ...and that code is executed before `Java_java_lang_System_getPropertyList`. It also run before the GC has parsed the memory settings. so I can't just call `j9gc_get_maximum_heap_size()`.

Comment (gacholio) [reply runtime/jcl/common/system.c]: The separation between the jvm and vm libraries is largely pointless today, so if moving the option parsing further in fixes things, I'd suggest that.

**Comment by pdbain-ibm** [comment]
Updated to handle both implicit and explicit setting.
Manual testing with various combinations of `-Xmx` and `-XX:MaxDirectMemorySize` :
```
c2a5915fb970-root:36$ ./jdk/bin/java -cp /team/pdbain/experimental/ -Xmx256m  -XX:MaxDirectMemorySize=10m dbb 2>&1 | tail
direct mem allocation: 8905600
direct mem allocation: 9715200
Exception in thread "main" java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.ByteBuffer.allocateDirect(java.base@10.0.2-internal/ByteBuffer.java:310)
	at dbb.main(dbb.java:39)
c2a5915fb970-root:37$ ./jdk/bin/java -cp /team/pdbain/experimental/ -Xmx256m  dbb 2>&1 | tail
direct mem allocation: 233974400
direct mem allocation: 234784000
Exception in thread "main" java.lang.OutOfMemoryError: Direct buffer memory
	at dbb.main(dbb.java:39)
c2a5915fb970-root:38$ ./jdk/bin/java -cp /team/pdbain/experimental/  dbb 2>&1 | tail
direct mem allocation: 1827267200
direct mem allocation: 1828076800
Exception in thread "main" java.lang.OutOfMemoryError: Direct buffer memory
	at dbb.main(dbb.java:39)
```

Personal build on Linux and Windows in progress.

**Comment by pdbain-ibm** [comment]
Windows and linux compilation successful, Windows sanity test in progress.  Would a committer kindly run a pull request build?  Thank you.

File: runtime/jcl/common/system.c [hunk 6]
```diff
@@ -357,10 +357,28 @@ jobject getPropertyList(JNIEnv *env)
...
 	}
 
-#undef USERNAME_LENGTH
+#if defined(OPENJ9_BUILD)
+	{
+		/* buffer to hold the size of the maximum direct byte buffer allocations */
+		char maxDirectMemBuff[24];
+		/* Set the maximum direct byte buffer allocation amount if it has not been set manually */
+		if ((UDATA) -1 == javaVM->directByteBufferMemoryMax) {
+
```
Comment (gacholio) [inline runtime/jcl/common/system.c]: Extra blank line?

**Comment by gacholio** [comment]
It looks like this has removed the ability to set the size in the internal builds.

File: runtime/jcl/common/system.c [hunk 7]
```diff
@@ -357,10 +357,37 @@ jobject getPropertyList(JNIEnv *env)
 		strings[propIndex++] = !usernameAlloc || result ? "unknown" : usernameAlloc;
 	}
 
-#undef USERNAME_LENGTH
+	{
+		/* buffer to hold the size of the maximum direct byte buffer allocations */
+		char maxDirectMemBuff[24];
+#if defined(OPENJ9_BUILD)
```
Comment (gacholio) [inline runtime/jcl/common/system.c]: Rather than duplicating the code here, would it be better to ifdef around the initial -1 check, then do the -1 check again outside the ifdef?

```ifdef (open)
if (-1) set to 7/8
endifdef
if (!-1) set property
'''

**Comment by pdbain-ibm** [comment]
Updated per GAC's comments.

File: runtime/jcl/common/system.c [hunk 8]
```diff
@@ -357,10 +357,26 @@ jobject getPropertyList(JNIEnv *env)
 		strings[propIndex++] = !usernameAlloc || result ? "unknown" : usernameAlloc;
 	}
 
-#undef USERNAME_LENGTH
```
Comment (gacholio) [inline runtime/jcl/common/system.c]: Why was this line removed?

Comment (pdbain-ibm) [reply runtime/jcl/common/system.c]: Oops.  Line restored.

**Comment by gacholio** [comment]
Looks OK to me now. I'll assign to Dan for final review/merge.

**Comment by gacholio** [comment]
jenkins test sanity win jdk8

**Comment by pdbain-ibm** [comment]
@DanHeidinga any other comments?

File: runtime/util/vmargs.c [hunk 9]
```diff
@@ -1583,47 +1529,6 @@ addLauncherArgs(J9PortLibrary * portLib, JavaVMInitArgs *launcherArgs, UDATA lau
...
-			/*
-			 *  CMVC 149604 - check for errors in <size> portion of -XX:maxDirectMemorySize=<size>
-			 *                and add -Dsun.nio.MaxDirectMemorySize=<size in bytes>
-			 */
-
-			UDATA value = 0;
-			char *optname = VMOPT_XXMAXDIRECTMEMORYSIZEEQUALS;
-			IDATA returnCode = convertMemorySizeToBytes(portLib, optString + strlen(VMOPT_XXMAXDIRECTMEMORYSIZEEQUALS), &value);
-			if ( OPTION_OK == returnCode ) {
-				const size_t bufferSize = strlen(SUN_NIO_MAXDIRECTMEMORYSIZE_EQUALS) + 16; /* allocate 16 byt bytes for maximum length decimal string and null */
```
Comment (DanHeidinga) [inline runtime/util/vmargs.c]: Should the definition of `SUN_NIO_MAXDIRECTMEMORYSIZE_EQUALS` be removed as well?

Comment (pdbain-ibm) [reply runtime/util/vmargs.c]: Good idea.  Done.

**Comment by pdbain-ibm** [comment]
As for tests, we don't have existing tests for this feature, though I could adapt my existing test mentioned in 
https://github.com/eclipse/openj9/pull/2629#issuecomment-414344927 (attached) to make a sanity test.  The complication is the divergenet behaviour of IBM Java 8.  If you want me to do so, I will open an issue and work on it when I return from vacation.
[dbb.java.txt](https://github.com/eclipse/openj9/files/2314490/dbb.java.txt)

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk8
