### PR TITLE
Ensure enough space is allocated for the unique cache id

### LINKED ISSUE #9838: Race condition in SH_OSCache::generateCacheUniqueID
Java -version output
--------------------
```
openjdk version "11.0.8-internal" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8-internal+0-adhoc.keithc.jdk11)
Eclipse OpenJ9 VM (build master-b902818ac0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20200609_000000 (JIT enabled, AOT enabled)
OpenJ9   - b902818ac0
OMR      - b302c9642
JCL      - 72bf42d051a based on jdk-11.0.8+6)
```

Summary of problem
------------------
```
18:55:43.751 0xbe22a00   j9shr.1012   *   ** ASSERTION FAILED ** at /Users/keithc/space/openj9/jdk11/openj9/runtime/shared_common/OSCache.cpp:1402: ((bufLenrequired <= bufLen))
```

`SH_OSCache::generateCacheUniqueID()` is called twice: the first time with a `NULL` buffer (to determine the amount of space required) and a second time with a buffer which is of a size determined by the first call. Part of the computation involves the length of a file (see [line 1399](https://github.com/eclipse/openj9/blob/master/runtime/shared_common/OSCache.cpp#L1399)). It's entirely reasonable that another process using the same cache has increased the size of the file between those two calls, with the result that the second call fails with the assertion shown above.

### PR DESCRIPTION
**Pull request by keithc-ca**
Don't compute the cache unique id for layer 0
* fix `J9SHR_UNIQUE_CACHE_ID_BUFSIZE` - it was too small
* use a format with fixed field widths so the length of the unique id does not depend on things like the length of the lower layer cache file
* use return value of `generateCacheUniqueID()` instead of using `strlen()`

Fixes #9838.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
@hangshao0 pls review.

**Comment by hangshao0** [comment]
Was the assertion failure inside this call ?
https://github.com/eclipse/openj9/blob/308216d0237bbf7f7d9c9109a46bc66bf6046f5b/runtime/shared_common/CompositeCache.cpp#L1716

I guess what has been changed is not the file size. It is `metadataBytes` and/or `classesBytes`. Another JVM is storing new metadata or classes into this top layer cache.

**Comment by hangshao0** [comment]
`CacheUniqueID` is only useful for no-top layer caches, so I think we do not need to call this line for top layer cache (`_previous` == NULL means it is top layer).
https://github.com/eclipse/openj9/blob/master/runtime/shared_common/CompositeCache.cpp#L1716

It is possible that another process is changing the cache file size, but it is not JVM. We do not supporting changing the cache file size.

**Comment by keithc-ca** [comment]
I added some more information in the issue: https://github.com/eclipse/openj9/issues/9838#issuecomment-642780974. Perhaps that will answer your question about the call stack (no call stacks are available in the javacore file).

This occurs during a build creating `jmod` files: no other processes should be accessing shared caches beside the bootjdk and the build jdk.

**Comment by keithc-ca** [comment]
An alternate solution would be to change the format so the length of the result is not sensitive to the values:
```
#if defined(J9VM_ENV_DATA64)
  const char * const format = "%s-%016llx_%016llx_%016zx_%016zx_%016zx_%016zx";
#else
  const char * const format = "%s-%016llx_%016llx_%08zx_%08zx_%08zx_%08zx";
#endif
```
Thoughts?

**Comment by hangshao0** [comment]
I've looked at the trace points. I think it should be called from line 1716 at CompositeCache.cpp. Putting the call inside if (NULL != _previous) should fix this. 

We don't expect any of the values (fileSize/metadataBytes/varTabBytes ect.) used in the cacheUniqueID to change. If changed, something is wrong and we should assert.

**Comment by keithc-ca** [comment]
Wouldn't Avoiding that call would mean the unique id is not computed: isn't it needed by higher layers?

**Comment by hangshao0** [comment]
> isn't it needed by higher layers?

Yes, it is needed by its higher layer only. 
If _previous is NULL, it is the top layer. It has no higher layer, so no need to call getCacheUniqueID(). (If another JVM creates a higher layer in the future, that JVM will compute the unique ID)
If  _previous is not NULL, it has a higher layer, so we call getCacheUniqueID().

I saw `C290M11F1A64P_sharedcc_keithc_G41L00` only in the trace, I didn't see its higher layer `C290M11F1A64P_sharedcc_keithc_G41L01`, so `C290M11F1A64P_sharedcc_keithc_G41L00` should be the top(highest) layer. There is no need to compute unique ID in this case.

**Comment by keithc-ca** [comment]
So I'm clear, there's no unique ID stored in a bottom layer
(e.g. `C290M11F1A64P_sharedcc_keithc_G41L00`)?

**Comment by hangshao0** [comment]
> So I'm clear, there's no unique ID stored in a bottom layer
> (e.g. C290M11F1A64P_sharedcc_keithc_G41L00)?

No.

**Comment by keithc-ca** [comment]
Jenkins test sanity zlinux jdk8

File: runtime/shared_common/CompositeCache.cpp [hunk 1]
```diff
@@ -1711,7 +1711,8 @@ SH_CompositeCacheImpl::startup(J9VMThread* currentThread, J9SharedClassPreinitCo
 	}
 	if (rc == CC_STARTUP_OK) {
 		_started = true;
-		if (NULL == cacheMemory) {
+		/* We don't need to compute the cache id for layer 0. */
```
Comment (hangshao0) [inline runtime/shared_common/CompositeCache.cpp:1714]: "We don't need to compute the cache id for layer 0" should be:
"We don't need to compute the cache id for the top layer". 
The cache ID is needed only by its higher layer. Top layer does not have a higher layer, so no need to compute cache id for the top layer.

File: runtime/shared_common/CacheMap.hpp [hunk 2]
```diff
@@ -39,7 +39,18 @@
...
+ */
+#define J9HEX_WIDTH(T) (2 * sizeof(T))
+
+/*
+ * A unique cache id is a path followed by six hexadecimal values,
+ * the first two of which express 64-bits values and the remaining
+ * four express UDATA values. Additionally, there are six separator
+ * characters and a terminating NUL character.
+ */
+#define J9SHR_UNIQUE_CACHE_ID_BUFSIZE (J9SH_MAXPATH + (2 * J9HEX_WIDTH(U_64)) + (4 * J9HEX_WIDTH(UDATA)) + 6 + 1)
```
Comment (hangshao0) [inline runtime/shared_common/CacheMap.hpp:53]: `J9SHR_UNIQUE_CACHE_ID_BUFSIZE` or `J9SHR_CACHE_UNIQUE_ID_BUFSIZE` ? The function name is `generateCacheUniqueID`

File: runtime/shared_common/CompositeCache.cpp (hunk 1 above)
Comment (keithc-ca) [reply runtime/shared_common/CompositeCache.cpp:1714]: Your earlier comments left me with the understanding that a layer stores the unique id of the below it. A layer 0 cache has no layers below it and so doesn't need to compute or store an id.

File: runtime/shared_common/CacheMap.hpp (hunk 2 above)
Comment (keithc-ca) [reply runtime/shared_common/CacheMap.hpp:53]: I didn't change the name of the macro, just its value.

Comment (hangshao0) [reply runtime/shared_common/CacheMap.hpp:53]: Ah, I see.

File: runtime/shared_common/CompositeCache.cpp (hunk 1 above)
Comment (hangshao0) [reply runtime/shared_common/CompositeCache.cpp:1714]: > a layer stores the unique id of the below it. A layer 0 cache has no layers below it

This is correct. 

> so doesn't need to compute or store an id.

The layer 0 does not store an id. But the cache id of layer 0 may needs to be computed. 
If there is a layer 1, the cache unique ID of layer 0 needs to be computed, and stored in layer 1.
If there is no layer 1, layer 0 is the top layer. There is no need to compute or stored id of layer 0.

**Comment by keithc-ca** [comment]
I'll wait for [testing](https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/3861/) to complete before updating the comment as requested.

**Comment by keithc-ca** [comment]
Updated commit and code comments.

**Comment by pshipton** [comment]
jenkins test extended win jdk11
