### PR TITLE
Lock the cache inside markItemStaleCheckMutex().

### LINKED ISSUE #6330: Windows build crash shared classes vmState=0x00080001 SH_CompositeCacheImpl::markStale
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_windows_Nightly/84
```
23:31:12  Creating jdk image
23:31:12  Unhandled exception
23:31:12  Type=Segmentation error vmState=0x00080001
23:31:12  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFC83877B3D ContextFlags=0010005f
23:31:12  Handler1=00007FFC83E8C9F0 Handler2=00007FFC83D9EFE0 InaccessibleWriteAddress=00000078D65CD150
23:31:12  RDI=00000078D65CD000 RSI=0000000000019A00 RAX=0000000000000000 RBX=00000078C4071608
23:31:12  RCX=00007FFC97570C5A RDX=0000000000000000 R8=00000078C37CD2E8 R9=00000078C37CD3C8
23:31:12  R10=0000000000000000 R11=0000000000000206 R12=00000078D91DFB50 R13=00000078D65CD138
23:31:12  R14=0000000000001000 R15=0000000000000000
23:31:12  RIP=00007FFC83877B3D RSP=00000078C37CD3B0 RBP=00000078D65CD150 GS=002B
23:31:12  FS=0053 ES=002B DS=002B
23:31:12  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM6 0000000000019598 (f: 103832.000000, d: 5.129982e-319)
23:31:12  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:31:12  Module=c:\Users\jenkins\workspace\Build_JDK11_x86-64_windows_Nightly\build\windows-x86_64-normal-server-release\jdk\bin\compressedrefs\j9shr29.dll
23:31:12  Module_base_address=00007FFC83860000 Offset_in_DLL=0000000000017b3d
23:31:12  Target=2_90_20190703_84 (Windows Server 2012 R2 6.3 build 9600)
23:31:12  CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
23:31:12  ----------- Stack Backtrace -----------
23:31:13  SH_CompositeCacheImpl::markStale+0x38d (compositecache.cpp:3287, 0x00007FFC83877B3D [j9shr29+0x17b3d])
23:31:13  SH_CacheMap::markItemStaleCheckMutex+0xd0 (cachemap.cpp:4363, 0x00007FFC8388B020 [j9shr29+0x2b020])
23:31:13  SH_ROMClassManagerImpl::locateROMClass+0x890 (romclassmanagerimpl.cpp:515, 0x00007FFC838AD960 [j9shr29+0x4d960])
23:31:13  SH_CacheMap::findROMClass+0x2eb (cachemap.cpp:2490, 0x00007FFC83887A5B [j9shr29+0x27a5b])
23:31:13  hookFindSharedClass+0x5d9 (shrinit.cpp:1443, 0x00007FFC83864C49 [j9shr29+0x4c49])
23:31:13  J9HookDispatch+0x153 (hookable.cpp:237, 0x00007FFC83DE1473 [J9HOOKABLE29+0x1473])
23:31:13  callFindLocallyDefinedClass+0x176 (classsupport.c:496, 0x00007FFC83E80146 [j9vm29+0x70146])
23:31:13  attemptDynamicClassLoad+0xf6 (classsupport.c:567, 0x00007FFC83E80386 [j9vm29+0x70386])
23:31:13  internalFindClassInModule+0x64e (classsupport.c:1089, 0x00007FFC83E7BB5E [j9vm29+0x6bb5e])
23:31:13  internalFindClassString+0x158 (classsupport.c:281, 0x00007FFC83E7B4B8 [j9vm29+0x6b4b8])
23:31:13  ?run@VM_BytecodeInterpreter@@QEAA_KPEAUJ9VMThread@@@Z+0x112ab (0x00007FFC83E2234B [j9vm29+0x1234b])
23:31:13  (0x00000000FF819B48)
23:31:13  (0x00000078C31002A8)
23:31:13  (0x00000078C37CE2A0)
23:31:13  (0x0000000000000010)
23:31:13  (0x0000000000000008)
23:31:13  (0x00000000000F6A40)
23:31:13  (0x00000078C37CE0B8)
23:31:13  (0x00000078C37CE0C8)
23:31:13  (0x000000000000003C)
23:31:13  (0x0000000000019A00)
23:31:13  (0x0000000000000030)
23:31:13  (0x0000000000019598)
23:31:13  (0x00000078C37CE028)
23:31:13  (0x00000000000F8338)
23:31:13  (0x00000078C37CE050)
23:31:13  (0x00000078C37CE060)
23:31:13  (0x0000000000000001)
23:31:13  (0x00000078C37CE030)
23:31:13  (0x0000000000019AF8)
23:31:13  (0x00000078C37CE0C0)
23:31:13  (0x0000000000019728)
23:31:13  ?run@VM_BytecodeInterpreter@@QEAA_KPEAUJ9VMThread@@@Z+0x19b7f (0x00007FFC83E2AC1F [j9vm29+0x1ac1f])
23:31:13  (0x00000000000003C0)
23:31:13  (0x0000000000019A00)
23:31:13  (0x00000000000F6A40)
23:31:13  (0x00000078C37CE0C0)
23:31:13  (0x0000000000000030)
```

### PR DESCRIPTION
**Pull request by hangshao0**
Readers can change the page protection when reading cache updates,
resulting in SIGSEGV if another thread is marking cache item stale. Lock
the cache to make sure there are no readers.

Fixes #6330

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

File: runtime/shared_common/CacheMap.cpp [hunk 1]
```diff
@@ -4583,10 +4583,15 @@ SH_CacheMap::markItemStaleCheckMutex(J9VMThread* currentThread, const ShcItem* i
 	Trc_SHR_CM_markItemStaleCheckMutex_Entry(currentThread, item);
 
 	if (_ccHead->hasWriteMutex(currentThread)) {
+		if (!isCacheLocked) {
+			_ccHead->doLockCache(currentThread);		/* Wait till all readers stop and unprotect metadata area */
+			isCacheLocked = true;
+		}
 		_ccHead->markStale(currentThread, (BlockPtr)ITEMEND(item), isCacheLocked);
```
Comment (pshipton) [inline runtime/shared_common/CacheMap.cpp]: How about using `true` instead of `isCacheLocked`, and then the parameter `isCacheLocked` doesn't need to be set to true above.

Comment (hangshao0) [reply runtime/shared_common/CacheMap.cpp]: Changed to use `true` directly.

**Comment by pshipton** [comment]
jenkins test sanity,extended zlinux jdk8

**Comment by pshipton** [comment]
@hangshao0 please create the same change against the v0.16.0-release branch. Once the testing passes I'll merge both.

**Comment by hangshao0** [comment]
PR for v0.16.0 branch: https://github.com/eclipse/openj9/pull/7040
