### PR TITLE
Fix racing condition that set and unset string intern table flag

### LINKED ISSUE #6472: Test_openjdk11_j9_sanity.functional_x86-64_linux TestMemoryMXBean crash vmState=0x00040000
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly/92
No artifacts captured.
```
23:45:29  [TestMemoryMXBean] [INFO] Starting TestMemoryMXBean tests ...
23:45:29  Unhandled exception
23:45:29  Type=Segmentation error vmState=0x00040000
23:45:29  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
23:45:29  Handler1=00007FA11D1833E0 Handler2=00007FA11CA7D520 InaccessibleAddress=00007FA0D7004CDA
23:45:29  RDI=00007FA118109D80 RSI=0000000000000006 RAX=0000000000000008 RBX=00007FA0D7004CD4
23:45:29  RCX=00000000FFFFFFFF RDX=0000000000000530 R8=00007FA0D6308000 R9=FFFFFFFFBE6C9338
23:45:29  R10=00007FA0D701C3B8 R11=00007FA0D7004CD4 R12=00007FA118109D80 R13=00007FA0D6308150
23:45:29  R14=00007FA0D701C3B8 R15=00007FA0D6308000
23:45:29  RIP=00007FA11D1F82FD GS=0000 FS=0000 RSP=00007FA0D6307FC0
23:45:29  EFlags=0000000000010293 CS=0033 RBP=00007FA1180D2260 ERR=0000000000000007
23:45:29  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007FA0D7004CDA
23:45:29  xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:45:29  xmm1 6d6e65706f2f746e (f: 1865380992.000000, d: 1.341241e+219)
23:45:29  xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:45:29  xmm3 626d754e656e694c (f: 1701734784.000000, d: 1.357107e+166)
23:45:29  xmm4 0000000048506bc0 (f: 1213230080.000000, d: 5.994153e-315)
23:45:29  xmm5 3fed259320000000 (f: 536870912.000000, d: 9.108368e-01)
23:45:29  xmm6 3ff190f6c151a1fc (f: 3243352576.000000, d: 1.097892e+00)
23:45:29  xmm7 3bbcc86800000000 (f: 0.000000, d: 6.095003e-21)
23:45:29  xmm8 402b8a02b8fa766d (f: 3103421952.000000, d: 1.376955e+01)
23:45:29  xmm9 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
23:45:29  xmm10 beb9000000000000 (f: 0.000000, d: -1.490116e-06)
23:45:29  xmm11 3d735816bc5ca07e (f: 3160186880.000000, d: 1.099585e-12)
23:45:29  xmm12 bebb72818e0f8d1a (f: 2383383808.000000, d: -1.635986e-06)
23:45:29  xmm13 3be2f6aed68c0614 (f: 3599500800.000000, d: 3.212560e-20)
23:45:29  xmm14 402bb9d3beb8c600 (f: 3199780352.000000, d: 1.386294e+01)
23:45:29  xmm15 0000000046b75168 (f: 1186419072.000000, d: 5.861689e-315)
23:45:29  Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
23:45:29  Module_base_address=00007FA11D0E4000
23:45:29  Target=2_90_20190713_93 (Linux 2.6.32-754.11.1.el6.x86_64)
23:45:29  CPU=amd64 (4 logical CPUs) (0x1ec001000 RAM)
23:45:29  ----------- Stack Backtrace -----------
23:45:29  (0x00007FA11D1F82FD [libj9vm29.so+0x1142fd])
23:45:29  (0x00007FA11D1F898F [libj9vm29.so+0x11498f])
23:45:29  (0x00007FA11D1EB34B [libj9vm29.so+0x10734b])
23:45:29  (0x00007FA11D1E85E2 [libj9vm29.so+0x1045e2])
23:45:29  (0x00007FA11D1E918E [libj9vm29.so+0x10518e])
23:45:29  (0x00007FA11D1E9C60 [libj9vm29.so+0x105c60])
23:45:29  (0x00007FA11D1EA334 [libj9vm29.so+0x106334])
23:45:29  (0x00007FA11D1DF414 [libj9vm29.so+0xfb414])
23:45:29  (0x00007FA11D1E065E [libj9vm29.so+0xfc65e])
23:45:29  (0x00007FA11D173AC2 [libj9vm29.so+0x8fac2])
23:45:29  (0x00007FA11D174EEB [libj9vm29.so+0x90eeb])
23:45:29  (0x00007FA11D17708E [libj9vm29.so+0x9308e])
23:45:29  (0x00007FA11D1168F8 [libj9vm29.so+0x328f8])
23:45:29  (0x00007FA11D0FCD90 [libj9vm29.so+0x18d90])
23:45:29  (0x00007FA11D1BE4F2 [libj9vm29.so+0xda4f2])
23:45:29  ---------------------------------------
```

### PR DESCRIPTION
**Pull request by hangshao0**
Move the code to unset J9AVLTREE_DISABLE_SHARED_TREE_UPDATES into
SH_CacheMap::enterStringTableMutex() so that is done inside ReadWrite
Mutex.

Fixes #6472

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

File: runtime/shared_common/CacheMap.cpp [hunk 1]
```diff
@@ -5251,9 +5251,11 @@ SH_CacheMap::enterStringTableMutex(J9VMThread* currentThread, BOOLEAN readOnly,
 				table->tailNode = SRP_PTR_GET(table->sharedTailNodePtr, J9SharedInternSRPHashTableEntry *);
 			}
 
-			if (J9_ARE_ANY_BITS_SET(_sharedClassConfig->runtimeFlags, J9SHR_RUNTIMEFLAG_BLOCK_SPACE_FULL | J9SHR_RUNTIMEFLAG_AVAILABLE_SPACE_FULL)) {
+			if (readOnly || J9_ARE_ANY_BITS_SET(_sharedClassConfig->runtimeFlags, J9SHR_RUNTIMEFLAG_BLOCK_SPACE_FULL | J9SHR_RUNTIMEFLAG_AVAILABLE_SPACE_FULL)) {
 				/* Disable all updates to the shared tree */
 				table->flags |= J9AVLTREE_DISABLE_SHARED_TREE_UPDATES;
+			} else {
+				table->flags &= ~J9AVLTREE_DISABLE_SHARED_TREE_UPDATES;
```
Comment (pshipton) [inline runtime/shared_common/CacheMap.cpp]: Shouldn't this check `currentThread->javaVM->sharedInvariantInternTable != NULL`?

Comment (pshipton) [reply runtime/shared_common/CacheMap.cpp]: Nm, I see it above now.

**Comment by pshipton** [comment]
jenkins test sanity xlinux,xlinuxxl jdk8,jdk11
