### PR TITLE
Do not enter class segment mutex inside read mutex

### LINKED ISSUE #9893: JVMSHRC129E Attempt to set readerCount to -1!
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly/394
SharedClasses.SCM01.MultiThreadMultiCL_0
```
MTM5 stderr JVMSHRC129E Attempt to set readerCount to -1!
MTM3 stderr JVMSHRC129E Attempt to set readerCount to -1!
MTM4 stderr JVMSHRC129E Attempt to set readerCount to -1!
MTM1 stderr JVMSHRC129E Attempt to set readerCount to -1!
MTM2 stderr JVMSHRC129E Attempt to set readerCount to -1!
```
```
MTM1 stderr Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NullPointerException
MTM1 stderr 	at java.base/sun.util.locale.provider.JRELocaleProviderAdapter.getCalendarProvider(JRELocaleProviderAdapter.java:349)
MTM1 stderr 	at java.base/sun.util.locale.provider.JRELocaleProviderAdapter.getLocaleServiceProvider(JRELocaleProviderAdapter.java:115)
MTM1 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:281)
MTM1 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)
MTM1 stderr 	at java.base/java.util.Calendar.createCalendar(Calendar.java:1692)
MTM1 stderr 	at java.base/java.util.Calendar.getInstance(Calendar.java:1629)
MTM1 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.logMessage(LoaderSlaveMultiThreadMultiCL.java:120)
MTM1 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.run(LoaderSlaveMultiThreadMultiCL.java:102)
MTM1 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.main(LoaderSlaveMultiThreadMultiCL.java:59)
MTM1 stderr Caused by: java.lang.NullPointerException
MTM1 stderr 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:231)
MTM1 stderr 	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
MTM1 stderr 	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:969)
MTM1 stderr 	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
MTM1 stderr 	... 9 more
```

### PR DESCRIPTION
**Pull request by hangshao0**
We always update the romclass segment at the end of
SH_CacheMap:findROMClass() if a class is returned. There is no 
need to update romclass segment in other places in findROMClass().

Fixes #9893

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

File: runtime/shared_common/CacheMap.cpp [hunk 1]
```diff
@@ -1775,21 +1774,8 @@ SH_CacheMap::runEntryPointChecks(J9VMThread* currentThread, void* address, const
...
-			hasClassSegmentMutex = true;
-		}
-	}
-	itemsAdded = refreshHashtables(currentThread, hasClassSegmentMutex);
-	if (classSegmentMutexAcquired) {
-		exitLocalMutex(currentThread, currentThread->javaVM->classMemorySegments->segmentMutex, "class segment mutex", "CM runEntryPointChecks");
-	}
 
-	if (-1 == itemsAdded) {
+	if ((itemsAdded = refreshHashtables(currentThread, hasClassSegmentMutex)) == -1) {
```
Comment (pshipton) [inline runtime/shared_common/CacheMap.cpp:1778]: Since the code is modified, the constant here and the next change should be on the left.

**Comment by pshipton** [comment]
Pls assert in updateROMSegmentList() the caller doesn't have the read mutex.

File: runtime/shared_common/CacheMap.cpp (hunk 1 above)
Comment (hangshao0) [reply runtime/shared_common/CacheMap.cpp]: Fixed.

**Comment by hangshao0** [comment]
> Pls assert in updateROMSegmentList() the caller doesn't have the read mutex.

enterReadMutex() does not really enter any mutex, it just increase _theca->readerCount by 1. So we are unable to test if the caller has the "read mutex" or not.

**Comment by pshipton** [comment]
jenkins test sanity,extended plinux,win jdk11

**Comment by pshipton** [comment]
We can assert the _theca->readerCount is 0?

**Comment by hangshao0** [comment]
> We can assert the _theca->readerCount is 0?

No, we cannot. Other threads (in this JVM or another JVM) can change readerCount anytime.

**Comment by pshipton** [comment]
jenkins test sanity,extended plinux,win jdk11

**Comment by pshipton** [comment]
How about using a thread local flag to track if the read mutex is held. I see there is a J9_PRIVATE_FLAGS2 space available for additional flags.

**Comment by hangshao0** [comment]
> How about using a thread local flag to track if the read mutex is held. I see there is a J9_PRIVATE_FLAGS2 (privateFlags2)space available for additional flags in the J9VMThread struct.

Yes, this can be done. I will create a Pull Request on this.
